### PR TITLE
Revert workaround for mdspan with CUDA 12.9

### PR DESCRIPTION
**Pull request by tpadioleau**
Compiling Kokkos with `cmake -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_DEPRECATED_CODE_5=OFF -B build-cuda` and CUDA 12.9 results in the following error
```
 21%] Building CXX object core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o
nvcc warning : Support for offline compilation for architectures prior to '<compute/sm/lto>_75' will be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/TP026749/kokkos/core/src/View/Kokkos_ViewTraits.hpp(492): error: class "Kokkos::Impl::ViewDataAnalysis<uint32_t *, Kokkos::Cuda::array_layout, uint32_t>" has no member "type"
    using data_type = typename data_analysis::type;
                                              ^
          detected during:
            instantiation of class "Kokkos::ViewTraits<DataType, Properties...> [with DataType=uint32_t *, Properties=<Kokkos::CudaSpace>]" at line 214 of /home/TP026749/kokkos/core/src/View/Kokkos_ViewLegacy.hpp
            instantiation of class "Kokkos::View<DataType, Properties...> [with DataType=uint32_t *, Properties=<Kokkos::CudaSpace>]" at line 28 of /home/TP026749/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp

/home/TP026749/kokkos/core/src/View/Kokkos_ViewTraits.hpp(493): error: class "Kokkos::Impl::ViewDataAnalysis<uint32_t *, Kokkos::Cuda::array_layout, uint32_t>" has no member "const_type"
    using const_data_type = typename data_analysis::const_type;
                                                    ^
          detected during:
            instantiation of class "Kokkos::ViewTraits<DataType, Properties...> [with DataType=uint32_t *, Properties=<Kokkos::CudaSpace>]" at line 214 of /home/TP026749/kokkos/core/src/View/Kokkos_ViewLegacy.hpp
            instantiation of class "Kokkos::View<DataType, Properties...> [with DataType=uint32_t *, Properties=<Kokkos::CudaSpace>]" at line 28 of /home/TP026749/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp

/home/TP026749/kokkos/core/src/View/Kokkos_ViewTraits.hpp(494): error: class "Kokkos::Impl::ViewDataAnalysis<uint32_t *, Kokkos::Cuda::array_layout, uint32_t>" has no member "non_const_type"
    using non_const_data_type = typename data_analysis::non_const_type;
                                                        ^
          detected during:
            instantiation of class "Kokkos::ViewTraits<DataType, Properties...> [with DataType=uint32_t *, Properties=<Kokkos::CudaSpace>]" at line 214 of /home/TP026749/kokkos/core/src/View/Kokkos_ViewLegacy.hpp
            instantiation of class "Kokkos::View<DataType, Properties...> [with DataType=uint32_t *, Properties=<Kokkos::CudaSpace>]" at line 28 of /home/TP026749/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp

/home/TP026749/kokkos/core/src/View/Kokkos_ViewLegacy.hpp(242): error: class "Kokkos::ViewTraits<uint32_t *, Kokkos::CudaSpace>" has no member "scalar_array_type"
        View<typename traits::scalar_array_type, typename traits::array_layout,
                              ^
          detected during instantiation of class "Kokkos::View<DataType, Properties...> [with DataType=uint32_t *, Properties=<Kokkos::CudaSpace>]" at line 28 of /home/TP026749/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp

/home/TP026749/kokkos/core/src/View/Kokkos_ViewLegacy.hpp(245): error: class "Kokkos::ViewTraits<uint32_t *, Kokkos::CudaSpace>" has no member "scalar_array_type"
        View<typename traits::scalar_array_type, typename traits::array_layout,
                              ^
          detected during instantiation of class "Kokkos::View<DataType, Properties...> [with DataType=uint32_t *, Properties=<Kokkos::CudaSpace>]" at line 28 of /home/TP026749/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp

5 errors detected in the compilation of "/home/TP026749/kokkos/core/src/impl/Kokkos_Core.cpp".
gmake[2]: *** [core/src/CMakeFiles/kokkoscore.dir/build.make:121: core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:1289: core/src/CMakeFiles/kokkoscore.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

In this PR I suggest to revert the workaround introduced in https://github.com/kokkos/kokkos/pull/8169 because there is a workaround available in mdspan to handle CUDA >=12.9, see https://github.com/kokkos/kokkos/pull/8615 and https://github.com/kokkos/kokkos/pull/8562.

The changes in `core/src/View/Kokkos_ViewTraits.hpp` and `core/src/View/Kokkos_ViewLegacy.hpp` make it possible to compile with `Kokkos_ENABLE_DEPRECATED_CODE_5=OFF` and `Kokkos_ENABLE_IMPL_VIEW_LEGACY=ON`.

### CODE REVIEW

File: core/src/View/Kokkos_ViewTraits.hpp [hunk 1]
```diff
@@ -488,7 +488,8 @@ struct ViewTraits {
  public:
   //------------------------------------
   // Data type traits:
-#ifdef KOKKOS_ENABLE_IMPL_VIEW_LEGACY
+#if defined(KOKKOS_ENABLE_IMPL_VIEW_LEGACY) && \
+    defined(KOKKOS_ENABLE_DEPRECATED_CODE_5)
```
Comment (science-enthusiast) [inline core/src/View/Kokkos_ViewTraits.hpp:492]: This PR is building on #7360 and #8614. It looks like #8614 assumed `KOKKOS_ENABLE_DEPRECATED_CODE_5` to be `ON`, in order to support legacy View. Have we documented some where that to enable legacy View support both `KOKKOS_ENABLE_IMPL_VIEW_LEGACY` and `KOKKOS_ENABLE_DEPRECATED_CODE_5` have to be `ON`?

Comment (masterleinad) [reply core/src/View/Kokkos_ViewTraits.hpp:492]: `KOKKOS_ENABLE_IMPL_VIEW_LEGACY` isn't supposed to be an user-facing option anyway.

Comment (science-enthusiast) [reply core/src/View/Kokkos_ViewTraits.hpp:492]: ok. My question is whether Sacado/Stokhos in Trilinos could break if both `Kokkos_ENABLE_IMPL_MDSPAN` and `Kokkos_ENABLE_DEPRECATED_CODE_5` are `OFF`.

Comment (science-enthusiast) [reply core/src/View/Kokkos_ViewTraits.hpp:492]: Given the name `Kokkos_ENABLE_IMPL_MDSPAN`, maybe this is also not user facing. That means I am still in the process of understanding how Trilinos uses legacy View if it wants to.

Comment (tpadioleau) [reply core/src/View/Kokkos_ViewTraits.hpp:492]: To be clear, legacy view used to be enabled with CUDA 12.9. This PR is changing this behavior, it turns it off by default.

If you prefer that we don't try to make the legacy view work when disabling deprecated code 5, it is ok for me to revert these changes.

**Review by masterleinad — APPROVED** [review]
Fine with me.

File: core/src/View/Kokkos_ViewTraits.hpp (hunk 1 above)
Comment (masterleinad) [reply core/src/View/Kokkos_ViewTraits.hpp:492]: I don't think it's necessarily a priority but I think it's fine to do it here as well.

Comment (science-enthusiast) [reply core/src/View/Kokkos_ViewTraits.hpp:492]: Yes, I see what we are trying to do with CUDA 12.9.

I was wondering whether Trilinos needs to ensure that `Kokkos_ENABLE_DEPRECATED_CODE_5` should be `ON` for them to work to with the legacy View.

Comment (crtrott) [reply core/src/View/Kokkos_ViewTraits.hpp:492]: Yeah they do, but its on by default anyway and I don't care about them having to deal with undocumented behavior if they mess with an IMPL option (i.e. turning legacy view on).

**Review by crtrott — APPROVED** [review]

File: core/src/View/Kokkos_ViewTraits.hpp (hunk 1 above)
Comment (science-enthusiast) [reply core/src/View/Kokkos_ViewTraits.hpp:492]: Thanks for the clarification :+1:
