### PR TITLE
Clean up HostIterateTile

### PR DESCRIPTION
**Pull request by masterleinad**
`HostIterateTile` was using specializations for `ParallelFor`, `ParallelReduce` for scalar reductions, and `ParallelReduce` for array reductions duplicating a lot of functionality and some symbols weren't even used.
This pull request unifies the three.

### CODE REVIEW

File: core/src/impl/KokkosExp_Host_IterateTile.hpp
Comment (science-enthusiast) [inline core/src/impl/KokkosExp_Host_IterateTile.hpp]: Since, we are going to use a single `check_iteration_bounds` function for all parallel constructs, this can be:

`[[maybe_unused]] const bool full_tile = check_iteration_bounds(tiledims, offset);`

The implementation of the nested loops for `parallel_reduce` can be improved such that the boolean `full_tile` is not needed. We have a plan that I will try to implement the nested loops for `parallel_reduce` using the recursive templates approach, sometime in the next couple of months.

**Comment by science-enthusiast** [comment]
Retest this please!

**Comment by science-enthusiast** [comment]
Hi, Does `core/unit_test/view/TestCreateMirrorViewAndCopy.hpp` or the associated tests and CI workflows need a fix?

File: core/src/impl/KokkosExp_Host_IterateTile.hpp
Comment (masterleinad) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp]: If it's not used at all, there is no need to define a variable for the returned value, right?

Comment (science-enthusiast) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp]: I see your point. I was not thinking clearly about how this works in C and C++ and I was anticipating warnings.

**Comment by masterleinad** [comment]
> Hi, Does `core/unit_test/view/TestCreateMirrorViewAndCopy.hpp` or the associated tests and CI workflows need a fix?

That's fixes elsewhere and unrelated.

**Review by science-enthusiast — APPROVED** [review]

File: core/src/impl/KokkosExp_Host_IterateTile.hpp [hunk 1]
```diff
@@ -849,40 +849,17 @@ struct Tile_Loop_Type<8, IsLeft, IType, Tagged,
...
-struct HostIterateTile<RP, Functor, Tag, ValueType,
-                       std::enable_if_t<std::is_void_v<ValueType>>> {
+template <typename RP, typename Functor, typename Tag, typename ReferenceType>
+struct HostIterateTile {
   using index_type = typename RP::index_type;
   using point_type = typename RP::point_type;
-
-  using value_type = ValueType;
+  using reference_type =
+      std::conditional_t<std::is_void_v<ReferenceType>, int, ReferenceType>;
```
Comment (dalg24) [inline core/src/impl/KokkosExp_Host_IterateTile.hpp]: Rename it to `reference_type_not_void` or something similar, move it right above the constrained `operator()` that uses it, and add a comment saying that this is needed to workaround  "argument may not be a void type".

Comment (masterleinad) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp]: Here you go!

File: core/src/impl/KokkosExp_Host_IterateTile.hpp [hunk 2]
```diff
@@ -980,9 +978,17 @@ struct HostIterateTile {
   }  // end check bounds
 
   // ParallelReduce
+
+  // The type used in the call operator below mustn't be void which is the case
+  // when using this class with parallel_for. When implementing behavior for
+  // parallel_reduce, ReferenceType isn't void. Hence, we can just resort to a
+  // dummy type in the former case.
+  using valid_reference_type =
+      std::conditional_t<std::is_void_v<ReferenceType>, int&, ReferenceType>;
```
Comment (dalg24) [inline core/src/impl/KokkosExp_Host_IterateTile.hpp]: I am not sure why you ref qualified the `int`.  I think it is straying the reader away.
The "not void" requires clause is not enough to "guard" for a trailing argument that resolves to `void`.
I find that spelling out the compile error without the workaround more helpful that the comment in its current form.

Comment (science-enthusiast) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp]: Hi, Could you clarify this point?
The "not void" requires clause is not enough to "guard" for a trailing argument that resolves to void.

Comment (dalg24) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp]: With the requires clause `requires(!std::is_void_v<ReferenceType>)`, the operator() does not participate in overload resolution when `ReferenceType` is `void` but if we use `ReferenceType` directly as the type for the `val` parameter, the compiler will error out.  Hence we pick some type that is not void, anything that can be a valid parameter type.

Comment (science-enthusiast) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp]: Thanks for the clarification. Yes, I knew why `valid_reference_type` had to be defined and that `ReferenceType` cannot be used directly. The requires clause is applied afterwards. Before that a valid function signature is needed by the compiler. void as function parameter type will lead to compilation error.

Comment (science-enthusiast) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp]: I mean, I didn't know this before this PR. But I saw what Daniel had done while reviewing the PR. I investigated and understood this approach.

File: core/src/impl/KokkosExp_Host_IterateTile.hpp [hunk 3]
```diff
@@ -1029,14 +977,18 @@ struct HostIterateTile<RP, Functor, Tag, ValueType,
...
+  // void in the call operator below, we still get a compiler error saying:
+  //   error: argument may not have 'void' type
+  // Hence, just use a different type in that case to make the compiler happy.
+  using valid_reference_type =
+      std::conditional_t<std::is_void_v<ReferenceType>, int, ReferenceType>;
 
   template <typename IType>
-  inline void operator()(IType tile_idx, value_type& val) const {
+    requires(!std::is_void_v<ReferenceType>)
+  inline void operator()(IType tile_idx, valid_reference_type val) const {
```
Comment (tretre91) [inline core/src/impl/KokkosExp_Host_IterateTile.hpp:1597]: Can you try with this?
```suggestion
  template <typename IType>
  inline void operator()(IType tile_idx,
                         std::enable_if_t<std::is_same_v<IType, IType> &&
                                              !std::is_void_v<ReferenceType>,
                                          ReferenceType>
                             val) const {
```
This compiles fine on my laptop with gcc 13.3.0. 
We need `std::is_same_v<IType, IType>` to introduce a dependency on a template parameter which is only known when the function is instantiated, otherwise instantiating the class with `ReferenceType` as `void` would fail
Putting this `enable_if` in the template argument list leads to the same compile error you had

Comment (masterleinad) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp:1597]: I mean we can but is this really better than what we have right now?

Comment (tretre91) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp:1597]: Not sure, I'm fine with the current state anyway

**Review by tretre91 — APPROVED** [review]

File: core/src/impl/KokkosExp_Host_IterateTile.hpp (hunk 3 above)
Comment (science-enthusiast) [reply core/src/impl/KokkosExp_Host_IterateTile.hpp:1597]: In your solution also one needs a comment to explain the need for `std::is_same_v<IType, IType>`.

But nice to know about your solution.

**Comment by dalg24** [comment]
Needs conflict resolution

**Comment by masterleinad** [comment]
> Needs conflict resolution

Done.
