### ISSUE TITLE
Nightly build failure, intel/19.0.5 icpc, kokkos/core/src/Kokkos_CopyViews.hpp(1403): error: expected a ")"

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7273]
**Describe the bug**

Builds with intel/19.0.5 icpc fail to compile with a nonsense error
```
11:09:50 /home/jenkins/node/workspace/kokkos_osrhel7_intel_1905-dbg/kokkos/core/src/Kokkos_CopyViews.hpp(1403): error: expected a ")"
11:09:50       ZeroMemset(exec, dst.data(),
11:09:50                      ^
11:09:50           detected during instantiation of "void Kokkos::deep_copy(const Kokkos::View<DT, DP...> &, Kokkos::ViewTraits<DT, DP...>::const_value_type &, std::enable_if_t<std::is_same_v, void> *) [with DT=int *, DP=<>]" at line 48 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905-dbg/kokkos/core/unit_test/TestLegionInitialization.cpp"
11:09:50 
11:09:50 /home/jenkins/node/workspace/kokkos_osrhel7_intel_1905-dbg/kokkos/core/src/Kokkos_CopyViews.hpp(1403): error #1599: declaration hides variable "exec" (declared at line 1397)
11:09:50       ZeroMemset(exec, dst.data(),
```

though the parenthesis all clearly have open-close pairs within https://github.com/kokkos/kokkos/blob/662043966274936f2c7a367e58975f06c2814cf7/core/src/Kokkos_CopyViews.hpp#L1402-L1404  🤷 

This follows merge of #7226 

**Please include the following for a minimal reproducer**
**Reproducer configuration:**
```bash
module load sems-cmake sems-intel/19.0.5

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial  --compiler=icpc --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -diag-disable=1011,-diag-disable=869" --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --debug
```

**Comment by ndellingwood** [comment]
Thanks @tcclevenger , intel/19 nightlies are back to passing state
