### ISSUE TITLE
Cuda instance will not compile after PR 6299 (`==` in signature)

### ISSUE THREAD

**Issue by romintomasetti** [kokkos/kokkos#6344]
The following signatures are incorrect.

https://github.com/kokkos/kokkos/blob/11c6cf74bfda55fdf318682c4d234924ef5ca4d7/core/src/Cuda/Kokkos_Cuda_Instance.hpp#L487-L500

It would give:
```c++
/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.hpp(490): error: expected a ")"
                                           cudaStream_t hStream == nullptr) const {
                                                                ^
```

I guess `cudaStream_t hStream = nullptr` is needed instead.

Introduced in https://github.com/kokkos/kokkos/commit/ba6b4d9d1c23dbbfeee1ef5d90bba157d30d7f0c by @tcclevenger. The error only happens if `KOKKOS_ENABLE_IMPL_CUDA_MALLOC_ASYNC` is enabled and `CUDART_VERSION >= 11020` (this is our case).

Related to:
- #6299.

**Comment by dalg24** [comment]
You are welcome to open a PR to fix the default arguments.

@ndellingwood @tcclevenger is there no coverage for `CUDA_MALLOC_ASYNC` in the nightlies?
No test means no support.

**Comment by ndellingwood** [comment]
> @ndellingwood @tcclevenger is there no coverage for `CUDA_MALLOC_ASYNC` in the nightlies?

@dalg24 I suppose not, I was not aware of the option `KOKKOS_ENABLE_IMPL_CUDA_MALLOC_ASYNC` and the need to explicitly enable it for coverate. Will add nightly tests to cover this case

**Comment by tcclevenger** [comment]
@romintomasetti Since this was a quick fix, I went ahead and made a PR. https://github.com/kokkos/kokkos/pull/6346

**Comment by ndellingwood** [comment]
@dalg24 @tcclevenger nightly job added to test `Kokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC=ON` with cuda/11.2.2, reproduced this error

**Comment by PhilMiller** [comment]
@ndellingwood and others who weren't aware of this non-default option, see #4228 for details of why it's optional and disabled by default.
