### ISSUE TITLE
Nightly compilation failure, intel classic compilers icpc: Kokkos_CopyIf.hpp(152): error #1011: missing return statement

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6502]
**Describe the bug**
Nightly builds with intel/19.0.5, intel/2021.3.0 compilers are failing (Serial, OpenMP and Threads backends) with output:
```
14:32:34 /home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/algorithms/unit_tests/../src/std_algorithms/impl/Kokkos_CopyIf.hpp(152): error #1011: missing return statement at end of non-void function "Kokkos::Experimental::Impl::copy_if_team_impl(const TeamHandleType &, InputIterator, InputIterator, OutputIterator, PredicateType) [with TeamHandleType=Kokkos::Impl::HostThreadTeamMember<Kokkos::Serial>,
14:32:34           InputIterator=Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<Test::stdalgos::value_type={double} *, std::conditional_t<true, std::conditional_t<true, Kokkos::Serial::array_layout, Kokkos::Serial::array_layout>, Kokkos::LayoutStride>, Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>, std::conditional_t<true, Kokkos::MemoryTraits<0U>, Kokkos::MemoryManaged>>>,
14:32:34           OutputIterator=Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<Test::stdalgos::value_type={double} *, std::conditional_t<true, std::conditional_t<true, Kokkos::Serial::array_layout, Kokkos::Serial::array_layout>, Kokkos::LayoutStride>, Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>, std::conditional_t<true, Kokkos::MemoryTraits<0U>, Kokkos::MemoryManaged>>>, PredicateType=Test::stdalgos::TeamCopyIf::GreaterThanValueFunctor<double>]"
14:32:34   }
14:32:34   ^
14:32:34           detected during:
14:32:34             instantiation of "OutputIterator Kokkos::Experimental::Impl::copy_if_team_impl(const TeamHandleType &, InputIterator, InputIterator, OutputIterator, PredicateType) [with TeamHandleType=Kokkos::Impl::HostThreadTeamMember<Kokkos::Serial>, InputIterator=Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<Test::stdalgos::value_type={double} *, std::conditional_t<true, std::conditional_t<true, Kokkos::Serial::array_layout, Kokkos::Serial::array_layout>, Kokkos::LayoutStride>,
14:32:34                       Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>, std::conditional_t<true, Kokkos::MemoryTraits<0U>, Kokkos::MemoryManaged>>>, OutputIterator=Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<Test::stdalgos::value_type={double} *, std::conditional_t<true, std::conditional_t<true, Kokkos::Serial::array_layout, Kokkos::Serial::array_layout>, Kokkos::LayoutStride>, Kokkos::Device<Kokkos::HostSpace::execution_space,
14:32:34                       Kokkos::HostSpace::memory_space>, std::conditional_t<true, Kokkos::MemoryTraits<0U>, Kokkos::MemoryManaged>>>, PredicateType=Test::stdalgos::TeamCopyIf::GreaterThanValueFunctor<double>]" at line 90 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/algorithms/unit_tests/../src/std_algorithms/Kokkos_CopyIf.hpp"
14:32:34             instantiation of "OutputIterator Kokkos::Experimental::copy_if(const TeamHandleType &, InputIterator, InputIterator, OutputIterator, Predicate) [with TeamHandleType=Kokkos::Impl::HostThreadTeamMember<Kokkos::Serial>, InputIterator=Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<Test::stdalgos::value_type={double} *, std::conditional_t<true, std::conditional_t<true, Kokkos::Serial::array_layout, Kokkos::Serial::array_layout>, Kokkos::LayoutStride>,
14:32:34                       Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>, std::conditional_t<true, Kokkos::MemoryTraits<0U>, Kokkos::MemoryManaged>>>, OutputIterator=Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<Test::stdalgos::value_type={double} *, std::conditional_t<true, std::conditional_t<true, Kokkos::Serial::array_layout, Kokkos::Serial::array_layout>, Kokkos::LayoutStride>, Kokkos::Device<Kokkos::HostSpace::execution_space,
14:32:34                       Kokkos::HostSpace::memory_space>, std::conditional_t<true, Kokkos::MemoryTraits<0U>, Kokkos::MemoryManaged>>>, Predicate=Test::stdalgos::TeamCopyIf::GreaterThanValueFunctor<double>, <unnamed>=0]" at line 70 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/algorithms/unit_tests/TestStdAlgorithmsTeamCopyIf.cpp"
14:32:34             instantiation of "void Test::stdalgos::TeamCopyIf::TestFunctorA<SourceViewType, DestViewType, DistancesViewType, IntraTeamSentinelView, ValueType>::operator()(const MemberType &) const [with SourceViewType=Kokkos::View<double **, Kokkos::Serial::memory_space>, DestViewType=Kokkos::View<double **>, DistancesViewType=Kokkos::View<std::size_t={unsigned long} *>, IntraTeamSentinelView=Kokkos::View<bool *>, ValueType=double, MemberType=Kokkos::Impl::HostThreadTeamMember<Kokkos::Serial>]"
14:32:34                       at line 229 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Serial/Kokkos_Serial_Parallel_Team.hpp"
14:32:34             instantiation of "std::enable_if_t<std::is_void<TagType>::value, void> Kokkos::Impl::ParallelFor<FunctorType, Kokkos::TeamPolicy<Properties...>, Kokkos::Serial>::exec<TagType>(Kokkos::Impl::HostThreadTeamData &) const [with FunctorType=Test::stdalgos::TeamCopyIf::TestFunctorA<Kokkos::View<double **, Kokkos::Serial::memory_space>, Kokkos::View<double **>, Kokkos::View<std::size_t={unsigned long} *>, Kokkos::View<bool *>, double>, Properties=<Kokkos::DefaultExecutionSpace>,
14:32:34                       TagType=Kokkos::Impl::WorkTagTrait::base_traits::work_tag]" at line 258 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Serial/Kokkos_Serial_Parallel_Team.hpp"
14:32:34             instantiation of "void Kokkos::Impl::ParallelFor<FunctorType, Kokkos::TeamPolicy<Properties...>, Kokkos::Serial>::execute() const [with FunctorType=Test::stdalgos::TeamCopyIf::TestFunctorA<Kokkos::View<double **, Kokkos::Serial::memory_space>, Kokkos::View<double **>, Kokkos::View<std::size_t={unsigned long} *>, Kokkos::View<bool *>, double>, Properties=<Kokkos::DefaultExecutionSpace>]" at line 144 of
14:32:34                       "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Kokkos_Parallel.hpp"
14:32:34             instantiation of "void Kokkos::parallel_for(const std::__cxx11::string &, const ExecPolicy &, const FunctorType &) [with ExecPolicy=Kokkos::TeamPolicy<Kokkos::DefaultExecutionSpace>, FunctorType=Test::stdalgos::TeamCopyIf::TestFunctorA<Kokkos::View<double **, Kokkos::Serial::memory_space>, Kokkos::View<double **>, Kokkos::View<std::size_t={unsigned long} *>, Kokkos::View<bool *>, double>, Enable=void]" at line 153 of
14:32:34                       "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Kokkos_Parallel.hpp"
14:32:34             instantiation of "void Kokkos::parallel_for(const ExecPolicy &, const FunctorType &, std::enable_if_t<Kokkos::is_execution_policy<ExecPolicy>::value, void> *) [with ExecPolicy=Kokkos::TeamPolicy<Kokkos::DefaultExecutionSpace>, FunctorType=Test::stdalgos::TeamCopyIf::TestFunctorA<Kokkos::View<double **, Kokkos::Serial::memory_space>, Kokkos::View<double **>, Kokkos::View<std::size_t={unsigned long} *>, Kokkos::View<bool *>, double>]" at line 133 of
14:32:34                       "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/algorithms/unit_tests/TestStdAlgorithmsTeamCopyIf.cpp"
14:32:34             instantiation of "void Test::stdalgos::TeamCopyIf::test_A<LayoutTag,ValueType>(std::size_t={unsigned long}, std::size_t={unsigned long}, int) [with LayoutTag=Test::stdalgos::DynamicTag, ValueType=double]" at line 162 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/algorithms/unit_tests/TestStdAlgorithmsTeamCopyIf.cpp"
14:32:34             instantiation of "void Test::stdalgos::TeamCopyIf::run_all_scenarios<LayoutTag,ValueType>() [with LayoutTag=Test::stdalgos::DynamicTag, ValueType=double]" at line 169 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/algorithms/unit_tests/TestStdAlgorithmsTeamCopyIf.cpp"
```

This began following merge of these commits:

    fix impl — [Francesco NMN Rizzi](https://jenkins-son.sandia.gov/user/fnrizzi/) / [githubweb](https://github.com/kokkos/kokkos/commit/1f4e3d5dbc08fed9b49d6658f6a6fd7a6df90d93)
    Split Kokkos_Threads_Parallel files — [bruno.turcksin](https://jenkins-son.sandia.gov/user/bruno.turcksin/) / [githubweb](https://github.com/kokkos/kokkos/commit/cb22b80613c26e68faedf3c3f83f622d56d7e79c)
    address review comment — [Francesco NMN Rizzi](https://jenkins-son.sandia.gov/user/fnrizzi/) / [githubweb](https://github.com/kokkos/kokkos/commit/5b693fd954aa24c8dda6bef128e38e844500a77e)
    SIMD: Split math functions from SIMD_Common.hpp (#6487) — [github](https://jenkins-son.sandia.gov/user/github/) / [githubweb](https://github.com/kokkos/kokkos/commit/f511dca95dd0c065e1de95d190c630a3e9c95602)

**Please also include the following items to support reproducing the bug**
**Reproducer** (kokkos-dev-2 has sems modules avail):
```bash
module load sems-cmake sems-intel/19.0.5

$KOKKOS_PATH/generate_makefile.bash --with-devices=OpenMP  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --no-examples   --with-options=enable_large_mem_tests
```

**Comment by ndellingwood** [comment]
Cross-reference #6493

**Comment by ajpowelsnl** [comment]
not a long-standing issue; fully resolved
