### ISSUE TITLE
intel/16.0.1, intel/17.0.1 nightly build failures with debugging enabled

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2867]
Debug builds with intel/16.0.1 and Serial, OpenMP, and Pthread backeds are failing to compile, with error messages like below:

```
11:12:02 /home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/src/impl/Kokkos_ViewCtor.hpp(240): error #869: parameter "arg" was never referenced
11:12:02     ViewCtorProp(ViewCtorProp<Args...> const &arg)
11:12:02                                               ^
11:12:02           detected during:
11:12:02             instantiation of "Kokkos::Impl::ViewCtorProp<P...>::ViewCtorProp(const Kokkos::Impl::ViewCtorProp<Args...> &) [with P=<std::string, Kokkos::HostSpace::memory_space, Kokkos::HostSpace::execution_space>, Args=<>]" at line 1896 of "/home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/src/Kokkos_View.hpp"
11:12:02             instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::Impl::ViewCtorProp<P...> &, const std::enable_if<<expression>, Kokkos::ViewTraits<DataType, Properties...>::array_layout>::type &) [with DataType=int *[10][5][2], Properties=<Kokkos::LayoutLeft, Kokkos::Serial>, P=<>]" at line 1967 of "/home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/src/Kokkos_View.hpp"
11:12:02             instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::Impl::ViewCtorProp<P...> &, std::enable_if<<expression>, size_t={unsigned long}>::type, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}) [with DataType=int *[10][5][2], Properties=<Kokkos::LayoutLeft, Kokkos::Serial>, P=<>]" at line 2039 of
11:12:02                       "/home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/unit_test/TestViewSubview.hpp"
11:12:02             instantiation of "TestViewSubview::TestSubviewStaticSizes<Space, Layout>::TestSubviewStaticSizes() [with Space=Kokkos::Serial, Layout=Kokkos::LayoutLeft]" at line 95 of "/home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/unit_test/serial/TestSerial_SubView_a.cpp"
```

Reproducer sample:
```
module load sems-env sems-cmake/3.12.2 sems-intel/16.0.1

<KOKKOS_PATH>/generate_makefile.bash --with-devices=Serial  --compiler=/projects/sems/install/rhel6-x86_64/sems/compiler/intel/16.0.1/base/bin/icpc --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="11" --ldflags=""  --kokkos-path=<KOKKOS_PATH> --no-examples --with-options=enable_large_mem_tests --debug
```

**Comment by ndellingwood** [comment]
Also failing in the intel/17.0.1 build, updated the issue title.
