### ISSUE TITLE
Error compiling Lulesh 2.0 with Kokkos with AMD GPU support

### ISSUE THREAD

**Issue by sameershende** [kokkos/kokkos#3499]
Hi, 
   I am trying to use  Kokkos with support for AMD GPUs to compile [Lulesh 2.0.](https://github.com/kokkos/kokkos-miniapps/tree/master/lulesh-2.0/kokkos-optimized). It gives me the following error: 
hipcc -std=c++14  -DKOKKOS_DEPENDENCE --amdgpu-target=gfx906 -fno-gpu-rdc -g -O3 -DRAJA_USE_GETTIME -I./in
cludes -I./ -DUSE_MPI=1  -c lulesh-comm.cc
hipcc -std=c++14  -DKOKKOS_DEPENDENCE --amdgpu-target=gfx906 -fno-gpu-rdc -g -O3 -DRAJA_USE_GETTIME -I./in
cludes -I./ -DUSE_MPI=1  -c lulesh-viz.cc
hipcc -std=c++14  -DKOKKOS_DEPENDENCE --amdgpu-target=gfx906 -fno-gpu-rdc -g -O3 -DRAJA_USE_GETTIME -I./in
cludes -I./ -DUSE_MPI=1  -c lulesh-util.cc
hipcc -std=c++14  -DKOKKOS_DEPENDENCE --amdgpu-target=gfx906 -fno-gpu-rdc -g -O3 -DRAJA_USE_GETTIME -I./in
cludes -I./ -DUSE_MPI=1  -c lulesh-init.cc
hipcc -std=c++14  -DKOKKOS_DEPENDENCE --amdgpu-target=gfx906 -fno-gpu-rdc -g -O3 -DRAJA_USE_GETTIME -I./in
cludes -I./ -DUSE_MPI=1  -c lulesh.cc
In file included from lulesh.cc:13:
./lulesh.h:390:73: error: reference to __host__ function 'operator[]' in __host__ __de
vice__ function
  KOKKOS_INLINE_FUNCTION Real_t &p(const Index_t idx) const { return m_p[idx]; }
                                                                        ^
lulesh.cc:137:46: note: called by 'operator()'
    sigxx[i] = sigyy[i] = sigzz[i] = -domain.p(i) - domain.q(i);
                                             ^
/usr/local/include/HIP/Kokkos_HIP_Parallel_Range.hpp:82:5: note: called by 'exec_range
<void>'
    m_functor(i);
    ^

This used to work with Kokkos 2.7 and 2.9. I was wondering if you have any suggestions on how we should handle this. 

Also, I see that Kokkos no longer supports the Makefile.kokkos file that these older codes used to include. Is there a plan to provide a compatibility Makefile.kokkos file with the new cmake based build systems so we may easily compile these codes that have not been converted to use cmake? To provide support for both cmake and the older build systems? It would help... 

Thanks!

**Comment by masterleinad** [comment]
> This used to work with Kokkos 2.7 and 2.9. I was wondering if you have any suggestions on how we should handle this.

The variable in question is of type `Kokkos::vector` and the access operator[] is only allowed to be called on the device in case `UVM` is used, see https://github.com/kokkos/kokkos/wiki/Kokkos::vector and https://github.com/kokkos/kokkos/blob/09a6952935701873dafc3fcd8233131ea63b5838/containers/src/Kokkos_Vector.hpp#L76-L86.
In particular, this won't work with HIP. Is there any chance that you can use `Kokkos::View` instead?

**Comment by masterleinad** [comment]
> Also, I see that Kokkos no longer supports the Makefile.kokkos file that these older codes used to include. Is there a plan to provide a compatibility Makefile.kokkos file with the new cmake based build systems so we may easily compile these codes that have not been converted to use cmake? To provide support for both cmake and the older build systems? It would help...

Makefile.kokkos still exists and should be useable for inline builds. What kind of problems do you see?

**Comment by sameershende** [comment]
> > Also, I see that Kokkos no longer supports the Makefile.kokkos file that these older codes used to include. Is there a plan to provide a compatibility Makefile.kokkos file with the new cmake based build systems so we may easily compile these codes that have not been converted to use cmake? To provide support for both cmake and the older build systems? It would help...
> 
> Makefile.kokkos still exists and should be useable for inline builds. What kind of problems do you see?

When I install Kokkos, I do not see Makefile.kokkos in the /usr/local hierarchy. I see: 
Singularity> find /usr/local -name Makefile.kokkos
Singularity> ls /usr/local/lib/    
cmake  libkokkoscontainers.a  libkokkoscore.a  librocprofiler64.so  python2.7  python3.6
Singularity> ls /usr/local/lib/cmake
Kokkos
Singularity> ls /usr/local/lib/cmake/Kokkos/
KokkosConfig.cmake	  KokkosConfigVersion.cmake	      KokkosTargets.cmake
KokkosConfigCommon.cmake  KokkosTargets-relwithdebinfo.cmake
Singularity>

**Comment by DavidPoliakoff** [comment]
Hey Sameer, I don't think we're installing Makefile.kokkos anymore, that proved to be a bit of a maintenance nightmare. Let me take a look at the Makefile for Lulesh, I'll see if there's a sane fix for all of this

**Comment by sameershende** [comment]
> > This used to work with Kokkos 2.7 and 2.9. I was wondering if you have any suggestions on how we should handle this.
> 
> The variable in question is of type `Kokkos::vector` and the access operator[] is only allowed to be called on the device in case `UVM` is used, see https://github.com/kokkos/kokkos/wiki/Kokkos::vector and
> 
> https://github.com/kokkos/kokkos/blob/09a6952935701873dafc3fcd8233131ea63b5838/containers/src/Kokkos_Vector.hpp#L76-L86
> 
> .
> In particular, this won't work with HIP. Is there any chance that you can use `Kokkos::View` instead?

I am looking for a Kokkos benchmark that does some significant computation on the AMD GPUs using HIP but without any third party package dependencies (e.g., Arborx).  To use this, it should be based on a cmake build system, since my installation did not include a Makefile.kokkos. I was looking at:
https://github.com/kokkos/kokkos-miniapps
 Do you have any recommendation on which

**Comment by DavidPoliakoff** [comment]
Oh, cool. Daniel develops ArborX, which he can point you at. HIP support is growing, but new, so it's good to talk with Daniel or the other HIP developers to figure out what to run

**Comment by sameershende** [comment]
Hi @DavidPoliakoff ,  In [E4S](https://e4s.io), we do have ArborX running properly with a third-party library - Google's benchmark (spack install benchmark) with Kokkos' cmake build system. We have verified that it can use the AMD GPUs when everything is compiled with hipcc by monitoring the GPU activity. Is there another example that you can recommend that just uses the new cmake based Kokkos build system and will work with AMD GPUs without any other third party libraries? Is there a plan to update the miniapps?

**Comment by DavidPoliakoff** [comment]
Hi Sameer, unfortunately I'm not the most familiar with our HIP work, I'll defer to @masterleinad (Daniel) on that.

**Comment by masterleinad** [comment]
HIP support is mostly feature-complete (apart from Tasking). If `ArborX` already works for you, looking at `LAMMPS` might be a good idea. Maybe, @stanmoore1 can suggest what to run.

**Comment by jrmadsen** [comment]
@sameershende I started working on updating this repo to use CMake and submodules but I couldn't get any of the other examples (beside lulesh) to build via the links in the README. You can use my fork that has CMake support if you want: https://github.com/jrmadsen/kokkos-miniapps/tree/submodules until we merge in some of these commits. 

It doesn't solve the vector instead of view issue but at the very least you will be able to test with pthreads/openmp/cuda-uvm etc. until we get the lulesh example updated.
