### ISSUE TITLE
Error compiling lambdas and default arguments with Cuda/7.5 and gcc/4.9.3

### ISSUE THREAD

**Issue by ramanan** [kokkos/kokkos#696]
I am running into the following errors when I compile our code with Lambdas on the OLCF/Titan. Titan has Cuda/7.5 and does not support anything above gcc/4.9.3. The example program is below. 

I compile as follows:
% export NVCC_WRAPPER_DEFAULT_COMPILER=CC
% $KOKKOS_DIR/bin/nvcc_wrapper -std=c++11 -expt-extended-lambda -I$KOKKOS_DIR/include main.C $KOKKOS_DIR/lib/libkokkos.a -o ./main

The error I get is:

main.C: In member function 'void MyClass::set(int, int)':
main.C:12:87: error: default arguments are only permitted for function parameters
       Kokkos::parallel_for(NP, KOKKOS_LAMBDA(const size_t& n) {
                                                                                       ^
main.C:17:90: error: default arguments are only permitted for function parameters
       Kokkos::parallel_reduce(NP, KOKKOS_LAMBDA(const size_t& n, int& lsum) { lsum+=lseq(n); }, sum);

The issue seems to be the use of defaults for function arguments. If I removed the default (a=0), this would compile and execute fine. Has anyone run into this issue before? Any known workarounds?

Thanks
Ramanan

===============
```c++
#include <Kokkos_Core.hpp>

class MyClass {
  public:
    typedef Kokkos::View<int *> IndexType;
    IndexType seq;

  public:
    void set(int NP, int a=0) {
      seq=IndexType("seq", NP);
      IndexType lseq=seq;
      Kokkos::parallel_for(NP, KOKKOS_LAMBDA(const size_t& n) {
        lseq(n) = n+a;
      } );

      int sum;
      Kokkos::parallel_reduce(NP, KOKKOS_LAMBDA(const size_t& n, int& lsum) { lsum+=lseq(n); }, sum);
      printf("rsa set %2d\n", sum);
    }
};

int main(int argc, char *argv[]){
  Kokkos::initialize();
  MyClass A;
  A.set(4);
  Kokkos::finalize();
}
```

**Comment by ibaned** [comment]
Much like your previous issue, I have seen this before and have not found a more convenient workaround. If you frequently make use of the defaulting behavior, you could overload the function:
```cpp
void set(int NP, int a) {
  //lambda goes here
}
void set(int NP) {
  set(NP, 0);
}
```
I have much less understanding of why this fails, but I recommend you put something in your title like "Error with lambdas and default arguments in...".

Does this work with CUDA 8.0 ?

**Comment by crtrott** [comment]
This compiles with Cuda 8 with the default argument in it. Nothing much we can do about it for Cuda 7.5 though, it is just a limitation of lambdas which even in Cuda 8 are still experimental after all.
