### ISSUE TITLE
Error in subview

### ISSUE THREAD

**Issue by ramanan** [kokkos/kokkos#2448]
I have a code that uses subview and it fails to build when using a Cuda build of Kokkos/2.9.00. This was working fine with 2.8.00. See simple reproducer below. 

```
#include <Kokkos_Core.hpp>

int main (int argc, char* argv[]) {
  Kokkos::initialize (argc, argv);

  Kokkos::View<double [120][140][96]> f1;
  Kokkos::View<double ***, Kokkos::LayoutStride> f2;

  f2=Kokkos::subview(f1, Kokkos::ALL(), Kokkos::ALL(), Kokkos::ALL());

  Kokkos::finalize ();
}
```

The build error is: /opt/sw/Kokkos/BuildCuda10.1_2.9.00/include/impl/Kokkos_ViewMapping.hpp(1065): error: static assertion failed with "ViewOffset subview construction requires compatible rank"

Can you tell me if something is wrong or has changed recently?

**Comment by dalg24** [comment]
Try this
```C++
Kokkos::View<double [120][140][96]> f1("label");
auto f2 = Kokkos::subview(f1, Kokkos::ALL(), Kokkos::ALL(), Kokkos::ALL());
```

**Comment by dhollman** [comment]
Yes, preserving static extents in subview was a feature request that I addressed with that commit you mentioned.  I'm surprised, though, that static extents aren't compatible with dynamic extents by default.

Also, what breaks in the `auto` version? That makes even less sense.

**Comment by crtrott** [comment]
Interesting that this breaks while there seems to be a test very very similar:

```c++
Kokkos::View<int*[10][5][2], Layout, Space> a;

   KOKKOS_INLINE_FUNCTION
   int operator()() const noexcept
   {
     /* Doesn't actually do anything; just static assertions */

     auto sub_a = Kokkos::subview(a, 0, Kokkos::ALL, Kokkos::ALL, Kokkos::ALL);
```

**Comment by crtrott** [comment]
Yeah as I thought:
This compiles:
```c++
#include <Kokkos_Core.hpp>

int main (int argc, char* argv[]) {
  Kokkos::initialize (argc, argv);

  Kokkos::View<double *[120][140][96]> f1;
  Kokkos::View<double ***, Kokkos::LayoutStride> f2;

  f2=Kokkos::subview(f1, 0,Kokkos::ALL(), Kokkos::ALL(), Kokkos::ALL());

  Kokkos::finalize ();
}
```

**Comment by crtrott** [comment]
The problem appears to be the take a subview of a view with only static extents, and use ALL() on each dimension. It already appears at minimum rank. In the following example only the last one doesn't compile (creation of f8):

```c++
#include <Kokkos_Core.hpp>

int main (int argc, char* argv[]) {
  Kokkos::initialize (argc, argv);

  int n = argc>1?atoi(argv[1]):5;
  Kokkos::View<double *[96]> f1;
  Kokkos::View<double *, Kokkos::LayoutStride> f2;

  f2=Kokkos::subview(f1,0, Kokkos::ALL());

  Kokkos::View<double *[96]> f3;
  Kokkos::View<double **, Kokkos::LayoutStride> f4;

  f4=Kokkos::subview(f3,Kokkos::ALL(), Kokkos::ALL());

  Kokkos::View<double [96]> f5;
  Kokkos::View<double *, Kokkos::LayoutStride> f6;

  f6=Kokkos::subview(f5,Kokkos::pair<int,int>(5,5+n));

  Kokkos::View<double [96]> f7;
  Kokkos::View<double *, Kokkos::LayoutStride> f8;

  f8=Kokkos::subview(f7,Kokkos::ALL());

  Kokkos::finalize ();
}
```

**Comment by dalg24** [comment]
@ramanan this will be fixed in release 3.0.
Thanks for reporting this.

**Comment by dalg24** [comment]
(We just merged the fix into the `develop` branch.)
