### ISSUE TITLE
Nightly Trilinos failure: kokkos_swap update breakage 

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6960]
**Describe the bug**

Nightly Trilinos build (clang/15, serial backend so far) is failing to compile following merge of #6943 
The error pops up mixed in with kokkos-kernels/ode unit test output, but I did a grep search in kokkos-kernels and did not see usage of `kokkos_swap`...

```
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos-kernels/ode/unit_test/backends/Test_Serial_ODE.cpp:19:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos-kernels/test_common/Test_Serial.hpp:20:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Core.hpp:45:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Build/kokkos/KokkosCore_Config_DeclareBackend.hpp:22:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/decl/Kokkos_Declare_SERIAL.hpp:21:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Serial/Kokkos_Serial.hpp:37:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_TaskScheduler.hpp:34:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_MemoryPool.hpp:26:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Parallel.hpp:31:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_View.hpp:42:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_MinMax.hpp:21:
17:42:17 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Pair.hpp:31:
17:42:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Swap.hpp:43:19: error: no matching function for call to 'kokkos_swap'
17:42:17   static decltype(kokkos_swap(std::declval<T&>(), std::declval<T&>()))
17:42:17                   ^~~~~~~~~~~
17:42:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Array.hpp:138:13: note: in instantiation of template class 'Kokkos::Impl::is_swappable<const double>' requested here
17:42:17       Impl::is_swappable<T>::value>
17:42:17             ^
17:42:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos-kernels/ode/impl/KokkosODE_BDF_impl.hpp:313:40: note: in instantiation of template class 'Kokkos::Array<const double, 6>' requested here
17:42:17   const Kokkos::Array<const double, 6> alpha{
17:42:17                                        ^
17:42:17 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug/Trilinos/kokkos/core/src/Kokkos_Swap.hpp:31:1: note: candidate template ignored: requirement 'std::is_move_assignable_v<const double>' was not satisfied [with T = const double]
17:42:17 kokkos_swap(T& a, T& b) noexcept(std::is_nothrow_move_constructible_v<T>&&
```

**Please include the following for a minimal reproducer**

**Reproducer configuration** (blake):
```
git clone -b develop https://github.com/trilinos/Trilinos.git
TRILINOS_DIR=$PWD/Trilinos
git clone -b develop https://github.com/kokkos/kokkos.git
KOKKOS_DIR=$PWD/kokkos
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
KOKKOSKERNELS_DIR=$PWD/kokkos-kernels

cd $TRILINOS_DIR
ln -s ${KOKKOS_DIR}/kokkos kokkos
ln -s ${KOKKOSKERNELS_DIR}/kokkos-kernels kokkos-kernels
cd -

module load cmake llvm openblas/0.3.23

cmake \
  -D CMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
  -D CMAKE_CXX_COMPILER="`which clang++`" \
  -D CMAKE_C_COMPILER="`which clang`" \
  -D CMAKE_Fortran_COMPILER="`which gfortran`" \
  -D CMAKE_CXX_FLAGS="-g -fPIC" \
  -D CMAKE_C_FLAGS="-g -fPIC" \
  -D CMAKE_Fortran_FLAGS="-g -fPIC" \
  -D CMAKE_BUILD_TYPE:STRING=DEBUG \
  -D BUILD_SHARED_LIBS:BOOL=OFF \
  -DTPL_ENABLE_MPI=OFF \
  -DTPL_ENABLE_BLAS:BOOL=ON \
   -DBLAS_LIBRARY_DIRS:FILEPATH=${OPENBLAS_ROOT}/lib \
   -DBLAS_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_LAPACK:BOOL=ON \
   -DLAPACK_INCLUDE_DIRS:FILEPATH=${OPENBLAS_ROOT}/include \
   -DLAPACK_LIBRARY_DIRS:FILEPATH=${OPENBLAS_ROOT}/lib \
   -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
  -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
  -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
  -DTrilinos_ENABLE_COMPLEX=ON \
  -DTrilinos_ENABLE_OpenMP=OFF \
  -DTrilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=ON \
   -D Kokkos_ENABLE_TESTS=ON \
  -D Kokkos_ARCH_SKX=ON \
  -DTrilinos_ENABLE_KokkosKernels=ON \
   -D KokkosKernels_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Sacado=ON \
   -D Sacado_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Stokhos=ON \
   -D Stokhos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Intrepid2=ON \
   -D Intrepid2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Adelus=ON \
   -D Adelus_ENABLE_TESTS:BOOL=ON \
  -DTrilinos_ENABLE_Compadre=ON \
   -D Compadre_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Panzer=ON \
   -D Panzer_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Amesos2=ON \
   -D Amesos2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Zoltan2=ON \
   -D Zoltan2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Teuchos=ON \
   -D Teuchos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Ifpack2=ON \
   -D Ifpack2_ENABLE_TESTS=ON \
\
  -DTPL_ENABLE_Matio=OFF \
\
-DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
-DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

**Comment by ndellingwood** [comment]
Looking at it a bit more, it might be some collision with an included gcc header?

**Comment by ndellingwood** [comment]
Also just failed with intel/2021.3 serial build, this is the output snip:

```
18:16:10 /net/watson/storage/fast/projects/sems/install/rhel8-x86_64/sems-compilers/tpl/gcc/8.3.0/clang/11.0.0/base/7k6onmj/bin/../include/c++/8.3.0/type_traits(2331): error: class "std::enable_if<false, void>" has no member "type"
18:16:10       using enable_if_t = typename enable_if<_Cond, _Tp>::type;
18:16:10                                                           ^
18:16:10           detected during:
18:16:10             instantiation of type "std::enable_if_t<false, void>" at line 138 of "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Array.hpp"
18:16:10             instantiation of class "Kokkos::Array<T, N, Proxy> [with T=const double, N=6UL, Proxy=void]" at line 313 of "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos-kernels/ode/impl/KokkosODE_BDF_impl.hpp"
18:16:10             instantiation of "void KokkosODE::Experimental::BDFSolve(const ode_type &, scalar_type, scalar_type, scalar_type, scalar_type, const vec_type &, const vec_type &, mat_type &, mat_type &) [with ode_type=Test::StiffChemistry, mat_type=const Kokkos::View<double **, Kokkos::Serial>, vec_type=Kokkos::View<double *, Kokkos::Serial>, scalar_type=double]" at line 203 of
18:16:10                       "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos-kernels/ode/unit_test/Test_ODE_BDF.hpp"
18:16:10             instantiation of "void Test::BDF_Solve_wrapper<ode_type, mat_type, vec_type, scalar_type>::operator()(int) const [with ode_type=Test::StiffChemistry, mat_type=Kokkos::View<double **, Kokkos::Serial>, vec_type=Kokkos::View<double *, Kokkos::Serial>, scalar_type=double]" at line 37 of "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Serial/Kokkos_Serial_Parallel_Range.hpp"
18:16:10             instantiation of "std::enable_if_t<std::is_void<TagType>::value, void> Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Serial>::exec<TagType>() const [with FunctorType=Test::BDF_Solve_wrapper<Test::StiffChemistry, Kokkos::View<double **, Kokkos::Serial>, Kokkos::View<double *, Kokkos::Serial>, double>, Traits=<Kokkos::Serial::execution_space>, TagType=Kokkos::Impl::WorkTagTrait::base_traits::work_tag]" at line 52 of
18:16:10                       "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Serial/Kokkos_Serial_Parallel_Range.hpp"
18:16:10             instantiation of "void Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Serial>::execute() const [with FunctorType=Test::BDF_Solve_wrapper<Test::StiffChemistry, Kokkos::View<double **, Kokkos::Serial>, Kokkos::View<double *, Kokkos::Serial>, double>, Traits=<Kokkos::Serial::execution_space>]" at line 144 of "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Parallel.hpp"
18:16:10             instantiation of "void Kokkos::parallel_for(const std::__cxx11::string &, const ExecPolicy &, const FunctorType &) [with ExecPolicy=Kokkos::RangePolicy<Kokkos::Serial::execution_space>, FunctorType=Test::BDF_Solve_wrapper<Test::StiffChemistry, Kokkos::View<double **, Kokkos::Serial>, Kokkos::View<double *, Kokkos::Serial>, double>, Enable=void]" at line 153 of
18:16:10                       "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Parallel.hpp"
18:16:10             instantiation of "void Kokkos::parallel_for(const ExecPolicy &, const FunctorType &, std::enable_if_t<Kokkos::is_execution_policy<ExecPolicy>::value, void> *) [with ExecPolicy=Kokkos::RangePolicy<Kokkos::Serial::execution_space>, FunctorType=Test::BDF_Solve_wrapper<Test::StiffChemistry, Kokkos::View<double **, Kokkos::Serial>, Kokkos::View<double *, Kokkos::Serial>, double>]" at line 799 of
18:16:10                       "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos-kernels/ode/unit_test/Test_ODE_BDF.hpp"
18:16:10             instantiation of "void Test::test_BDF_adaptive_stiff<Device,scalar_type>() [with Device=Kokkos::Serial, scalar_type=double]" at line 829 of "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos-kernels/ode/unit_test/Test_ODE_BDF.hpp"
18:16:10 
18:16:10 /home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Swap.hpp(54): error: no instance of overloaded function "Kokkos::kokkos_swap" matches the argument list
18:16:10             argument types are: (const double, const double)
18:16:10       noexcept(kokkos_swap(std::declval<T&>(), std::declval<T&>()));
```

**Comment by dalg24** [comment]
OK.  These are all case of swaping Kokkos arrays of elements with const-qualified types.

**Comment by ndellingwood** [comment]
@dalg24 thanks for addressing so quickly! So it looks like this showed up indirectly in kokkos-kernels through use of `Kokkos::Array` (I was confused to see it since kokkos-kernels does not directly use kokkos_swap)

```
kokkos-kernels ndellin$ git grep Kokkos_Array.hpp
ode/impl/KokkosODE_RungeKuttaTables_impl.hpp:#include <Kokkos_Array.hpp>
```

**Comment by ndellingwood** [comment]
Reopening, looks like a case of whack-a-mole where kokkos standalone is now failing in the intel/19 job (so far), and the Trilinos nightly build with intel/2021.3 is still failing following merge of #6962

**Comment by ndellingwood** [comment]
Following merge of #6962 , looks like occurrences with local `kokkos/core/unit_test/TestArray.cpp` test

### Standalone kokkos build failure with intel/2021.3:
```
20:40:36 /home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/src/Kokkos_Swap.hpp(61): error: no instance of overloaded function "Kokkos::kokkos_swap" matches the argument list
20:40:36             argument types are: (const int, const int)
20:40:36       noexcept(kokkos_swap(std::declval<T&>(), std::declval<T&>()));
20:40:36                ^
20:40:36 /home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/src/Kokkos_Array.hpp(200): note: this candidate was rejected because function is not visible
20:40:36     friend KOKKOS_INLINE_FUNCTION constexpr void kokkos_swap(
20:40:36                                                  ^
20:40:36 /home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/src/Kokkos_Array.hpp(140): note: this candidate was rejected because function is not visible
20:40:36     kokkos_swap(Array<T, N>& a,
20:40:36     ^
20:40:36 /home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/src/Kokkos_Array.hpp(140): note: this candidate was rejected because function is not visible
20:40:36     kokkos_swap(Array<T, N>& a,
20:40:36     ^
20:40:36 /home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/src/Kokkos_Array.hpp(140): note: this candidate was rejected because function is not visible
20:40:36     kokkos_swap(Array<T, N>& a,
20:40:36     ^
20:40:36 /home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/src/Kokkos_Array.hpp(140): note: this candidate was rejected because function is not visible
20:40:36     kokkos_swap(Array<T, N>& a,
20:40:36     ^
20:40:36 /home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/src/Kokkos_Swap.hpp(68): note: this candidate was rejected because function is not visible
20:40:36   kokkos_swap(T (&a)[N], T (&b)[N]) noexcept(Impl::is_nothrow_swappable_v<T>) {
20:40:36   ^
20:40:36 /home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/src/Kokkos_Swap.hpp(31): note: this candidate was rejected because at least one template argument could not be deduced
20:40:36   kokkos_swap(T& a, T& b) noexcept(std::is_nothrow_move_constructible_v<T>&&
20:40:36   ^
20:40:36           detected during:
20:40:36             instantiation of "const bool Kokkos::Impl::is_nothrow_swappable_v [with T=const int]" at line 141 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/src/Kokkos_Array.hpp"
20:40:36             instantiation of class "Kokkos::Array<T, N> [with T=const int, N=1UL]" at line 124 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/unit_test/TestArray.cpp"
```

**Reproducer**:
```bash
module load sems-cmake sems-intel/2021.3

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --no-examples   --with-options=enable_large_mem_tests
```

### Trilinos integration build failure with intel/2021.3:
```
18:13:41 /home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Swap.hpp(61): error: no instance of overloaded function "Kokkos::kokkos_swap" matches the argument list
18:13:41             argument types are: (const int, const int)
18:13:41       noexcept(kokkos_swap(std::declval<T&>(), std::declval<T&>()));
18:13:41                ^
18:13:41 /home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Array.hpp(200): note: this candidate was rejected because function is not visible
18:13:41     friend KOKKOS_INLINE_FUNCTION constexpr void kokkos_swap(
18:13:41                                                  ^
18:13:41 /home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Array.hpp(140): note: this candidate was rejected because function is not visible
18:13:41     kokkos_swap(Array<T, N>& a,
18:13:41     ^
18:13:41 /home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Array.hpp(140): note: this candidate was rejected because function is not visible
18:13:41     kokkos_swap(Array<T, N>& a,
18:13:41     ^
18:13:41 /home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Array.hpp(140): note: this candidate was rejected because function is not visible
18:13:41     kokkos_swap(Array<T, N>& a,
18:13:41     ^
18:13:41 /home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Array.hpp(140): note: this candidate was rejected because function is not visible
18:13:41     kokkos_swap(Array<T, N>& a,
18:13:41     ^
18:13:41 /home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Swap.hpp(68): note: this candidate was rejected because function is not visible
18:13:41   kokkos_swap(T (&a)[N], T (&b)[N]) noexcept(Impl::is_nothrow_swappable_v<T>) {
18:13:41   ^
18:13:41 /home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Swap.hpp(31): note: this candidate was rejected because at least one template argument could not be deduced
18:13:41   kokkos_swap(T& a, T& b) noexcept(std::is_nothrow_move_constructible_v<T>&&
18:13:41   ^
18:13:41           detected during:
18:13:41             instantiation of "const bool Kokkos::Impl::is_nothrow_swappable_v [with T=const int]" at line 141 of "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/src/Kokkos_Array.hpp"
18:13:41             instantiation of class "Kokkos::Array<T, N, Proxy> [with T=const int, N=1UL, Proxy=void]" at line 124 of "/home/jenkins/jenkins-new/workspace/KokkosEco_Trilinos_KokkosDev2_SemsIntel2021_3_Serial_MKL/Trilinos/kokkos/core/unit_test/TestArray.cpp"
```

**Comment by masterleinad** [comment]
Looks like we need the same workaround as for `nvcc`, see https://godbolt.org/z/h7eKvxovY.

**Comment by ndellingwood** [comment]
@masterleinad there is another related case from last night's nightlies in Trilinos with cuda/11.2.2 builds:

```
20:37:32 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-no-uvm/Trilinos/kokkos/core/src/Kokkos_Swap.hpp(56): error: no instance of overloaded function "Kokkos::kokkos_swap" matches the argument list
20:37:32             argument types are: (double [3][3], double [3][3])
20:37:32           detected during:
20:37:32             instantiation of "const __nv_bool Kokkos::Impl::is_nothrow_swappable_v [with T=double [3][3]]" 
20:37:32 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-no-uvm/Trilinos/kokkos/core/src/Kokkos_Array.hpp(141): here
20:37:32             instantiation of class "Kokkos::Array<T, N, Proxy> [with T=double [3][3], N=8UL, Proxy=void]" 
20:37:32 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-no-uvm/Trilinos/packages/percept/src/percept/mesh/mod/smoother/sgrid_metric_helpers.hpp(74): here
20:37:32 
20:37:33 [ 62%] Building CXX object packages/panzer/dof-mgr/src/CMakeFiles/panzer-dof-mgr.dir/Panzer_NodalFieldPattern.cpp.o
20:37:34 [ 62%] Building CXX object packages/percept/CMakeFiles/percept.dir/src/adapt/UniformRefiner.cpp.o
20:37:36 1 error detected in the compilation of "/home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-no-uvm/Trilinos/packages/percept/src/adapt/Refiner.cpp".
```
