### PR TITLE
Fixed an incorrect struct initialization

### PR DESCRIPTION
**Pull request by ldh4**
Building Kokkos for a HIP build with `-DKokkos_ENABLE_HIP_RELOCATABLE_DEVICE_CODE=ON` produced an error:

```
[  4%] Building CXX object core/src/CMakeFiles/kokkoscore.dir/desul/src/Lock_Array_HIP.cpp.o
/ascldap/users/donlee/kokkos/kokkos/core/src/HIP/Kokkos_HIP_Locks.cpp:60:67: error: cannot initialize a member subobject of type 'std::int32_t' (aka 'int') with an rvalue of type 'nullptr_t'
                                                                  nullptr, 0};
                                                                  ^~~~~~~
1 error generated when compiling for gfx908.
```

It turned out that there was a HIPLockArrays struct variable that was being initialized incorrectly.

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]

File: core/src/HIP/Kokkos_HIP_Locks.cpp [hunk 1]
```diff
@@ -56,8 +56,7 @@ namespace Kokkos {
 
 #ifdef KOKKOS_ENABLE_HIP_RELOCATABLE_DEVICE_CODE
 namespace Impl {
-__device__ __constant__ HIPLockArrays g_device_hip_lock_arrays = {nullptr,
-                                                                  nullptr, 0};
+__device__ __constant__ HIPLockArrays g_device_hip_lock_arrays = {nullptr, 0};
```
Comment (dalg24) [inline core/src/HIP/Kokkos_HIP_Locks.cpp:59]: For reference
https://github.com/kokkos/kokkos/blob/cb636c3344a06918c4aeaa7c53aec251f8c35c04/core/src/HIP/Kokkos_HIP_Locks.hpp#L61-L64

**Comment by dalg24** [comment]
Bug was introduced in #4371

**Comment by dalg24** [comment]
This needs to be cherry picked in the patch release

**Review by masterleinad — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Comment by dalg24** [comment]
NVHPC failure is the issue reported in #5025 
```
49: [ RUN      ] openmp.scatterview_devicetype
49: /var/jenkins/workspace/Kokkos/containers/unit_tests/TestScatterView.hpp:363: Failure
49: The difference between val0 and 4.0 is 4, which exceeds 1e-14 * 4.0, where
49: val0 evaluates to 8,
49: 4.0 evaluates to 4, and
49: 1e-14 * 4.0 evaluates to 4e-14.
49: Data differs at index 9
```
