### ISSUE TITLE
HIP backend in Kokkos release 3.1.01 does not build with ROCm-3.5

### ISSUE THREAD

**Issue by tomdeakin** [kokkos/kokkos#3280]
I'm trying out the Kokkos HIP backend to target AMD GPUs. On a system with HIP v3.5 I can't get Kokkos to build, error below. I've had success with HIP v2.8.

I've setting `ARCH=Vega906 DEVICE=HIP CXX=hipcc` when building Kokkos.

```
$ hipcc --version
HIP version: 3.5.20214-a2917cdc
clang version 11.0.0 (/data/jenkins_workspace/centos_pipeline_job_3.5/rocm-rel-3.5/rocm-3.5-30-20200528/7.5/external/llvm-project/clang 6c08b900599eee52e12bce1e76b20dc413ce30e7)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
```

```bash
Using KOKKOS_PATH=/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01
make: Entering directory `/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/BabelStream'
hipcc -I./ -I/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src -I/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarki$
g/2020/babelstream/mi50-cosma/kokkos-3.1.01/containers/src -I/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/algorithms/src -I/cosma/home/d$
006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/eti --std=c++11 --amdgpu-target=gfx906 -fno-gpu-rdc --gcc-toolchain=/usr -I./ -I/cosma/home/do00$
/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src -I/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma$
kokkos-3.1.01/containers/src -I/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/algorithms/src -I/cosma/home/do006/dc-deak1/codes/performanc$
-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/eti -O3   -DKOKKOS -c main.cpp
In file included from main.cpp:33:
In file included from ./KokkosStream.hpp:12:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/Kokkos_Core.hpp:82:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/Kokkos_HIP.hpp:60:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/HIP/Kokkos_HIP_Parallel_Range.hpp:52:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/HIP/Kokkos_HIP_BlockSize_Deduction.hpp:53:
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/HIP/Kokkos_HIP_KernelLaunch.hpp:79:14: error: __constant__ variables must be globa$
  __device__ __constant__ unsigned long kokkos_impl_hip_constant_memory_buffer
             ^
/opt/rocm-3.5.0/hip/include/hip/hcc_detail/host_defines.h:71:37: note: expanded from macro '__constant__'
#define __constant__ __attribute__((constant))
                                    ^
In file included from main.cpp:33:
In file included from ./KokkosStream.hpp:12:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/Kokkos_Core.hpp:82:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/Kokkos_HIP.hpp:60:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/HIP/Kokkos_HIP_Parallel_Range.hpp:54:
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/HIP/Kokkos_HIP_ReduceScan.hpp:146:24: error: no matching function for call to 'atom
ic_fetch_add'
      num_teams_done = Kokkos::atomic_fetch_add(global_flags, 1) + 1;
                       ^~~~~~~~~~~~~~~~~~~~~~~~
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:264:10: note: candidate template ignored: requirem
ent 'sizeof(unsigned int) != sizeof(int) && sizeof(unsigned int) == sizeof(long)' was not satisfied [with T = unsigned int]
inline T atomic_fetch_add(volatile T* const dest,
         ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:322:10: note: candidate template ignored: requirem
ent '(sizeof(unsigned int) != 4) && (sizeof(unsigned int) != 8)' was not satisfied [with T = unsigned int]
inline T atomic_fetch_add(
         ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:202:12: note: candidate function not viable: call 
to __host__ function from __device__ function
inline int atomic_fetch_add(volatile int* const dest, const int val) {
           ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:210:17: note: candidate function not viable: call 
to __host__ function from __device__ function
inline long int atomic_fetch_add(volatile long int* const dest,
                ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:220:21: note: candidate function not viable: call 
to __host__ function from __device__ function
inline unsigned int atomic_fetch_add(volatile unsigned int* const dest,
                    ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:228:26: note: candidate function not viable: call 
to __host__ function from __device__ function
inline unsigned long int atomic_fetch_add(
                         ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:239:10: note: candidate function not viable: call 
to __host__ function from __device__ function
inline T atomic_fetch_add(
         ^
2 errors generated when compiling for gfx906.
make: *** [main.o] Error 1
make: Leaving directory `/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/BabelStream'

Build failed.

**Comment by dalg24** [comment]
What version of Kokkos are you using?  Also did you try using CMake to configure?

**Comment by tomdeakin** [comment]
> What version of Kokkos are you using?

kokkos-3.1.01

> Also did you try using CMake to configure?

I tried, but the error looks the same.

```bash
$ cmake .. -DKokkos_ENABLE_HIP=On -DKokkos_ARCH_VEGA906=On -DCMAKE_CXX_COMPILER=hipcc

$ make
Scanning dependencies of target kokkoscore
[  4%] Building CXX object core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o
[  8%] Building CXX object core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Core.cpp:45:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/Kokkos_Core.hpp:82:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/Kokkos_HIP.hpp:60:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/HIP/Kokkos_HIP_Parallel_Range.hpp:52:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/HIP/Kokkos_HIP_BlockSize_Deduction.hpp:53:
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/HIP/Kokkos_HIP_KernelLaunch.hpp:79:14: error: __constant__ variables must be global
  __device__ __constant__ unsigned long kokkos_impl_hip_constant_memory_buffer
             ^
/opt/rocm-3.5.0/hip/include/hip/hcc_detail/host_defines.h:71:37: note: expanded from macro '__constant__'
#define __constant__ __attribute__((constant))
                                    ^
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Core.cpp:45:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/Kokkos_Core.hpp:82:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/Kokkos_HIP.hpp:60:
In file included from /cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/HIP/Kokkos_HIP_Parallel_Range.hpp:54:
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/HIP/Kokkos_HIP_ReduceScan.hpp:146:24: error: no matching function for call to 'atom
ic_fetch_add'
      num_teams_done = Kokkos::atomic_fetch_add(global_flags, 1) + 1;
                       ^~~~~~~~~~~~~~~~~~~~~~~~
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:264:10: note: candidate template ignored: requirem
ent 'sizeof(unsigned int) != sizeof(int) && sizeof(unsigned int) == sizeof(long)' was not satisfied [with T = unsigned int]
inline T atomic_fetch_add(volatile T* const dest,
         ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:322:10: note: candidate template ignored: requirem
ent '(sizeof(unsigned int) != 4) && (sizeof(unsigned int) != 8)' was not satisfied [with T = unsigned int]
inline T atomic_fetch_add(
         ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:202:12: note: candidate function not viable: call 
to __host__ function from __device__ function
inline int atomic_fetch_add(volatile int* const dest, const int val) {
           ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:210:17: note: candidate function not viable: call 
to __host__ function from __device__ function
inline long int atomic_fetch_add(volatile long int* const dest,
                ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:220:21: note: candidate function not viable: call 
to __host__ function from __device__ function
inline unsigned int atomic_fetch_add(volatile unsigned int* const dest,
                    ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:228:26: note: candidate function not viable: call 
to __host__ function from __device__ function
inline unsigned long int atomic_fetch_add(
                         ^
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/kokkos-3.1.01/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:239:10: note: candidate function not viable: call 
to __host__ function from __device__ function
inline T atomic_fetch_add(
         ^
2 errors generated when compiling for gfx906.
make[2]: *** [core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o] Error 1
make[1]: *** [core/src/CMakeFiles/kokkoscore.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Rombur** [comment]
@tomdeakin This should have been fixed on develop. Can you try it?

**Comment by dalg24** [comment]
I was able to reproduce.  Kokkos release-3.1.01 does not build with rocm-3.5 (it does with rocm-3.3)
As Bruno said you need to use the develop branch.  The next Kokkos release should be out soon.

**Comment by tomdeakin** [comment]
I can build Kokkos, but I'm not struggling to link against the built library due to
```
/cosma/home/do006/dc-deak1/codes/performance-portability/benchmarking/2020/babelstream/mi50-cosma/BabelStream/libkokkos.a(Kokkos_Profiling.o): In function `Kokkos::Profiling::initialize()':
Kokkos_Profiling.cpp:(.text+0x1180): multiple definition of `Kokkos::Profiling::initialize()'
etc
```

**Comment by masterleinad** [comment]
Hmmm... we haven't seen this problem in other applications. Would you have a minimal example or a branch for us to look at?

**Comment by tomdeakin** [comment]
Update: error was caused by some rogue `libkokkos.a`s somewhere in a directory. I blew away everything and started again and it went away. Thanks everyone for your help!
