### ISSUE TITLE
RangePolicy's CTAD fails with NVCC 11.1

### ISSUE THREAD

**Issue by aprokop** [kokkos/kokkos#7329]
**Describe the bug**

CTAD for `RangePolicy`, introduced in #6850, fails with CUDA 11.1 version.

Reproducer:
```cpp
#include <Kokkos_Core.hpp>

template <typename ExecutionSpace, typename ViewType>
void iota(ExecutionSpace const &space, ViewType const &v,
          typename ViewType::value_type value = 0)
{
  Kokkos::parallel_for("iota", Kokkos::RangePolicy(space, 0, v.extent(0)),
      KOKKOS_LAMBDA(int i) { v(i) = value + i; });
}

int main(int argc, char *argv[])
{
  Kokkos::ScopeGuard guard(argc, argv);
  Kokkos::View<int*> v("view", 10);
  iota(Kokkos::DefaultExecutionSpace{}, v);
  return EXIT_SUCCESS;
}
```
This code fails with Kokkos 4.3 and Kokkos 4.4 on CUDA 11.1:
```
/home/users/aprokop/code/arborx/benchmarks/develop/develop.cpp: In instantiation of 'void iota(const ExecutionSpace&, const ViewType&, typename ViewType::value_type) [with ExecutionSpace = Kokkos::Cuda; ViewType = Kokkos::View<int*>; typename ViewType::value_type = int]':
/home/users/aprokop/code/arborx/benchmarks/develop/develop.cpp:29:40:   required from here
/home/users/aprokop/code/arborx/benchmarks/develop/develop.cpp:19:61: error: 'RangePolicy' was not declared in this scope; did you mean 'Kokkos::RangePolicy'?
   19 |   Kokkos::parallel_for(
      |                                                             ^
      |                                                  Kokkos::RangePolicy
/home/users/aprokop/local/opt/saturn/kokkos-4.3.1-cuda11.1/include/Kokkos_ExecPolicy.hpp:68:7: note: 'Kokkos::RangePolicy' declared here
   68 | class RangePolicy : public Impl::PolicyTraits<Properties...> {
```
It passes with added `<ExecutionSpace>` template to `RangePolicy`.

**Comment by aprokop** [comment]
@dalg24 That does not work.

The things that worked are
```
template <typename ExecutionSpace, typename ViewType>
void iota(ExecutionSpace const &, ViewType const &v,
          typename ViewType::value_type value = 0)
{
  Kokkos::DefaultExecutionSpace space;
  Kokkos::parallel_for("iota", Kokkos::RangePolicy(space, (int32_t)0, (int32_t)v.extent(0)),
      KOKKOS_LAMBDA(int i) { v(i) = value + i; });
}
```
I had to both define `space` inside the function, and do static converts for arguments to `int32_t` (`int64_t` also works).

**Comment by cwpearson** [comment]
As of Kokkos 5, we require nvcc 12.2
