### ISSUE TITLE
Nightly build compilation errors with gcc/8.2.0 with SKX arch: Kokkos_SIMD_AVX512.hpp

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6268]
**Describe the bug**
Nightly gcc/8.2.0 builds on SKX emit compilation errors:
```
01:26:07 In file included from /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD.hpp:29,
01:26:07                  from /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/unit_tests/TestSIMD.cpp:19:
01:26:07 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp: In function ‘Kokkos::Experimental::simd<double, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> > Kokkos::Experimental::abs(const Kokkos::Experimental::simd<double, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> >&)’:
01:26:07 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp:782:69: error: cannot convert ‘const __m512d’ {aka ‘const __vector(8) double’} to ‘__m512’ {aka ‘__vector(16) float’}
01:26:07    return simd<double, simd_abi::avx512_fixed_size<8>>(_mm512_abs_pd(rhs));
01:26:07                                                                      ^~~
01:26:07 In file included from /projects/x86-64/gcc/8.2.0/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/immintrin.h:45,
01:26:07                  from /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp:26,
01:26:07                  from /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD.hpp:29,
01:26:07                  from /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/unit_tests/TestSIMD.cpp:19:
01:26:07 /projects/x86-64/gcc/8.2.0/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/avx512fintrin.h:7730:23: note:   initializing argument 1 of ‘__m512d _mm512_abs_pd(__m512)’
01:26:07  _mm512_abs_pd (__m512 __A)
01:26:07                 ~~~~~~~^~~
```

The compilation error does not occur with gcc/8.3.0, gcc/9.2.0, gcc/10.2.0 on SKX on the same system, so I'm adding the Compiler Issue label

**This is the list of changes since the previous passing build**:
Fix SIMD abs unit test accidentally using complex overload ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/300/changes#778225ffb1647ccb9483e4935694fcca110984b8) / [githubweb](https://github.com/kokkos/kokkos/commit/778225ffb1647ccb9483e4935694fcca110984b8))
    Fix SIMD tests on NEON ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/300/changes#8296fb127b28bfeba972e400d21b607db58625a0) / [githubweb](https://github.com/kokkos/kokkos/commit/8296fb127b28bfeba972e400d21b607db58625a0))

Ensure that complex is only instantiated for cv-unqualified floating-point type ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/299/changes#113055e3c0b46d9d83f461f8aaa9a6819e28827e) / [githubweb](https://github.com/kokkos/kokkos/commit/113055e3c0b46d9d83f461f8aaa9a6819e28827e))
    SYCL: Use in-order queues in InterOp tests (#6246) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/299/changes#6a8488d78bcec6448bdf42b0258d076de155bd4c) / [githubweb](https://github.com/kokkos/kokkos/commit/6a8488d78bcec6448bdf42b0258d076de155bd4c))
    std_algos: fix wrong corner case for `is_partitioned` (#6257) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/299/changes#07a0f0c2c8ff3ab1a8134e44aeb75c3522854197) / [githubweb](https://github.com/kokkos/kokkos/commit/07a0f0c2c8ff3ab1a8134e44aeb75c3522854197))
    SIMD: Add abs() for all int types (#6069) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/299/changes#35c1e3c37402ff8505410456421145e0cd50812c) / [githubweb](https://github.com/kokkos/kokkos/commit/35c1e3c37402ff8505410456421145e0cd50812c))

**Please also include the following items to support reproducing the bug**
**Reproducer** (Blake testbed):
```bash
module load cmake/3.19.3 gcc/8.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial --arch=SKX --compiler=g++ --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --no-examples   --with-options=enable_large_mem_tests --debug

# CMake line:
cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized"  -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_SKX=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=DEBUG -DKokkos_ENABLE_DEBUG=ON -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF $KOKKOS_PATH
```

**Comment by masterleinad** [comment]
Yes, this looks like a bug in `avx512fintrin.h`. According to https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm512_abs_pd&ig_expand=64,72,302,64,  `_mm512_abs_pd` should take a `__mm512d`, not a `__m512`.

**Comment by masterleinad** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87467

**Comment by masterleinad** [comment]
Can you try if
```
(__m512d) _mm512_and_epi64 ((__m512i) rhs ,_mm512_set1_epi64 (0x7fffffffffffffffLL));
```
works as a workaround before gcc-9?

**Comment by ndellingwood** [comment]
@masterleinad I'm not sure I understand how to apply that change, can you give a bit more detail/diff?
I tried replacing the `rhs` arg to `_mm512_abs_pd` with the snip you provided but that still resulted in compilation error, though I may have made a mistake in my attempt (I'm assuming this attempts to convert the rhs to input the broken avx intrinsic will accept)

Here's what I tried:
```diff
diff --git a/simd/src/Kokkos_SIMD_AVX512.hpp b/simd/src/Kokkos_SIMD_AVX512.hpp
index a02eed5..eb8dfc2 100644
--- a/simd/src/Kokkos_SIMD_AVX512.hpp
+++ b/simd/src/Kokkos_SIMD_AVX512.hpp
@@ -779,7 +779,8 @@ KOKKOS_IMPL_HOST_FORCEINLINE_FUNCTION
 simd<double, simd_abi::avx512_fixed_size<8>> abs(
     simd<double, simd_abi::avx512_fixed_size<8>> const& a) {
   __m512d const rhs = static_cast<__m512d>(a);
-  return simd<double, simd_abi::avx512_fixed_size<8>>(_mm512_abs_pd(rhs));
+  //return simd<double, simd_abi::avx512_fixed_size<8>>(_mm512_abs_pd(rhs));
+  return simd<double, simd_abi::avx512_fixed_size<8>>(_mm512_abs_pd((__m512d) _mm512_and_epi64 ((__m512i) rhs ,_mm512_set1_epi64 (0x7fffffffffffffffLL)) ));
 }
 
 KOKKOS_IMPL_HOST_FORCEINLINE_FUNCTION
```

**Comment by masterleinad** [comment]
@ndellingwood The snippet I provided is the implementation of `_mm512_abs_pd` for a GCC version I was trying and I suspect that it would also for earlier versions. That is replace
```
return simd<double, simd_abi::avx512_fixed_size<8>>(_mm512_abs_pd(rhs));
```
by
```
return simd<double, simd_abi::avx512_fixed_size<8>>((__m512d) _mm512_and_epi64 ((__m512i) rhs, _mm512_set1_epi64 (0x7fffffffffffffffLL)));
```

**Comment by ndellingwood** [comment]
@masterleinad thanks for the clarification, that worked with gcc/8.2.0 to get compilation to 100%

**Comment by ndellingwood** [comment]
@masterleinad shall I submit a PR with this diff (may need clang-format)

```diff
diff --git a/simd/src/Kokkos_SIMD_AVX512.hpp b/simd/src/Kokkos_SIMD_AVX512.hpp
index a02eed5..9eb0f4e 100644
--- a/simd/src/Kokkos_SIMD_AVX512.hpp
+++ b/simd/src/Kokkos_SIMD_AVX512.hpp
@@ -779,7 +779,11 @@ KOKKOS_IMPL_HOST_FORCEINLINE_FUNCTION
 simd<double, simd_abi::avx512_fixed_size<8>> abs(
     simd<double, simd_abi::avx512_fixed_size<8>> const& a) {
   __m512d const rhs = static_cast<__m512d>(a);
+#if defined(KOKKOS_COMPILER_GNU) && (KOKKOS_COMPILER_GNU < 830)
+  return simd<double, simd_abi::avx512_fixed_size<8>>( (__m512d) _mm512_and_epi64 ((__m512i) rhs ,_mm512_set1_epi64 (0x7fffffffffffffffLL)) );
+#else
   return simd<double, simd_abi::avx512_fixed_size<8>>(_mm512_abs_pd(rhs));
+#endif
 }
 
 KOKKOS_IMPL_HOST_FORCEINLINE_FUNCTION
```

**Comment by ndellingwood** [comment]
@masterleinad I opened #6269 with your suggested change as a potential fix for the issue

**Comment by masterleinad** [comment]
Fixed in #6269.
