### ISSUE TITLE
CMake: Fix having kokkos as a subdirectory in a pure cmake project

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#629]
Ok I worked a bit on this. This is a simple CMakeLists.txt for a project which has snapshoted kokkos in the top level project directory.

```
cmake_minimum_required (VERSION 2.8.12)
project (Example)

#include Kokkos:
add_subdirectory (kokkos)
include_directories(kokkos/core/src)
include_directories(kokkos/algorithms/src)
include_directories(kokkos/containers/src)
include_directories(${CMAKE_BINARY_DIR}/kokkos/core/src)
include_directories(${CMAKE_BINARY_DIR}/kokkos/algorithms/src)
include_directories(${CMAKE_BINARY_DIR}/kokkos/containers/src)

#What variables are set??
#get_cmake_property(_variableNames VARIABLES)
#foreach (_variableName ${_variableNames})
#    message(STATUS "${_variableName}=${${_variableName}}")
#endforeach()

add_executable (example simple_reduce_lambda.cpp)
target_link_libraries (example kokkoscore)

set(CMAKE_CXX_FLAGS "-std=c++11 -O3")
```

The directory contains:
CMakeLists.txt kokkos simple_reduce_lambda.cpp

Creating a build dir and then doing cmake ../ from it configures the build, make builds. 

But: can we do better than doing the include_directories buisness: i.e. define variables inside kokkos which can be consumed on the outside. Also need to figure out all the architecture settings which are currently not cmake variables.

**Comment by gmackey** [comment]
I've got logic to handle the architecture settings.

The Kokkos CMakeLists.txt will define variables KOKKOS_C_FLAGS, KOKKOS_CPP_FLAGS, KOKKOS_CXXFLAGS, and KOKKOS_LIBS that will be available in the caller's scope.  Should these variables just be set in the PARENT_SCOPE or should they be global (CACHE INTERNAL)?

I'm creating a pure cmake version that has behavior more like the makefile version.  A single library libkokkos.a will be created that will include core, containers, and algorithm.  The cmake and Tribits versions will share common code as much as possible.  The way I'm doing this should not change anything about user interface for a Tribits user (aka Trilinos user) but the new functionality I'm added should be easily added to that version when the Trilinos team approves them.

**Comment by hcedwar** [comment]
Open concern one library per subdirectory (core, container, algorithm)

**Comment by gmackey** [comment]
After staring at this some more, the most CMaky way of doing things is to apply compile flags, linker flags, libs, etc. as requirements to the libkokkos target for building the kokkos library.  What this means is that all these things will be attached to the library.  When a user builds against that library, they will inherit all of those things automatically without doing anything.

Is there any heartburn with this?  This is for the non-Tribits version only, and Trilinos will not be affected.  This is also only for the situation where a user builds Kokkos as part of building their application.  To me, this is really what is intended, and as a user I want as little difficulty in using a library as possible.  So, enabling KOKKOS_HAVE_PTHREAD in the CMake GUI for a user's application will automatically pass the correct flags, libraries, etc. to the user's compile (only of targets that link against the Kokkos library) without them doing anything.

This takes some control away from the user compared to us returning things like KOKKOS_CXXFLAGS that the user has to add themselves, but it will only affect targets that link against the kokkos library.  Is there ever a case where the user would want to use different flags?  My understanding is that it is required they use the same flags.

**Comment by gmackey** [comment]
Would this address the concern of building separate libraries?

What if we add the CMake option KOKKOS_BUILD_SEPARATE_LIBS that is by default set to off.  In this case, a single kokkos library is built that includes all of core, containers, and algorithms.  If the option is turned on, separate libraries are built.  This to me seems like a clean way to allow both options without requiring all options to be built all the time.

If we really wanted customization, we could have four separate options: KOKKOS_BUILD_LIB, KOKKOS_BUILD_CORE_LIB, KOKKOS_BUILD_CONTAINERS_LIB, and KOKKOS_BUILD_ALGORITHMS_LIB.

Also, right now it doesn't make sense to build an algorithms library.  There are only header files in algorithms, so there would be nothing in the library.  There's even a warning about an empty library during a build.  The algorithms library could be added in when / if source files are added to algorithms.

**Comment by mhoemmen** [comment]
@gmackey wrote:
> Also, right now it doesn't make sense to build an algorithms library. There are only header files in algorithms, so there would be nothing in the library. There's even a warning about an empty library during a build.

Trilinos' old trick for getting rid of the warning is to include a .cpp file with a trivial function in each subpackage.

**Comment by gmackey** [comment]
Thanks for the suggestion , Mark.  I found a CMaky way to do this.  I made the algorithms library an interface library.  This means a .a file won't be built, but I can use target_include_directories() to add dependencies to the interface library.  A target is created that users can call and they inherit those dependencies.

**Comment by mhoemmen** [comment]
@gmackey Awesome!

**Comment by gmackey** [comment]
Is requiring CMake 3.1 or later for the non-Tribits version going to be an issue?  This won't impact the Tribits version which is what Trilinos uses.

**Comment by dholladay00** [comment]
3.1 works for my project

**Comment by gmackey** [comment]
Unless I get any objections, 3.1 it is.  This is when CMake started supporting things to easily do compilation with specific C++ standards or features.

**Comment by gmackey** [comment]
@dholladay00 Since the only user I know about is okay with 3.1. :)

**Comment by hcedwar** [comment]
Add an example usage within the 'example' subdirectory.

**Comment by gmackey** [comment]
@dholladay00 I have a decently tested version of the new CMake build process for building Kokkos as part of another CMake project checked into my fork of Kokkos at https://github.com/gmackey/kokkos.git.  It's in the branch 'cmake'.  There's an example of how to build in example/cmake_build/.  When you get a chance, would you mind testing it out?

**Comment by dholladay00** [comment]
I'll try to get to this soon. That example is nice b/c I don't have to pull it in as an external project!

For Kokkos specific flags/options (think KOKKOS_DEBUG, KOKKOS_ARCH, backend type, etc.), if I set them in my CMakelists, will that be respected?

**Comment by gmackey** [comment]
You are testing out my limited but growing CMake knowledge.  I just tested things out.  The options are CACHE variables, so you can set them in your CMakeLists.txt file, but you have to set them as CACHE varaibles.  They also have to be set before calling add_subdirector() for kokkos.  A minimal example:

```
set(KOKKOS_ENABLE_PTHREAD ON CACHE BOOL "" FORCE)
add_subdirectory(kokkos)
```

**Comment by gmackey** [comment]
You can also set them through ccmake or the CMake GUI or through command line parameters to cmake.

`cmake .. -DKOKKOS_ENABLE_OPENMP:BOOL=OFF`

**Comment by dholladay00** [comment]
This appears to work. I still need to look at performance and make sure nothing is drastically different in terms of kernel timing, but everything compiled, ran and passed in terms of correctness.

Enabling the option for `aggressive_vectorization` does not appear to be exposed when I look through the available options from `ccmake . `. Can that be added, or do I need to do `add_definitions (-DKOKKOS_INTERNAL_OPT_RANGE_AGGRESSIVE_VECTORIZATION)`

**Comment by gmackey** [comment]
I can add that option to the CMake build.

Thanks for trying it out as an initial user!  Let me know if you find anything else you need.

**Comment by gmackey** [comment]
@dholladay00 I just added the option.  Update from my branch and try it out.

**Comment by gmackey** [comment]
Oh, it's been renamed to KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION.

**Comment by dholladay00** [comment]
Excellent, I pulled most recent. I was testing out for when I *eventually* have things working with cuda, but ran into fun issues.

In your example, the c++ standard is set by cmake such that `-std=gnu++11` is added. When compiling for the cuda backend, running into [this](https://github.com/UoB-HPC/GPU-STREAM/issues/16). `std=c++11` is added elsewhere, and I verified that removing `std=gnu++11` fixed the compile error. 

According to the link, it is an issue with gcc. I have only tried with 5.3.0 and 5.4.0. I'll see what happens with 6, but I thought you should be aware as this broke the Kokkos build process.

```
[  1%] Building CXX object kokkos/CMakeFiles/kokkos.dir/core/src/impl/Kokkos_CPUDiscovery.cpp.o
cd /.../kokkos && /.../kokkos/bin/nvcc_wrapper   -D__MKL__ -D__USE_QUO__ -isystem /projects/opt/centos7/openmpi/1.10.3-gcc_5.4.0/include -I/.../kokkos/core/src -I/.../kokkos/containers/src -I/.../kokkos/algorithms/src -I/projects/opt/centos7/cuda/8.0/include -I/.../build_cuda/kokkos  -g   -std=c++11 -expt-extended-lambda -Xcompiler -fopenmp -g -std=gnu++11 -o CMakeFiles/kokkos.dir/core/src/impl/Kokkos_CPUDiscovery.cpp.o -c /.../kokkos/core/src/impl/Kokkos_CPUDiscovery.cpp
/projects/opt/centos7/gcc/5.3.0/packages/gcc-5.3.0/include/c++/5.3.0/type_traits(311): error: identifier "__float128" is undefined
```

**Comment by crtrott** [comment]
Greg, definitely use -std=c++11 instead of -std=gnu++11, the latter is NOT a c++ standard but some extension of it by GNU.

**Comment by gmackey** [comment]
@crtrott I can do that.  My initial thought was to let the user decide what to do and follow the CMake convention.  CMake made the choice, which I disagree with, to make using the extensions for C++11 (aka gnu++11) the default.  The user has to make a conscious choice to disable them and use the normal standard with the line

`set(CMAKE_CXX_EXTENSIONS OFF)
`
We can certainly change this behavior, but it's different from the normal CMake way of things.  Is that what you want?

BTW, this is not what is causing the error Daniel is seeing.  I've compiled in a lot of configurations using the GNU extensions and had no problems.  There's a particular bug in the standards in GCC 5.4 that causes this.

There's also another error where the std flag is being added twice.  Another user has run into this.

**Comment by dholladay00** [comment]
This is done internally by [default](https://cmake.org/cmake/help/v3.6/prop_tgt/CXX_EXTENSIONS.html#prop_tgt:CXX_EXTENSIONS) by cmake. I can set this myself, though I would not mind it being set internally.

**Comment by gmackey** [comment]
@dholladay00 Try adding the line

`set(CMAKE_CXX_EXTENSIONS OFF)
`

and see if it at least switches off the GNU extensions.  I'm investigating the other parts of your bug.

**Comment by crtrott** [comment]
Ah ok so this is coming in via CMakes discovery of the c++11 flag I guess, maybe CMake needs to fix that.

**Comment by gmackey** [comment]
@dholladay00 Did you see the error with GCC 5.3?  I was unable to duplicate the error using 5.3 with my small example.

**Comment by dholladay00** [comment]
I saw the error in 5.3 and 5.4

**Comment by gmackey** [comment]
@dholladay00 What machine are you compiling on, and what options are you changing from the defaults in your build?

**Comment by dholladay00** [comment]
I'm running on a machine called darwin at LANL. It's a machine that has lots of different backend types for testing out new things. I'm trying to see if I can get it to compile with 5.3.

**Comment by gmackey** [comment]
I'm trying on a different machine that has 5.4 installed.

**Comment by dholladay00** [comment]
In that example, where is `nvcc_wrapper` dealt with?

**Comment by gmackey** [comment]
It is assumed that the user took care of that.  The easiest way is to ensure that the environment variable CXX is set to the path to nvcc_wrapper.

**Comment by dholladay00** [comment]
Hmm… `SET (CMAKE_CXX_EXTENSIONS OFF)` puts 2 `-std=c++11` on the compile line which results in `nvcc fatal   : redefinition of argument 'std'`

```
[  1%] Building CXX object kokkos/CMakeFiles/kokkos.dir/core/src/impl/Kokkos_CPUDiscovery.cpp.o
cd /.../build_cuda/kokkos && /.../kokkos/bin/nvcc_wrapper   -D__MKL__ -D__USE_QUO__ -isystem /projects/opt/centos7/openmpi/1.6.5-gcc_5.3.0/include -I/.../kokkos/core/src -I/.../kokkos/containers/src -I/.../kokkos/algorithms/src -I/projects/opt/centos7/cuda/8.0/include -I/.../build_cuda/kokkos  -g   -std=c++11 -expt-extended-lambda -Xcompiler -fopenmp -mavx -g -std=c++11 -o CMakeFiles/kokkos.dir/core/src/impl/Kokkos_CPUDiscovery.cpp.o -c /.../kokkos/core/src/impl/Kokkos_CPUDiscovery.cpp
                                                                                                                                                                                                                                                                                                            ^^^^^^^^^^                                                     ^^^^^^^^^^
```

**Comment by gmackey** [comment]
That's what I expected.   I'm investigating why there are 2 -std=c++11 on the compile line.

**Comment by gmackey** [comment]
For now, if you temporarily comment out the line
 
set(CMAKE_CXX_STANDARD 11)
 
you should be able to compile.

**Comment by gmackey** [comment]
@dholladay00 I issued a fix in my cmake branch.  When you get a chance, would you try it out to make sure you can compile now with the following line both enabled and commented out?

set(CMAKE_CXX_STANDARD 11)

**Comment by dholladay00** [comment]
It works with the line commented and uncommented, but in both cases, **only** when I disable extensions (with gcc 5.3.0, have not tried with other compilers).

**Comment by gmackey** [comment]
I had noticed that.  NVCC (and consequently nvcc_wrapper) doesn't support the GNU extensions.  I'm going to add an error to the build process letting the user know what went wrong.  Or I might be able to add a warning and switch to not using extensions in this case.
