### ISSUE TITLE
Nightly compilation error, intel/17: TestLegionInteroperability.cpp(129): error: expression must have a constant value

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5214]
**Describe the bug**
Nightly builds with intel/17.0.1 fail to compile with output:
```
02:16:11 /home/jenkins/node/workspace/kokkos_osrhel7_intel_1701-dbg/kokkos/core/unit_test/TestLegionInteroperability.cpp(129): error: expression must have a constant value
02:16:11   std::enable_if_t<!has_deprecated_serial_impl_initialize_v<T>>
02:16:11                    ^
02:16:11 
02:16:11 /net/watson.sandia.gov/storage/fast/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/6.4.0/base/bin/../include/c++/6.4.0/type_traits(2523): error: class "std::enable_if<<error-constant>, void>" has no member "type"
02:16:11       using enable_if_t = typename enable_if<_Cond, _Tp>::type;
02:16:11                                                           ^
02:16:11           detected during instantiation of type "std::enable_if_t<<error-constant>, void>" at line 129 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1701-dbg/kokkos/core/unit_test/TestLegionInteroperability.cpp"
02:16:11 
02:16:11 /home/jenkins/node/workspace/kokkos_osrhel7_intel_1701-dbg/kokkos/core/unit_test/TestLegionInteroperability.cpp(135): error: static assertion failed with ""
02:16:11   STATIC_ASSERT(std::is_void<decltype(
02:16:11   ^
02:16:11 
02:16:11 compilation aborted for /home/jenkins/node/workspace/kokkos_osrhel7_intel_1701-dbg/kokkos/core/unit_test/TestLegionInteroperability.cpp (code 2)
02:16:11 make[2]: *** [core/unit_test/CMakeFiles/KokkosCore_TestCompileOnly.dir/TestLegionInteroperability.cpp.o] Error 2
```

**Please also include the following items to support reproducing the bug**
**Reproducer**:
```
module load sems-archive-env sems-archive-cmake/3.17.1 sems-archive-gcc/6.4.0 sems-archive-intel/17.0.1

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples   --with-options=enable_large_mem_tests
```

**Comment by ndellingwood** [comment]
Since this is specific to the test and intel/17 support will be dropped soon, should this test just be disabled for intel/17 to address rather than working around the compiler?

**Comment by ajpowelsnl** [comment]
> Since this is specific to the test and intel/17 support will be dropped soon, should this test just be disabled for intel/17 to address rather than working around the compiler?

@ndellingwood - good question.  I'll bring it up.
