### ISSUE TITLE
Nightly build errors with cuda/11.4.2+gcc/8.3.0: Kokkos_Bitset.hpp:38:26: error: '__T0' was not declared in this scope

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6515]
**Describe the bug**
Nightly Cuda builds with cuda/11.4.2+gcc/8.3.0 are failing to compile with error output:
```
02:06:15 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda1142_gcc830_cpp17/kokkos/containers/unit_tests/../src/Kokkos_Bitset.hpp:38:26: error: '__T0' was not declared in this scope
02:06:15      auto new_ctor_props(view_ctor_prop);
02:06:15                      ~~~~~^~~~~~~~~~~~~~~  
02:06:15 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda1142_gcc830_cpp17/kokkos/containers/unit_tests/../src/Kokkos_Bitset.hpp:38:26: note: suggested alternative: '__T1'
02:06:15      auto new_ctor_props(view_ctor_prop);
02:06:15                      ~~~~~^~~~~~~~~~~~~~~  
02:06:15                      __T1
02:06:15 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda1142_gcc830_cpp17/kokkos/containers/unit_tests/../src/Kokkos_Bitset.hpp:41:8: error: unable to deduce 'auto' from 'new_ctor_props'
02:06:15      return new_ctor_props;
02:06:15         ^~~~~~~~~~~~~~
02:06:15 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda1142_gcc830_cpp17/kokkos/containers/unit_tests/../src/Kokkos_Bitset.hpp: In instantiation of 'Kokkos::Bitset<Device>::Bitset(const Kokkos::Impl::ViewCtorProp<Args ...>&, unsigned int) [with P = {}; Device = Kokkos::Serial]':
02:06:15 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda1142_gcc830_cpp17/kokkos/containers/unit_tests/../src/Kokkos_Bitset.hpp:96:79:   required from 'Kokkos::Bitset<Device>::Bitset(unsigned int) [with Device = Kokkos::Serial]'
02:06:15 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda1142_gcc830_cpp17/kokkos/containers/unit_tests/TestBitset.hpp:158:13:   required from 'void Test::test_bitset() [with Device = Kokkos::Serial]'
02:06:15 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda1142_gcc830_cpp17/kokkos/containers/unit_tests/TestBitset.hpp:239:1523:   required from here
02:06:15 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda1142_gcc830_cpp17/kokkos/containers/unit_tests/../src/Kokkos_Bitset.hpp:110:12: error: 'const void prop_copy' has incomplete type
02:06:15      const auto prop_copy = Kokkos::Impl::with_updated_label(
```

This follows merge of #6198 

**Please also include the following items to support reproducing the bug**
**Reproducer** (kokkos-dev-2):
```bash
module load sems-cmake sems-gcc/8.3.0 sems-cuda/11.4.2

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --with-cuda-options=enable_lambda  --no-examples   --with-options=enable_large_mem_tests
```

**Comment by masterleinad** [comment]
@ndellingwood Can you try if
```
diff --git a/containers/src/Kokkos_Bitset.hpp b/containers/src/Kokkos_Bitset.hpp
index 8be327b04..0c3be44e5 100644
--- a/containers/src/Kokkos_Bitset.hpp
+++ b/containers/src/Kokkos_Bitset.hpp
@@ -33,15 +33,11 @@ namespace Impl {
 template <typename... P>
 auto with_updated_label(const ViewCtorProp<P...>& view_ctor_prop,
                         const std::string& label) {
-  //! If the label property is already set, append. Otherwise, set label.
-  if constexpr (ViewCtorProp<P...>::has_label) {
-    auto new_ctor_props(view_ctor_prop);
-    static_cast<ViewCtorProp<void, std::string>&>(new_ctor_props)
-        .value.append(label);
-    return new_ctor_props;
-  } else {
-    return Impl::with_properties_if_unset(view_ctor_prop, label);
-  }
+  static_assert(ViewCtorProp<P...>::has_label);
+  auto new_ctor_props(view_ctor_prop);
+  static_cast<ViewCtorProp<void, std::string>&>(new_ctor_props)
+      .value.append(label);
+  return new_ctor_props;
 }
 }  // namespace Impl
```
fixes this for you?

**Comment by ndellingwood** [comment]
@masterleinad I tested the change but I still see the same error:

```
/ascldap/users/ndellin/kokkos/containers/unit_tests/../src/Kokkos_Bitset.hpp:37:26: error: '__T0' was not declared in this scope
   auto new_ctor_props(view_ctor_prop);
                     ~~~~~^~~~~~~~~~~~~
/ascldap/users/ndellin/kokkos/containers/unit_tests/../src/Kokkos_Bitset.hpp:37:26: note: suggested alternative: '__T1'
   auto new_ctor_props(view_ctor_prop);
                     ~~~~~^~~~~~~~~~~~~
                     __T1
/ascldap/users/ndellin/kokkos/containers/unit_tests/../src/Kokkos_Bitset.hpp:40:8: error: unable to deduce 'auto' from 'new_ctor_props'
   return new_ctor_props;
        ^~~~~~~~~~~~~~
```

Tested with this diff:
```diff
diff --git a/containers/src/Kokkos_Bitset.hpp b/containers/src/Kokkos_Bitset.hpp
index 8be327b..fd41314 100644
--- a/containers/src/Kokkos_Bitset.hpp
+++ b/containers/src/Kokkos_Bitset.hpp
@@ -33,15 +33,11 @@ namespace Impl {
 template <typename... P>
 auto with_updated_label(const ViewCtorProp<P...>& view_ctor_prop,
                         const std::string& label) {
-  //! If the label property is already set, append. Otherwise, set label.
-  if constexpr (ViewCtorProp<P...>::has_label) {
-    auto new_ctor_props(view_ctor_prop);
-    static_cast<ViewCtorProp<void, std::string>&>(new_ctor_props)
-        .value.append(label);
-    return new_ctor_props;
-  } else {
-    return Impl::with_properties_if_unset(view_ctor_prop, label);
-  }
+  static_assert(ViewCtorProp<P...>::has_label);
+  auto new_ctor_props(view_ctor_prop);
+  static_cast<ViewCtorProp<void, std::string>&>(new_ctor_props)
+    .value.append(label);
+  return new_ctor_props;
 }
 }  // namespace Impl
```

**Comment by fnrizzi** [comment]
@ndellingwood https://github.com/kokkos/kokkos/pull/6518 this fixes it for me, can you please check?
