### PR TITLE
Fixup cast tolerance to double before printing

### LINKED ISSUE #6698: Nightly test failure, Hip backend: Kokkos_Printf.hpp:48:22: error: cannot pass object of non-trivial type 'Kokkos::Experimental::Impl::floating_point_wrapper<__half>' through variadic function; call will abort at runtime
**Describe the bug**

Nightly Hip builds fail to compile (`-Wnon-pod-varargs`), seen with rocm/5.2.0 and 5.6.0:
```
/home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi250_rocm560_hip_serial/kokkos/core/src/Kokkos_Printf.hpp:48:22: error: cannot pass object of non-trivial type 'Kokkos::Experimental::Impl::floating_point_wrapper<__half>' through variadic function; call will abort at runtime [-Wnon-pod-varargs]
    ::printf(format, args...);
                     ^
/home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi250_rocm560_hip_serial/kokkos/core/unit_test/TestMathematicalFunctions.hpp:316:17: note: in instantiation of function template specialization 'Kokkos::printf<double, Kokkos::Experimental::Impl::floating_point_wrapper<__half>>' requested here
        Kokkos::printf("relative difference exceeds tolerance [%e > %e]\n",
                ^
/home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi250_rocm560_hip_serial/kokkos/core/unit_test/TestMathematicalFunctions.hpp:572:15: note: in instantiation of function template specialization 'FloatingPointComparison::compare<Kokkos::Experimental::Impl::floating_point_wrapper<__half>, Kokkos::Experimental::Impl::floating_point_wrapper<__half>>' requested here
    bool ar = compare(Func::eval(val_[i]), res_[i], Func::ulp_factor());
              ^
/home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi250_rocm560_hip_serial/kokkos/core/src/Serial/Kokkos_Serial_Parallel_Range.hpp:82:7: note: in instantiation of member function 'TestMathUnaryFunction<Kokkos::Serial, MathUnaryFunction_sin, Kokkos::Experimental::Impl::floating_point_wrapper<__half>, 3, Kokkos::Experimental::Impl::floating_point_wrapper<__half>>::operator()' requested here
      m_functor_reducer.get_functor()(i, update);
      ^
/home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi250_rocm560_hip_serial/kokkos/core/src/Serial/Kokkos_Serial_Parallel_Range.hpp:121:20: note: in instantiation of function template specialization 'Kokkos::Impl::ParallelReduce<Kokkos::Impl::CombinedFunctorReducer<TestMathUnaryFunction<Kokkos::Serial, MathUnaryFunction_sin, Kokkos::Experimental::Impl::floating_point_wrapper<__half>, 3, Kokkos::Experimental::Impl::floating_point_wrapper<__half>>, Kokkos::Impl::FunctorAnalysis<Kokkos::Impl::FunctorPatternInterface::REDUCE, Kokkos::RangePolicy<Kokkos::Serial>, TestMathUnaryFunction<Kokkos::Serial, MathUnaryFunction_sin, Kokkos::Experimental::Impl::floating_point_wrapper<__half>, 3, Kokkos::Experimental::Impl::floating_point_wrapper<__half>>, int>::Reducer>, Kokkos::RangePolicy<Kokkos::Serial>, Kokkos::Serial>::exec<void>' requested here
    this->template exec<WorkTag>(update);
...
```

This error began following merge of these changes:

Fixup test math functions ulp should double -> int ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_carawaymi50_rocm520_hipserial/845/changes#71729af719b2eb20b512efad05ae609e74e1dd7a) / [githubweb](https://github.com/kokkos/kokkos/commit/71729af719b2eb20b512efad05ae609e74e1dd7a))
    #5333: CUDA: Use scratch space appropriate to small reduction elements in Team reductions (#5334) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_carawaymi50_rocm520_hipserial/845/changes#02b46c09c75697da5a1e4bfed5429a56c1bfb7ef) / [githubweb](https://github.com/kokkos/kokkos/commit/02b46c09c75697da5a1e4bfed5429a56c1bfb7ef))
    Cuda: Allocate using the correct device (#6392) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_carawaymi50_rocm520_hipserial/845/changes#4078a0d8a022ab1ad2291554b2820916fa3bc361) / [githubweb](https://github.com/kokkos/kokkos/commit/4078a0d8a022ab1ad2291554b2820916fa3bc361))
    Let `Profiling::ProfilingSection(std::string)` constructor be explicit and nodiscard (#6690) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_carawaymi50_rocm520_hipserial/845/changes#f485cfa53cb2d25cab98e7a1d41a116027ec2363) / [githubweb](https://github.com/kokkos/kokkos/commit/f485cfa53cb2d25cab98e7a1d41a116027ec2363))

**Please include the following for a minimal reproducer**
**Reproducer** (caraway MI50 or MI250 queue):
```bash
# Environment
module load cmake rocm/5.6.0

# Configure
${KOKKOS_PATH}/generate_makefile.bash --with-hip --with-serial --compiler=hipcc --arch=VEGA90A --kokkos-path=${KOKKOS_PATH}

# Compile
make -j16

```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #6698 
Bug introduced in #6647 and broke the SYCL build on Jenkins
```
/opt/intel/oneapi/compiler/2023.0.0/linux/bin-llvm/../include/sycl/ext/oneapi/experimental/builtins.hpp:89:10: error: cannot compile this non-scalar arg to printf yet
  return ::printf(__format, args...);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_SYCL1A.dir/build.make:538: core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_SYCL1A.dir/sycl/TestSYCL_MathematicalFunctions1.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2059: core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_SYCL1A.dir/all] Error 2

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
Why not declare `abs_tol` and `rel_tol` as `double` to begin with?

**Comment by dalg24** [comment]
> Why not declare `abs_tol` and `rel_tol` as `double` to begin with?

because the problem is when formatting the output to print and that preferably we compare results in their original type.

**Review by masterleinad — APPROVED** [review]
Good enough.

**Review by ndellingwood — APPROVED** [review]

**Comment by dalg24** [comment]
SYCL build had an issue but the Clang+CUDA build that was also showing the issue passed
