### PR TITLE
clang 17+: use new offload driver to support RDC

### PR DESCRIPTION
**Pull request by rbberger**
Addresses #2421

### CODE REVIEW

File: cmake/kokkos_arch.cmake [hunk 1]
```diff
@@ -680,7 +680,7 @@ endif()
 
 if(NOT KOKKOS_COMPILE_LANGUAGE STREQUAL CUDA)
   if(KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE)
-    compiler_specific_flags(Clang -fcuda-rdc NVIDIA --relocatable-device-code=true)
+    compiler_specific_flags(Clang -fgpu-rdc --offload-new-driver NVIDIA --relocatable-device-code=true)
```
Comment (dalg24) [inline cmake/kokkos_arch.cmake:683]: I could not find documentation about `--offload-new-driver`.
Why do we need it?

Comment (rbberger) [reply cmake/kokkos_arch.cmake:683]: See slide 13, https://www.openmp.org/wp-content/uploads/OpenMP-Offloading-in-LLVM-15.pdf. This is not just about OpenMP offloading, but enables OpenMP target offload and HIP/CUDA interoperability. Without `--offload-new-driver` you get the errors like `undefined reference to `__cudaRegisterLinkedBinary__nv_50a56434682ff3e9` in issue #2421.

Comment (rbberger) [reply cmake/kokkos_arch.cmake:683]: Also see https://www.youtube.com/watch?v=4NnzymmQe7k for more context.

Comment (rbberger) [reply cmake/kokkos_arch.cmake:683]: Btw, I did try to also add `--offload-link` to the linker flags, but that produces "unused command-line" option warnings. That's why I left that out. Despite this, all unit tests seem to pass.

**Comment by tpadioleau** [comment]
Thanks for this contribution, I am interested to test this with DDC, come back to you as soon as possible.

**Review by dalg24 — DISMISSED** [review]

**Comment by masterleinad** [comment]
We should think adding a CI build for Clang+Cuda+RDC.

**Review by masterleinad — APPROVED** [review]

**Comment by tpadioleau** [comment]
@rbberger what version of llvm did you use ? I have errors at the link stage in the tests of my library:
```
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: nvlink command failed due to signal (use -v to see invocation)
Ubuntu clang version 18.1.8 (11~20.04.2)
Target: nvptx64-nvidia-cuda
Thread model: posix
InstalledDir: /usr/lib/llvm-18/bin
```

I have tried your branch, with llvm@18 and cuda@11.8

**Comment by rbberger** [comment]
LLVM 19.1.7, CUDA 12.8

**Comment by tpadioleau** [comment]
Ok thanks, I will give a try in an other environment.

**Comment by rbberger** [comment]
I'll do some tests with older compilers as well. There was a bigger change with 19, so maybe it is just 19+. I wrote 15 because it seems the relevant parts were introduced at that version.

**Comment by masterleinad** [comment]
This seems to work fine for me on `Polaris` with Clang 19.1.7 and Cuda 12.2.2.

**Comment by rbberger** [comment]
Confirmed Kokkos unit tests work with LLVM 18.1.8 and CUDA 12.4.1. Currently building LLVM 15, 16, and 17 over night to continue verification.

**Comment by rbberger** [comment]
FYI, I'm building LLVM with Spack as follows:
```yaml
specs:
  - llvm@19.1.7%gcc@13.2.0 targets=x86,nvptx,amdgpu +flang+libomptarget+gold+offload arch=x86_64
  - llvm@18.1.8%gcc@13.2.0 targets=x86,nvptx,amdgpu +flang+libomptarget+gold arch=x86_64
#  - llvm@17.0.6%gcc@13.2.0 targets=x86,nvptx,amdgpu +flang+libomptarget+gold arch=x86_64 (still testing)
# - llvm@16.0.6%gcc@13.2.0 targets=x86,nvptx,amdgpu +flang+libomptarget+gold arch=x86_64 (still testing)
# - llvm@15.0.7%gcc@13.2.0 targets=x86,nvptx,amdgpu +flang+libomptarget+gold arch=x86_64 (still testing)
  - binutils@2.43.1+gold+ld+headers arch=x86_64
```

**Comment by tpadioleau** [comment]
Good news, I could compile and run DDC tests with llvm 19.

I had to workaround one issue with anonymous namespaces though. If one declares device variables with the same name in anonymous namespaces, the linker complains about multiple definitions.

File: cmake/kokkos_enable_options.cmake [hunk 2]
```diff
@@ -197,13 +197,14 @@ if(KOKKOS_COMPILE_LANGUAGE STREQUAL CUDA)
...
 endif()
 
-# This is known to occur with Clang 9. We would need to use nvcc as the linker
+# This is known to occur with Clang 9 until Clang 15. We would need to use nvcc as the linker
 # http://lists.llvm.org/pipermail/cfe-dev/2018-June/058296.html
-# TODO: Through great effort we can use a different linker by hacking
-# CMAKE_CXX_LINK_EXECUTABLE in a future release
-if(KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE AND KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
+if(KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE AND KOKKOS_CXX_COMPILER_ID STREQUAL Clang AND KOKKOS_CXX_COMPILER_VERSION
+                                                                                            VERSION_LESS 15
```
Comment (tpadioleau) [inline cmake/kokkos_enable_options.cmake:203]:
```suggestion
                                                                                            VERSION_LESS 18
```
I would be a bit more conservative, if we don't want to test versions less than 18, let's not allow it ? Moreover we don't have CI about that yet.

**Review by tpadioleau — CHANGES_REQUESTED** [review]
Overall is ok for me, I would just be stricter about the version of clang we implicitly claim to support.

File: cmake/kokkos_arch.cmake (hunk 1 above)
Comment (jjellio) [reply cmake/kokkos_arch.cmake:683]: offload-new-driver is an optimization that does among other things substantially reduces file IO.  It also bundles global variable initializations into a single HIP or Cuda call, which can make a marked difference in program startup (as in 5+ mins while it iterates over the symbol table setting each global one at a time). For SNL apps all this put together is rather substantial.

**Comment by masterleinad** [comment]
I pushed a commit for testing that modifies the existing Clang-15+Cuda build. If this works we likely want a separate build.
Retest this please.

**Comment by rbberger** [comment]
No success with Clang 15 and 16, partly because of difficulties finding a good GCC, Clang, CUDA combination (the whole CUDA 11 -> 12 transition and fun with GCC headers), part of linker failures.

**Comment by rbberger** [comment]
Same for me with Clang 17.0.6 + CUDA 12.8.0. Everything passes. Seems to me it's reasonable to limit this to Clang >=17.

Next up, I need to do more client tests and see if there is anything missing on the installed CMake front.

**Comment by jjellio** [comment]
> Same for me with Clang 17.0.6 + CUDA 12.8.0. Everything passes. Seems to me it's reasonable to limit this to Clang >=17.
> 
> Next up, I need to do more client tests and see if there is anything missing on the installed Kokkos CMake front.

Richard, I think it's great to get some CI on this - as this is a technology that makes sense with RDC links.  That said, if you start poking AMD's clang fork, you'll find it works, then didn't, and it will start working again in rocm 6.4.  This instability was caused by RDC link optimizations that AMD has been working on - and how stable that is in the release of 6.4... I'm not too sure on.  If you want to ping me on my SNL email (or grab me at the COE hackathon), I can discuss more on all of this.

**Comment by rbberger** [comment]
@jjellio yeah, we can talk about AMD during the March hackathon.

File: cmake/kokkos_enable_options.cmake (hunk 2 above)
Comment (rbberger) [reply cmake/kokkos_enable_options.cmake]: Increased version requirement to Clang 17.

**Comment by masterleinad** [comment]
Retest this please.

File: cmake/kokkos_arch.cmake (hunk 1 above)
Comment (rbberger) [reply cmake/kokkos_arch.cmake:683]: Finally found a meaningful documentation page: https://openmp.llvm.org/CommandLineArgumentReference.html

**Comment by tpadioleau** [comment]
> @tpadioleau the Clang 18 you tested was the Ubuntu package, right? Does that come with libomptarget?

As discussed on Slack, i tested Clang 18 from the Ubuntu packages. I also added the libomp-dev package but it didn't help. I was using cuda 11.8, i don't know if it can be a bad combination ?

**Comment by masterleinad** [comment]
Retest this please.

**Comment by dalg24** [comment]
```
clang++-17: error: argument unused during compilation: '--cuda-gpu-arch=sm_70' [-Werror,-Wunused-command-line-argument]

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
`CUDA-12.5.1-Clang-17-RDC` passed (we need #7846 to enable clang-tidy).

File: core/src/Cuda/Kokkos_Cuda_Task.hpp
Comment (dalg24) [inline core/src/Cuda/Kokkos_Cuda_Task.hpp:1]: Did you mean to push these changes?

**Review by tpadioleau — APPROVED** [review]
Seems ok to me

File: core/src/Cuda/Kokkos_Cuda_Task.hpp
[the remark this answers is not in the document]
Comment (masterleinad) [reply core/src/Cuda/Kokkos_Cuda_Task.hpp:1]: No, they will still be called from `__host__ __device__` functions. As soon as a function is `__host__ __device__`, eevrything downstream from it also need to have this annotation (unless guarded bu `KOKKOS_IF_ON_HOST`/`KOKKOS_IF_ON_DEVICE`.
