### PR TITLE
Fixup CUDA backend when profiling disabled

### LINKED ISSUE #3001: Compilation fails when profiling disabled and CUDA enabled
Both master and develop branches fail to compile if `Kokkos_ENABLE_PROFILING` is disabled. This happens when compiling the _CUDA backend, using Clang compiler_. Error `DeviceTypeTraits` is not declared, I guess due to not including `Kokkos_Profiling_Interface.hpp` that declares it...

```
In file included from /home/josip/Code/kokkos/core/src/Cuda/Kokkos_Cuda_Locks.cpp:51:
/home/josip/Code/kokkos/core/src/Kokkos_Cuda.hpp:279:8: error: explicit specialization of undeclared template struct 'DeviceTypeTraits'
struct DeviceTypeTraits<Cuda> {
       ^               ~~~~~~
/home/josip/Code/kokkos/core/src/Kokkos_Cuda.hpp:281:20: error: unknown type name 'DeviceType'
  static constexpr DeviceType id = DeviceType::Cuda;
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #3001
Bug was introduced in #2824

### CODE REVIEW

**Comment by masterleinad** [comment]
The related definition of the general template is https://github.com/kokkos/kokkos/blob/ea8a8f01dd9d522701717078dc950618dd7f1798/core/src/impl/Kokkos_Profiling_Interface.hpp#L55-L82
so we explicitly define it even if `Kokkos_ENABLE_PROFILING=OFF`. @DavidPoliakoff Is there a reaon for that? If so, I think also the specialization should be defined.

**Comment by DavidPoliakoff** [comment]
@masterleinad , @crtrott and I had a discussion about this. Basically, he saw the DeviceType thought as being useful out side of Profiling, so I implemented it as universally on. Under that logic, we'd want these specializations defined as well.

**Comment by crtrott** [comment]
Gonna cherry-pick that one commit also into 3.1.1
