### ISSUE TITLE
cuda+xl compilation error in numeric traits

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#3934]
cuda/10.1 builds on Power with xl/16.1.1 as host compiler fail to compile on develop and release-candidate-3.4.0 (SHA d3a6b0a959512e6fe6d6bb062b585bf005441c6b) branches with errors of the form:

```
/ascldap/users/ndellin/kokkos/core/src/Kokkos_NumericTraits.hpp(98): error: a constexpr static data member declaration requires an in-class initializer

/ascldap/users/ndellin/kokkos/core/src/Kokkos_NumericTraits.hpp(98): error: data member initializer is not allowed
```

The error message doesn't really make sense (there is an in-class initializer), seems a compiler hiccup.
Extra note, replacing `LDBL_EPSILON` with `DBL_EPSILON`, though incorrect value for the `long double` type, allows compilation to complete.

Sample reproducer instructions for white testbed (this is using the launch compiler, and not nvcc_wrapper):
```
module load git cmake/3.19.3 cuda/10.1.105 gcc/7.2.0 ibm/xl/16.1.1

export XLC_USR_CONFIG=/opt/ibm/xlC/16.1.1/etc/xlc.cfg.rhel.7.6.gcc.7.2.0.cuda.10.1

cmake -DCMAKE_CXX_COMPILER=xlc++ -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -qxflag=disable__cplusplusOverride" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_PASCAL60=ON -DKokkos_ARCH_POWER8=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RELEASE" $KOKKOS_PATH
```

**Comment by masterleinad** [comment]
```diff
diff --git a/core/src/Kokkos_NumericTraits.hpp b/core/src/Kokkos_NumericTraits.hpp
index b0e030786..5b6991a71 100644
--- a/core/src/Kokkos_NumericTraits.hpp
+++ b/core/src/Kokkos_NumericTraits.hpp
@@ -92,10 +92,30 @@ template <> struct finite_max_helper<unsigned long long int> { static constexpr
 template <> struct finite_max_helper<float> { static constexpr float value = FLT_MAX; };
 template <> struct finite_max_helper<double> { static constexpr double value = DBL_MAX; };
 template <> struct finite_max_helper<long double> { static constexpr long double value = LDBL_MAX; };
-template <class> struct epsilon_helper;
+template <class T> struct epsilon_helper
+{
+  static constexpr T value = T{};
+};
+
+template<typename T>
+constexpr T machineeps() {
+  T epsilon = 1;
+  T prev=1;
+  T expression=1;
+
+  do {
+    prev = epsilon;
+    epsilon /= 2;
+    expression = 1 + epsilon;
+  } while (expression > 1);
+
+  return prev;
+}
+
+template <typename T> constexpr T epsilon_helper<T>::value;
 template <> struct epsilon_helper<float> { static constexpr float value = FLT_EPSILON; };
 template <> struct epsilon_helper<double> { static constexpr double value = DBL_EPSILON; };
-template <> struct epsilon_helper<long double> { static constexpr long double value = LDBL_EPSILON; };
+template <> struct epsilon_helper<long double> { static constexpr long double value = machineeps<long double>(); };
 template <class> struct round_error_helper;
 template <> struct round_error_helper<float> { static constexpr float value = 0.5F; };
 template <> struct round_error_helper<double> { static constexpr double value = 0.5; };
```
seems to work for me.
