### ISSUE TITLE
Build error with relocatable device code with CUDA 10.1 GCC 7.3

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#2134]
```
/var/jenkins/workspace/Kokkos/core/src/impl/Kokkos_TaskQueueMultiple_impl.hpp: In instantiation of 'void Kokkos::Impl::TaskQueueMultiple<ExecSpace, MemorySpace>::Destroy::destroy_shared_allocation() [with ExecSpace = Kokkos::Cuda; MemorySpace = Kokkos::CudaUVMSpace]':
/var/jenkins/workspace/Kokkos/core/src/Cuda/Kokkos_Cuda_Task.cpp:58:16:   required from here
/var/jenkins/workspace/Kokkos/core/src/impl/Kokkos_TaskQueueMultiple_impl.hpp:59:16: error: cannot call member function 'Kokkos::Impl::TaskQueueMultiple<ExecSpace, MemorySpace>::team_queue_type& Kokkos::Impl::TaskQueueMultiple<ExecSpace, MemorySpace>::get_team_queue(int) [with ExecSpace = Kokkos::Cuda; MemorySpace = Kokkos::CudaUVMSpace; Kokkos::Impl::TaskQueueMultiple<ExecSpace, MemorySpace>::team_queue_type = Kokkos::Impl::TaskQueueMultiple<Kokkos::Cuda, Kokkos::CudaUVMSpace>]' without object
   m_queue->get_team_queue(0).~TaskQueueMultiple();
   ~~~~~~~~~~~~~^~~
/var/jenkins/workspace/Kokkos/Makefile.targets:48: recipe for target 'Kokkos_Cuda_Task.o' failed
make[1]: *** [Kokkos_Cuda_Task.o] Error 1
make[1]: Leaving directory '/var/jenkins/workspace/Kokkos/build/core'
Makefile:12: recipe for target 'kokkoslib-test' failed
make: *** [kokkoslib-test] Error 2
```

_Originally posted by @crtrott in https://github.com/kokkos/kokkos/pull/2126#issuecomment-491892858_

**Comment by crtrott** [comment]
Looks like a compiler issue. This works with CUDA 10.1 / GCC 6.1 it also works with GCC 7.3 building for OpenMP. I have a workaround like this, which is further indication this is a compiler bug. 
```c++
// KOKKOS WORKAROUND for CUDA 10.1 with GCC 7.3.0
#if(KOKKOS_COMPILER_CUDA_VERSION==101) && defined(KOKKOS_COMPILER_NVCC) && (KOKKOS_COMPILER_GNU==730)
  (*m_queue).get_team_queue(0).~TaskQueueMultiple();
#else
  m_queue->get_team_queue(0).~TaskQueueMultiple();
#endif
```

**Comment by crtrott** [comment]
Bug doesn't happen with GCC 7.2 but does with GCC 7.4
