### PR TITLE
Promote KOKKOS_IMPL_[B]HALF_TYPE_DEFINED to KOKKOS_HAS_NATIVE_[B]HALF_TYPE

### LINKED ISSUE #9431: Kokkos half: export cmake variable to know when half is not aliasing float
I am trying to enable Kokkos::Experimental::half_t in Kokkos Kernels' ETI system.
When I do it naively it creates duplicate symbols for objects templated on half_t and float on architecture that do not support half_t yet (pretty much all CPU builds...).
Exporting a CMake variable would allow me to check at configure time if half_t can safely be included in the list of types to instantiate, of not I can error out with a helpful message for the user.

### PR DESCRIPTION
**Pull request by masterleinad**
This allows detecting proper half_t support via
```CMake
include(CheckCXXSymbolExists)
# Syntax: check_cxx_symbol_exists(<macro_name> <header_file> <result_variable>)
check_cxx_symbol_exists(KOKKOS_HALF_TYPE_DEFINED "Kokkos_Macros.hpp" KOKKOS_CORE_HAS_HALF_T)
```
at configure time.

### Related issues / PRs

Fixes https://github.com/kokkos/kokkos/issues/9431.

### Changelog Entry
- Yes

### Documentation PR
- Maybe

### CODE REVIEW

**Review by JBludau — COMMENTED** [review]
What was the original motivation for not making them public?

**Comment by masterleinad** [comment]
> What was the original motivation for not making them public?

The macro was introduced in https://github.com/kokkos/kokkos/commit/5cb888dd8ff9e1d7ef7458141eca74210eb43bf5 but is only exported in `Kokkos_Macros.hpp` since 141fe0fb6bc1b9fca3d9991321a5968bdd6af357 so it wasn't (easily) visible initially anyway. https://github.com/kokkos/kokkos/pull/9203 (which includes 141fe0fb6bc1b9fca3d9991321a5968bdd6af357) focused on not changing behavior and we assumed that the previously available `KOKKOS_HALF_T_IS_FLOAT` would be good enough for downstream users (but it's awkward for configure-time detection).
We could try retiring `KOKKOS_HALF_T_IS_FLOAT` as well.

**Comment by JBludau** [comment]
> > What was the original motivation for not making them public?
> 
> The macro was introduced in [5cb888d](https://github.com/kokkos/kokkos/commit/5cb888dd8ff9e1d7ef7458141eca74210eb43bf5) but is only exported in `Kokkos_Macros.hpp` since [141fe0f](https://github.com/kokkos/kokkos/commit/141fe0fb6bc1b9fca3d9991321a5968bdd6af357) so it wasn't (easily) visible initially anyway. #9203 (which includes [141fe0f](https://github.com/kokkos/kokkos/commit/141fe0fb6bc1b9fca3d9991321a5968bdd6af357)) focused on not changing behavior and we assumed that the previously available `KOKKOS_HALF_T_IS_FLOAT` would be good enough for downstream users (but it's awkward for configure-time detection).

Hmm are we convinced that 
```
include(CheckCXXSymbolExists)
# Syntax: check_cxx_symbol_exists(<macro_name> <header_file> <result_variable>)
check_cxx_symbol_exists(KOKKOS_HALF_T_IS_FLOAT "Kokkos_Macros.hpp" KOKKOS_CORE_HALF_T_IS_FLOAT)
```
is not clear enough? I actually find it more expressive than `KOKKOS_HALF_TYPE_DEFINED` which does not say that it could not be defined to be `float`...

**Comment by masterleinad** [comment]
```
check_cxx_symbol_exists(KOKKOS_HALF_T_IS_FLOAT "Kokkos_Macros.hpp" KOKKOS_CORE_HALF_T_IS_FLOAT)
```
won't work since `KOKKOS_HALF_T_IS_FLOAT` is always defined. This pull request currently proposes something that is backward-compatible and allows `check_cxx_symbol_exists` to work.

**Review by lucbv — APPROVED** [review]
I am fine with the change, so here we would check if `KOKKOS_HALF_TYPE_DEFINED` exists at which point we know that it is safe to instantiate on `KE::{b}half_t`

**Comment by JBludau** [comment]
> ```cmake
> include(CheckCXXSymbolExists)
> # Syntax: check_cxx_symbol_exists(<macro_name> <header_file> <result_variable>)
> check_cxx_symbol_exists(KOKKOS_HALF_TYPE_DEFINED "Kokkos_Macros.hpp" KOKKOS_CORE_HAS_HALF_T)
> ```

Huh, I thought that `check_cxx_symbol_exists` would also capture the value of the symbol but it seems like it is not.
I see that running a full compile check just to get this info is not nice

**Review by ldh4 — APPROVED** [review]

**Review by crtrott — CHANGES_REQUESTED** [review]
I get the motivation but I don't like the name at all. Kokkos::half exists whether that thing is defined or not. And its one thing if its internal, another if its public.

**Comment by crtrott** [comment]
Maybe KOKKOS_HAS_NATIVE_HALF_TYPE, or KOKKOS_HAS_TRUE_HALF_TYPE? Its a positive thing again instead of a negation, we use the KOKKOS_HAS for SharedSpace as well to express existence.

**Comment by masterleinad** [comment]
Let me go with `KOKKOS_HAS_NATIVE_HALF_TYPE` then.

File: core/src/Kokkos_Macros.hpp [hunk 1]
```diff
@@ -690,13 +690,13 @@
 #define KOKKOS_IMPL_EXPORT
 #endif
 
-#ifdef KOKKOS_IMPL_HALF_TYPE_DEFINED
+#ifdef KOKKOS_HAS_NATIVE_HALF_TYPE
 #define KOKKOS_HALF_T_IS_FLOAT false
```
Comment (JBludau) [inline core/src/Kokkos_Macros.hpp:694]: Why not keep all the IMPL ones and just define the new one here?

Comment (masterleinad) [reply core/src/Kokkos_Macros.hpp:694]: I don't see a good reason why we need both an IMPL and a non-IMPL macro.

**Review by crtrott — APPROVED** [review]
Agree with Daniel, that I don't see a reason for keeping the IMPL one.

File: core/src/Kokkos_Macros.hpp (hunk 1 above)
Comment (JBludau) [reply core/src/Kokkos_Macros.hpp:694]: Since this duplicates the functionality of `KOKKOS_HALF_T_IS_FLOAT` should we deprecate that one?

Comment (masterleinad) [reply core/src/Kokkos_Macros.hpp:694]: Sure, but I don't think there is a way to do that visible to the user portably and in particular not with `gcc`.
Are we OK with just guarding the macro for deprecated code 5 being enabled?

Comment (JBludau) [reply core/src/Kokkos_Macros.hpp]: We should at least add some comments in https://kokkos.org/kokkos-core-wiki/API/core/numerics/half-precision-types.html

It is still in `Experimental` after all

Comment (JBludau) [reply core/src/Kokkos_Macros.hpp:694]: We should at least add some comments in https://kokkos.org/kokkos-core-wiki/API/core/numerics/half-precision-types.html

It is still in `Experimental` after all
