### ISSUE TITLE
Nightly build failure, intel/19.0.5,2021.3 icpc (intel classic compiler), simd unit tests

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7674]
**Describe the bug**

Nightly builds with intel/19.0.5 icpc are failing to compile with error:
```
15:18:48 /data/jenkins/workspace/kokkos_osrhel8_intel_1905_openmp_serial/kokkos/simd/unit_tests/include/TestSIMD_WhereExpressions.hpp(156): error: a field declaration cannot have a type involving a variable length array
15:18:48           return (mask[i]) ? src[index[i]] : dst[i];
15:18:48                                              ^
15:18:48           detected during:
15:18:48             instantiation of "void device_check_where_expr<Abi,DataType>() [with Abi=Kokkos::Experimental::simd_abi::scalar, DataType=int32_t={__int32_t={signed int}}]" at line 201
15:18:48             instantiation of "void device_check_where_expr_all_types<Abi,DataTypes...>(Kokkos::Experimental::Impl::data_types<DataTypes...>) [with Abi=Kokkos::Experimental::simd_abi::scalar, DataTypes=<int32_t={__int32_t={signed int}}, uint32_t={__uint32_t={unsigned int}}, int64_t={__int64_t={signed long}}, uint64_t={__uint64_t={unsigned long}}, double, float>]" at line 208
15:18:48             instantiation of "void device_check_where_expr_all_abis(Kokkos::Experimental::Impl::abi_set<Abis...>) [with Abis=<Kokkos::Experimental::simd_abi::scalar>]" at line 214
```

This began following merge of these commits:

**Changes**

    Use cmakedefine directive for version macros in generated config file ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel8_intel_1905_openmp_serial/1275/changes#f5fbf899509e27ab6bf285af71f9bfaeb56c2563) / [githubweb](https://github.com/kokkos/kokkos/commit/f5fbf899509e27ab6bf285af71f9bfaeb56c2563))
    Merge pull request #7630 from ldh4/simd_remove_proxy_reference ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel8_intel_1905_openmp_serial/1275/changes#12174dc3bc414cace7969ecc27adaee0b5bd1777) / [githubweb](https://github.com/kokkos/kokkos/commit/12174dc3bc414cace7969ecc27adaee0b5bd1777))

**Please include the following for a minimal reproducer**
**Reproducer notes**:
```bash
module load sems-cmake sems-intel/19.0.5

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -Wall" --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --no-examples   --with-options=enable_large_mem_tests
```

**Comment by dalg24** [comment]
Caused by #7630 
Ping @ldh4

**Comment by ndellingwood** [comment]
Issue is resolved for me with #7678
