### ISSUE TITLE
Jenkins failures after merge of thread-sanitizer PR

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2555]
The following Jenkins builds are failing after merge of PR #2375

**Kokkos_develop_kokkos-dev_intel_1502**

```
In file included from <https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_intel_1502/ws/kokkos/core/src/Kokkos_Atomic.hpp(294),>
                 from <https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_intel_1502/ws/kokkos/core/src/impl/Kokkos_Atomic_View.hpp(47),>
                 from <https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_intel_1502/ws/kokkos/core/src/impl/Kokkos_ViewMapping.hpp(57),>
                 from <https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_intel_1502/ws/kokkos/core/src/Kokkos_View.hpp(457),>
                 from <https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_intel_1502/ws/kokkos/core/src/Kokkos_Parallel.hpp(52),>
                 from <https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_intel_1502/ws/kokkos/core/src/Kokkos_Serial.hpp(55),>
                 from <https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_intel_1502/ws/kokkos/core/src/Kokkos_Core.hpp(53),>
                 from <https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_intel_1502/ws/kokkos/core/unit_test/TestReduceDeviceView.hpp(1),>
                 from <https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_intel_1502/ws/kokkos/core/unit_test/threads/TestThreads_Reductions_DeviceView.cpp(45)>:
<https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_intel_1502/ws/kokkos/core/src/impl/Kokkos_Atomic_Store.hpp(94)>: error: the global scope has no "value"
                std::is_trivially_copyable<T>::value
                                               ^
```

**gcc-4.9.3-OpenMP_Serial-release (build failed)
gcc-4.9.3-Pthreads-hwloc-release (build failed)
gcc-4.9.3-Pthreads-release (build failed)
gcc-4.8.4-OpenMP-release (build failed)
gcc-4.8.4-Pthreads-release (build failed)**
Link error with undefined reference to `__atomic_load`

```
TestThreads_Atomics.o: In function `_ZN6Kokkos4Impl11ParallelForIN10TestAtomic10CASFunctorINS_7complexIdEENS_7ThreadsEEENS_11RangePolicyIJS6_EEES6_E4execERNS0_11ThreadsExecEPKv':
TestThreads_Atomics.cpp:(.text._ZN6Kokkos4Impl11ParallelForIN10TestAtomic10CASFunctorINS_7complexIdEENS_7ThreadsEEENS_11RangePolicyIIS6_EEES6_E4execERNS0_11ThreadsExecEPKv[_ZN6Kokkos4Impl11ParallelForIN10TestAtomic10CASFunctorINS_7complexIdEENS_7ThreadsEEENS_11RangePolicyIIS6_EEES6_E4execERNS0_11ThreadsExecEPKv]+0x47): undefined reference to `__atomic_load_16'
TestThreads_Atomics.o: In function `_ZN6Kokkos4Impl14ParallelReduceIN10TestAtomic16CASFunctorReduceINS_7complexIdEENS_7ThreadsEEENS_11RangePolicyIJS6_EEENS_11InvalidTypeES6_E4execERNS0_11ThreadsExecEPKv':
TestThreads_Atomics.cpp:(.text._ZN6Kokkos4Impl14ParallelReduceIN10TestAtomic16CASFunctorReduceINS_7complexIdEENS_7ThreadsEEENS_11RangePolicyIIS6_EEENS_11InvalidTypeES6_E4execERNS0_11ThreadsExecEPKv[_ZN6Kokkos4Impl14ParallelReduceIN10TestAtomic16CASFunctorReduceINS_7complexIdEENS_7ThreadsEEENS_11RangePolicyIIS6_EEENS_11InvalidTypeES6_E4execERNS0_11ThreadsExecEPKv]+0x57): undefined reference to `__atomic_load_16'
TestThreads_Atomics.o: In function `TestAtomic::CASFunctor<TestAtomic::SuperScalar<4>, Kokkos::Threads>::operator()(int) const':
TestThreads_Atomics.cpp:(.text._ZNK10TestAtomic10CASFunctorINS_11SuperScalarILi4EEEN6Kokkos7ThreadsEEclEi[_ZNK10TestAtomic10CASFunctorINS_11SuperScalarILi4EEEN6Kokkos7ThreadsEEclEi]+0x28): undefined reference to `__atomic_load'
TestThreads_Atomics.o: In function `TestAtomic::CASFunctorReduce<TestAtomic::SuperScalar<4>, Kokkos::Threads>::operator()(int, int&) const':
TestThreads_Atomics.cpp:(.text._ZNK10TestAtomic16CASFunctorReduceINS_11SuperScalarILi4EEEN6Kokkos7ThreadsEEclEiRi[_ZNK10TestAtomic16CASFunctorReduceINS_11SuperScalarILi4EEEN6Kokkos7ThreadsEEclEiRi]+0x28): undefined reference to `__atomic_load'
collect2: error: ld returned 1 exit status
```

**Comment by ndellingwood** [comment]
The atomics issue is strange because it looks like a fix was pushed for this in commit 197a420f7fbe4538205e063e5894b0e874a4e01e to allow for gcc/4.8.4 + OpenMP testing to pass CI testing.
Adding @dhollman

**Comment by masterleinad** [comment]
> The gcc+openmp atomics issue is strange because it looks like a fix was pushed for this in commit [197a420](https://github.com/kokkos/kokkos/commit/197a420f7fbe4538205e063e5894b0e874a4e01e) to allow for gcc/4.8.4 + OpenMP testing to pass CI testing.

What does the Jenkins file look like? That commit only patches CI but doesn't add the flag in general.

**Comment by ndellingwood** [comment]
> That commit only patches CI but doesn't add the flag in general

I didn't realize that, thanks for the info.

The Jenkins jobs we run are set up through a SEMS GUI, we do not set up an explicit Jenkins file. In all cases they end up calling the `kokkos/scripts/testing_scripts/test_all_sandia` script with some subset of options for a particular machine.

The `generate_makefile` script can be used for any of the failing builds, for example with the gcc/4.8.4 module loaded:

```
<PATH_TO_KOKKOS>/generate_makefile.bash --with-openmp --compiler=g++
make unit-tests-only -j
```

**Comment by crtrott** [comment]
We need to add -latomic to the Makefile too under the same conditions as in cmake.

**Comment by ndellingwood** [comment]
Failing build summary since PR #2375 merge:

**intel builds**:
Sample error message
```
/home/jenkins/bowman/workspace/Kokkos_SLURM_inner_test/core/src/impl/Kokkos_Atomic_Load.hpp(153): error: the global scope has no "value"
                                        !std::is_trivially_copyable<T>::value
```
intel-15.0.2-OpenMP-release (build failed)
intel-15.0.2-Pthreads_Serial-release (build failed)
intel-16.0.3-OpenMP-release (build failed)
intel-16.0.3-Pthreads_Serial-release (build failed)
intel-17.0.1-OpenMP-release (build failed)
intel-17.0.1-Pthreads_Serial-release (build failed)
intel_17*
intel_180128*


**gcc builds**:
Link error with undefined reference to `__atomic_load`
gcc-4.9.3-OpenMP_Serial-release (build failed)
gcc-4.9.3-Pthreads-hwloc-release (build failed)
gcc-4.9.3-Pthreads-release (build failed)
gcc-4.8.4-OpenMP-release (build failed)
gcc-4.8.4-Pthreads-release (build failed)


**cuda builds**:
Sample error message
```
<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_10_gcc_740_kepler/ws/kokkos/core/src/impl/Kokkos_Atomic_Generic.hpp(358)>: error: qualifiers dropped in binding reference of type "const Kokkos::complex<double> &" to initializer of type "volatile Kokkos::complex<double>"
          detected during:
            instantiation of "T Kokkos::Impl::atomic_oper_fetch(const Oper &, volatile T *, Kokkos::Impl::enable_if<<expression>, const T>::type &) [with Oper=Kokkos::Impl::NoOpOper<Kokkos::complex<double>>, T=Kokkos::complex<double>]"
<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_10_gcc_740_kepler/ws/kokkos/core/src/impl/Kokkos_Atomic_Load.hpp(244)>: here
            instantiation of "T Kokkos::Impl::_relaxed_atomic_load_impl(T *, std::enable_if<<expression>, const void **>::type) [with T=Kokkos::complex<double>]"
<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_10_gcc_740_kepler/ws/kokkos/core/src/impl/Kokkos_Atomic_Load.hpp(264)>: here
            instantiation of "T Kokkos::Impl::_atomic_load(T *, Kokkos::Impl::memory_order_relaxed_t) [with T=Kokkos::complex<double>]"
<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_10_gcc_740_kepler/ws/kokkos/core/src/impl/Kokkos_Atomic_Load.hpp(327)>: here
            instantiation of "T Kokkos::Impl::atomic_load(T *) [with T=Kokkos::complex<double>]"
<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_10_gcc_740_kepler/ws/kokkos/core/unit_test/TestAtomic.hpp(256)>: here
            instantiation of "void TestAtomic::CASFunctor<T, DEVICE_TYPE>::operator()(int) const [with T=Kokkos::complex<double>, DEVICE_TYPE=Kokkos::Cuda]"
<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_10_gcc_740_kepler/ws/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(586)>: here
            [ 4 instantiation contexts not shown ]
...
```

Power8 + Kepler arches
cuda/9.2 + gcc/7.2 or xl/16.1
cuda/10.0.130 +gcc/7.4.0

**Comment by jjwilke** [comment]
PR #2558 allows the user to force libatomic to be linked.  Do we want a minimal compile test to be added to the build system so the TPL gets automatically added? And if so, what would a minimal reproducer be?

**Comment by dalg24** [comment]
I just realized I only link For GCC 48.4 and forgot to deal with 4.9.3

**Comment by masterleinad** [comment]
> PR #2558 allows the user to force libatomic to be linked. Do we want a minimal compile test to be added to the build system so the TPL gets automatically added? And if so, what would a minimal reproducer be?

I think something like that would be a good idea but we don't have a minimal reproducer yet.  We only see linking `KokkosCore_UnitTest_OpenMP.dir/openmp/TestOpenMP_Atomics.cpp` failing.

**Comment by dalg24** [comment]
> cuda/9.2 + gcc/7.2 or xl/16.1
> cuda/10.0.130 +gcc/7.4.0

These failures are unexpected.  Any idea?

**Comment by ndellingwood** [comment]
> Any idea?

I'm not certain, but looking at PR #2557 it looks like @crtrott encountered this and pushed fixes in commit c82ebc0fdba499677d7f7ba20f22801c6972456f , apparently a `volatile` was missing?

**Comment by ndellingwood** [comment]
PRs #2557 #2558 and #2559 address various aspects of this issue.
