### PR TITLE
SIMD: Replace unavailable loadu/storeu instructions

### LINKED ISSUE #6182: Nightly test failures, gcc/8.2,9.2, SKX arch, debug build: error: ‘_mm512_loadu_epi64’ was not declared in this scope
**Describe the bug**
Nightly tests began failing to compile in gcc/8.2,9.2, SKX arch, debug builds following merge of these commits:

Remove extended_namespace template paramter for SYCLMemoryOrder/Scope ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/266/changes#e832781a3f03332b954a6ee908c3ab933b098583) / [githubweb](https://github.com/kokkos/kokkos/commit/e832781a3f03332b954a6ee908c3ab933b098583))
    Cherry-pick v3.7.02 changelog into develop [ci skip] ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/266/changes#1af1379994e0f23f213bd7d9caeae18a2a2272c9) / [githubweb](https://github.com/kokkos/kokkos/commit/1af1379994e0f23f213bd7d9caeae18a2a2272c9))
    Kokkos: Mark HWLOC as a TriBITS TPL as well (trilinos/Trilinos#11938) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/266/changes#9df5a01a80509c63b14c1c68e1b1aec989159797) / [githubweb](https://github.com/kokkos/kokkos/commit/9df5a01a80509c63b14c1c68e1b1aec989159797))
    SIMD: make binary op tests to test against all data types (#5913) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/266/changes#915c1746696180a8d4e569e60eecef9aaceaa5f8) / [githubweb](https://github.com/kokkos/kokkos/commit/915c1746696180a8d4e569e60eecef9aaceaa5f8))
    Also create symlinks for CMake configuration files to cmake_packages/Kokkos for TriBITS (#6163) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/266/changes#65ffe4c5d94d83555c565ffa27a1616a3d71b009) / [githubweb](https://github.com/kokkos/kokkos/commit/65ffe4c5d94d83555c565ffa27a1616a3d71b009))
    Allow passing a temporary std::vector to partition_space (#6167) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/266/changes#0b7bed5817a7c095df9d8d8409e00d3a4f61fb1b) / [githubweb](https://github.com/kokkos/kokkos/commit/0b7bed5817a7c095df9d8d8409e00d3a4f61fb1b))

**Error message**:
```
01:26:06 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp:391:15: error: ‘_mm512_loadu_epi64’ was not declared in this scope
01:26:06      m_value = _mm512_loadu_epi64(ptr);
01:26:06                ^~~~~~~~~~~~~~~~~~
01:26:06 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp:391:15: note: suggested alternative: ‘_mm512_load_epi64’
01:26:06      m_value = _mm512_loadu_epi64(ptr);
01:26:06                ^~~~~~~~~~~~~~~~~~
01:26:06                _mm512_load_epi64
01:26:06 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp: In member function ‘void Kokkos::Experimental::simd<long int, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> >::copy_to(Kokkos::Experimental::simd<long int, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> >::value_type*, Kokkos::Experimental::element_aligned_tag) const’:
01:26:06 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp:395:5: error: ‘_mm512_storeu_epi64’ was not declared in this scope
01:26:06      _mm512_storeu_epi64(ptr, m_value);
01:26:06      ^~~~~~~~~~~~~~~~~~~
01:26:06 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp:395:5: note: suggested alternative: ‘_mm512_store_epi64’
01:26:06      _mm512_storeu_epi64(ptr, m_value);
01:26:06      ^~~~~~~~~~~~~~~~~~~
01:26:06      _mm512_store_epi64
01:26:06 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp: In member function ‘void Kokkos::Experimental::simd<long unsigned int, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> >::copy_from(const value_type*, Kokkos::Experimental::element_aligned_tag)’:
01:26:06 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp:522:15: error: ‘_mm512_loadu_epi64’ was not declared in this scope
01:26:06      m_value = _mm512_loadu_epi64(ptr);
01:26:06                ^~~~~~~~~~~~~~~~~~
01:26:06 [ 93%] Building CXX object algorithms/unit_tests/CMakeFiles/Kokkos_AlgorithmsUnitTest_StdSet_C.dir/TestStdAlgorithmsFindEnd.cpp.o
```

**Please also include the following items to support reproducing the bug**
**Reproducer** (Blake testbed):
```bash
module load cmake/3.19.3 gcc/8.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial --arch=SKX --compiler=g++ --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --no-examples   --with-options=enable_large_mem_tests --debug
```

### PR DESCRIPTION
**Pull request by ldh4**
Resolves #6182.

`_mm512_loadu_epi64` and `_mm512_storeu_epi64` became available in `gcc/avx512fintrin.h` starting GCC 10. Compiling with previous versions of gcc causes undeclared errors on these.

This PR replaces `_mm512_loadu_epi64` with `_mm512_loadu_si512` and `_mm512_storeu_epi64` with `_mm512_storeu_si512`. 
Functionally, both replaced and replacing calls operate on 512 bits of memory that are not expected to be aligned in any boundary.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Comment by dalg24** [comment]
Is it preferable to unconditionally use `_mm512_loadu_si512` or to guard for the version of GCC?

**Comment by ldh4** [comment]
> Is it preferable to unconditionally use `_mm512_loadu_si512` or to guard for the version of GCC?

I think unconditional use of `_mm512_loadu_si512` is ok. Looking at the intel intrinsics guide, there are no differences in  [_mm512_loadu_epi64](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#techs=AVX_512&text=_mm512_loadu_epi64&ig_expand=5932,4637,705,707,4861,4870,702,5927,7193,355,4027,4027,4107,4107,4107,4107) and [_mm512_loadu_si512](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#techs=AVX_512&text=_mm512_loadu_si&ig_expand=5932,4637,705,707,4861,4870,702,5927,7193,355,4027,4107,4027,4107,4144,4065,4144,4144](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#techs=AVX_512&text=_mm512_loadu_si512&ig_expand=5932,4637,705,707,4861,4870,702,5927,7193,355,4027,4107,4027,4107,4144,4065,4144,4144,4144)) in their instructions and operations.

Trying out in [godbolt](https://godbolt.org/z/aWPd6Yx6s) also produces same instructions for calling these intrinsics.

**Review by dalg24 — APPROVED** [review]

**Comment by ndellingwood** [comment]
CI failure in OPENACC-NVHPC-CUDA-11.6 build due to out-of-disk space error, unrelated to PR
`Disk quota exceeded`
