### PR TITLE
Fix typo in cuda_func_set_attribute[s]_wrapper

### LINKED ISSUE #6780: CUDA occupancy compilation error with Kokkos 4.2
**Describe the bug**

Setting occupancy seems to be broken in Kokkos 4.2 for the code that worked in Kokkos 4.1

**Please include the following for a minimal reproducer**

The following code worked in Kokkos 4.1 with Cuda but is broken in 4.2:
```c++
#include <Kokkos_Core.hpp>
int main(int argc, char *argv[]) {
  Kokkos::ScopeGuard guard(argc, argv);
  using ExecutionSpace = Kokkos::Cuda;
  Kokkos::parallel_for("blah",
    Kokkos::Experimental::prefer(
      Kokkos::RangePolicy<ExecutionSpace>(ExecutionSpace{}, 0, 10),
      Kokkos::Experimental::DesiredOccupancy{75}),
    KOKKOS_LAMBDA(int) {/* do nothing */}
  );
  return 0;
}
```
Using nvcc/11.5 with 4.1.00 and 4.2.00.

The error message is
```
kokkos-4.2.0/include/Cuda/Kokkos_Cuda_Instance.hpp(512): error:
  identifier "cudaFuncSetAttributes" is undefined
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #6780. https://github.com/kokkos/kokkos/commit/4d8629f26c introduced `cuda_func_set_attributes_wrapper` which should have been `cuda_func_set_attribute_wrapper` and mapping to `cudaFuncSetAttribute` instead of `cudaFuncSetAttributes`. Our CI didn't detect that typo since we were never executing a kernel with `DesiredOccupancy`.
This pull request fixes that. The test was changed to not use default constructed policies since that created problems with `MDRange` (division by zero) and this test isn't designed to test that. Whether default constructed policy instances should be usable or not is a separate question and out-of-scope for this pull request.

### CODE REVIEW

**Review by crtrott — CHANGES_REQUESTED** [review]
Windows CUDA build failed with a compile error

File: core/unit_test/TestCommonPolicyConstructors.hpp
Comment (dalg24) [inline core/unit_test/TestCommonPolicyConstructors.hpp:1]: This test is about constructing policies so I don't think that executing a kernel belongs here.
Did you consider other places to add the test?

Comment (tcclevenger) [reply core/unit_test/TestCommonPolicyConstructors.hpp:1]: I agree. Maybe these fit better in the TestTeam/TestRange/TestMDRange unit tests? For instance, `TestRange.hpp:test_for()` function could add a policy with desired occupancy conversion run a do-nothing parallel_for(). 

But it is a bit annoying that each policy would need its own test, and adds a lot more code than what is here..

Comment (masterleinad) [reply core/unit_test/TestCommonPolicyConstructors.hpp:1]: To me, this looked like the best place to check that the constructed policies are actually usable but I'm fine to move/copy the test somewhere else if desired.

Comment (dalg24) [reply core/unit_test/TestCommonPolicyConstructors.hpp:1]: Find a better place plz.

File: core/unit_test/TestOccupancyControlTrait.hpp [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+
+  // DesiredOccupancy -> MaximizeOccupancy
+  auto const policy_drop_occ =
+      prefer(policy_with_occ_and_hint, MaximizeOccupancy{});
+  test_policy_execution(policy_drop_occ);
+}
+
+// FIXME_MSVC_WITH_CUDA
+// This test doesn't compile with CUDA on Windows
+#if !(defined(_WIN32) && defined(KOKKOS_ENABLE_CUDA))
```
Comment (dalg24) [inline core/unit_test/TestOccupancyControlTrait.hpp:82]: Does not compile when dispatching to the host execution space as well?

Comment (masterleinad) [reply core/unit_test/TestOccupancyControlTrait.hpp]: Let's give it a shot.

File: core/unit_test/TestOccupancyControlTrait.hpp [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+  auto const policy_drop_occ =
+      prefer(policy_with_occ_and_hint, MaximizeOccupancy{});
+  test_policy_execution(policy_drop_occ);
+}
+
+TEST(TEST_CATEGORY, occupancy_control) {
+// FIXME_MSVC_WITH_CUDA
+// This test doesn't compile with CUDA on Windows
+#if defined(_WIN32) && defined(KOKKOS_ENABLE_CUDA)
+  if constexpr (!std::is_same_v<TEST_EXECSPACE, Kokkos::Cuda>)
```
Comment (dalg24) [inline core/unit_test/TestOccupancyControlTrait.hpp:84]: Please use `GTEST_SKIP << "reason"  // FIXME_SOMETHING;`

Comment (masterleinad) [reply core/unit_test/TestOccupancyControlTrait.hpp:84]: It's not working anyway.

File: core/unit_test/TestCommonPolicyConstructors.hpp [hunk 3]
```diff
@@ -87,7 +84,7 @@ void test_prefer_desired_occupancy() {
       !decltype(policy_drop_occ)::experimental_contains_desired_occupancy);
 }
 
-TEST(TEST_CATEGORY, execution_policy_occupancy_and_hint) {
+[[maybe_unused]] void test_execution_policy_occupancy_and_hint() {
```
Comment (dalg24) [inline core/unit_test/TestCommonPolicyConstructors.hpp:87]: Why did you change this and removed the assertions above?

Comment (masterleinad) [reply core/unit_test/TestCommonPolicyConstructors.hpp:87]: So this can all be compile-time checks. I moved the runtime checks to the new test.

File: core/unit_test/TestOccupancyControlTrait.hpp [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+      policy,
+      KOKKOS_LAMBDA(
+          const typename Kokkos::TeamPolicy<Properties...>::member_type&){});
+}
+template <class... Properties>
+void test_policy_execution(const Kokkos::MDRangePolicy<Properties...>& policy) {
+  Kokkos::parallel_for(policy, KOKKOS_LAMBDA(int, int){});
+}
+template <class... Properties>
+void test_policy_execution(const DummyPolicy<Properties...>&) {}
```
Comment (dalg24) [inline core/unit_test/TestOccupancyControlTrait.hpp:43]: What is the point of having DummyPolicy in this test?

File: core/unit_test/TestOccupancyControlTrait.hpp [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+      prefer(policy_with_occ_and_hint, MaximizeOccupancy{});
+  test_policy_execution(policy_drop_occ);
+}
+
+// FIXME_MSVC_WITH_CUDA
+// This test doesn't compile with CUDA on Windows
+#if !(defined(_WIN32) && defined(KOKKOS_ENABLE_CUDA))
+TEST(TEST_CATEGORY, occupancy_control) {
+  test_prefer_desired_occupancy(DummyPolicy<TEST_EXECSPACE>{});
+  test_prefer_desired_occupancy(Kokkos::RangePolicy<TEST_EXECSPACE>(0, 0));
```
Comment (dalg24) [inline core/unit_test/TestOccupancyControlTrait.hpp:85]: Wouldn't we want to actually dispatch a kernel and not have empty ranges?

Comment (masterleinad) [reply core/unit_test/TestOccupancyControlTrait.hpp:85]: I don't have much of a preference but am happy to extend to a non-trivial range. The current version caught the original issue.

File: core/unit_test/TestOccupancyControlTrait.hpp (hunk 4 above)
Comment (masterleinad) [reply core/unit_test/TestOccupancyControlTrait.hpp:43]: Only to keep the runtime test I moved here.

File: core/unit_test/TestCommonPolicyConstructors.hpp (hunk 3 above)
Comment (dalg24) [reply core/unit_test/TestCommonPolicyConstructors.hpp:87]: Undo all changes to that file

**Review by dalg24 — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Comment by crtrott** [comment]
I did not figure out why the windows thing failed so far. A more exhaustive Linux tests did not expose any issues:

```c++
#include<Kokkos_Core.hpp>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc, argv);
  {
    Kokkos::RangePolicy<> a(0,5);
    auto b = Kokkos::Experimental::prefer(a, Kokkos::Experimental::DesiredOccupancy{30});
    auto c = Kokkos::Experimental::require(b, Kokkos::Experimental::WorkItemProperty::HintLightWeight);

    auto d = Kokkos::Experimental::require(a, Kokkos::Experimental::WorkItemProperty::HintLightWeight);
    auto e = Kokkos::Experimental::prefer(d, Kokkos::Experimental::DesiredOccupancy{30});


    printf("%s\n",typeid(decltype(a)).name());
    printf("%s\n",typeid(decltype(b)).name());
    printf("%s %i\n",typeid(decltype(c)).name(), (int) c.impl_get_desired_occupancy());
    printf("%s\n",typeid(decltype(d)).name());
    printf("%s %i\n",typeid(decltype(e)).name(), (int) e.impl_get_desired_occupancy());
    {
      printf("\n");
      using p1_t = Kokkos::MDRangePolicy<Kokkos::Experimental::DesiredOccupancy, Kokkos::Rank<2>>;
      using p2_t = Kokkos::MDRangePolicy<Kokkos::Rank<2>, Kokkos::Experimental::DesiredOccupancy>;
      printf("%s\n",typeid(p1_t).name());
      printf("%s\n",typeid(p2_t).name());
    }
    {
      printf("\n");
      using p1_t = Kokkos::RangePolicy<Kokkos::Experimental::DesiredOccupancy, Kokkos::IndexType<char>>;
      using p2_t = Kokkos::RangePolicy<Kokkos::IndexType<char>, Kokkos::Experimental::DesiredOccupancy>;
      printf("%s %s\n",typeid(p1_t).name(), typeid(typename p1_t::member_type).name());
      printf("%s %s\n",typeid(p2_t).name(), typeid(typename p1_t::member_type).name());
    }
  }
  Kokkos::finalize();
}
```

prints (with c++filt -t):
```
Kokkos::RangePolicy<>
Kokkos::RangePolicy<Kokkos::Experimental::DesiredOccupancy>
Kokkos::RangePolicy<Kokkos::Experimental::DesiredOccupancy, Kokkos::Experimental::WorkItemProperty::ImplWorkItemProperty<1ul> > 30
Kokkos::RangePolicy<Kokkos::Experimental::WorkItemProperty::ImplWorkItemProperty<1ul> >
Kokkos::RangePolicy<Kokkos::Experimental::WorkItemProperty::ImplWorkItemProperty<1ul>, Kokkos::Experimental::DesiredOccupancy> 30

Kokkos::MDRangePolicy<Kokkos::Experimental::DesiredOccupancy, Kokkos::Rank<2u, (Kokkos::Iterate)0, (Kokkos::Iterate)0> >
Kokkos::MDRangePolicy<Kokkos::Rank<2u, (Kokkos::Iterate)0, (Kokkos::Iterate)0>, Kokkos::Experimental::DesiredOccupancy>

Kokkos::RangePolicy<Kokkos::Experimental::DesiredOccupancy, Kokkos::IndexType<char> > char
Kokkos::RangePolicy<Kokkos::IndexType<char>, Kokkos::Experimental::DesiredOccupancy> char
```

I.e. everything seems fine.

**Comment by aprokop** [comment]
Should it be cherry-picked to 4.2.1?

**Comment by masterleinad** [comment]
> Should it be cherry-picked to 4.2.1?

We decided against it. Candidate for 4.2.2.
