### ISSUE TITLE
AtomicsUpdate Issues: track all the stuff which needs to be fixed or is fixed

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1689]
This for now is all for an OpenMP build with sems-gcc/5.3.0

* ~Missing typeinfo include in Kokkos_ExecPolicy.hpp~ done by crtrott
* ~Cast away const from ptr on volatile_load~ done by crtrott
  * ~atomic_load is used inside which doesn't support const T*~
* ~Sems GCC 5.3.0: undefined reference to __atomic_compare_exchange_16~ done by crtrott
  * ~looks like this can be fixed by adding -mcx16 to CXXFLAGS and LDFLAGS~
* ~ExaMiniMD build for OpenMP doesn't seem to do atomics somewhere~
  * ~compile with: `make -f ../src/Makefile KOKKOS_PATH=/home/crtrott/Kokkos/kokkos KOKKOS_ARCH=SNB,Volta70 KOKKOS_DEVICES=OpenMP -j`~
  * ~run with `mpirun -np 4 -map-by socket:PE=6 ./ExaMiniMD.omp_old_atomic -il ../input/in.lj --force-iteration NEIGH_HALF`~
* ~Warnings break -Werror build~
  * ~`/home/crtrott/Kokkos/kokkos/core/src/atomic/Kokkos_Atomic_GNU.hpp:231:10: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]`~
* ~Linker needs -latomic~ done by crtrott
* ~most of the openmp.atomic_* tests hang~ done by crtrott
  * ~they hang because there is not actual implementation of atomic_fetch_max, thus the deprecated function (with the volatile overload) ends up calling itself in an infinite loop~ done by crtrott
  * ~atomic_increment and decrement don't exist either ..~ done by crtrott
  * ~atomic_mul_fetch simple is missing~ done by crtrott
  * ~atomic_compare_exchange returns the wrong value (returns new value instead of old)~ done by crtrott
* ~Tests fail:~ fixed by crtrott
  * ~[  FAILED  ] 6 tests, listed below:~
  * ~[  FAILED  ] openmp.team_long_reduce~
  * ~[  FAILED  ] openmp.team_double_reduce~
  * ~[  FAILED  ] openmp.team_reduce~
  * ~[  FAILED  ] openmp.range_for~
  * ~[  FAILED  ] openmp.range_reduce~
  * ~[  FAILED  ] openmp.range_scan~
  * ~root cause: wrong atomic_compare_exchange behavior, not diagnosed by atomic unit test~

**Comment by crtrott** [comment]
Cuda,OpenMP,ROCm atomics don't exist ...
