### ISSUE TITLE
cuda/9.2 compilation errors: more than one conversion function from "Kokkos::Experimental::half_t::impl_type" to a built-in type

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#3561]
Nightly Kokkos and Kokkos+Kernels+Tpetra+Sacado Trilinos cuda/9.2 tests began failing at compilation following merge of #3439. This is occurring on kokkos-dev (builds using gcc/6.1 as host compiler), but the failure does not show up in cuda/9.2 builds on white using gcc/7.2.0 as the host compiler.

https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_cuda_92/36/consoleFull
https://jenkins-son.sandia.gov/view/Kokkos/job/Kokkos_develop_kokkos-dev_cuda_92-dbg-boundscheck/36/consoleFull
https://jenkins-son.sandia.gov/job/KokkosKernels_Trilinos_TpetraCore_Sacado_KokkosDev_CUDA92_opt/changes

Error message
```bash
06:02:37 /home/jenkins/slave/workspace/Kokkos_develop_kokkos-dev_cuda_92/kokkos/core/src/Cuda/Kokkos_Cuda_Half.hpp(206): error: more than one conversion function from "Kokkos::Experimental::half_t::impl_type" to a built-in type applies:
06:02:37             function "__half::operator float() const"
06:02:37             function "__half::operator short() const"
06:02:37             function "__half::operator unsigned short() const"
06:02:37             function "__half::operator int() const"
06:02:37             function "__half::operator unsigned int() const"
06:02:37             function "__half::operator long long() const"
06:02:37             function "__half::operator unsigned long long() const"
06:02:37             function "__half::operator __nv_bool() const"

06:02:37 /home/jenkins/slave/workspace/Kokkos_develop_kokkos-dev_cuda_92/kokkos/core/src/Cuda/Kokkos_Cuda_Half.hpp(217): error: more than one conversion function from "Kokkos::Experimental::half_t::impl_type" to a built-in type applies:
06:02:37             function "__half::operator float() const"
06:02:37             function "__half::operator short() const"
06:02:37             function "__half::operator unsigned short() const"
06:02:37             function "__half::operator int() const"
06:02:37             function "__half::operator unsigned int() const"
06:02:37             function "__half::operator long long() const"
06:02:37             function "__half::operator unsigned long long() const"
06:02:37             function "__half::operator __nv_bool() const"
...
```

Reproducer:
```bash
module load sems-env sems-cmake/3.12.2 sems-cuda/9.2 sems-gcc/6.1.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,OpenMP --arch=Kepler35 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --with-cuda --kokkos-path=$KOKKOS_PATH --no-examples --with-options=enable_large_mem_tests
```

**Comment by ndellingwood** [comment]
Referencing PR #3563

**Comment by ndellingwood** [comment]
Addressed by #3563 and #3571

**Comment by Char-Aznable** [comment]
@ndellingwood I am still seeing this error in the latest Kokkos ( cac5a078 ) and Kokkos-Kernels (9e338ef9) built with nvcc 11.1.74

**Comment by Char-Aznable** [comment]
This error didn't occur in 565a5203a30ccb0d5524ee70d0b5340bc48c9af0 so it must be introduced between 565a5203a30ccb0d5524ee70d0b5340bc48c9af0 and cac5a07

**Comment by ndellingwood** [comment]
Additional fixes in PR #3587

**Comment by jjaraalm** [comment]
I ran into this issue on a different project using gcc 7.3.1, nvcc 10.2, and 6d65b5a3a1a48c43312a4f35f4eea367f59ec554. It otherwise builds fine using Kokkos 3.1.00.

**Comment by DavidPoliakoff** [comment]
Adding my name to the list of people hitting this. NVCC 10.1, gcc 7.3.0

**Comment by DavidPoliakoff** [comment]
For reference, my problem involved a screwup (on my part) in a build system. I wound up not passing the correct architecture flag to a file that included Kokkos.

**Comment by rfbird** [comment]
Like @DavidPoliakoff, I was running into this in a situation where I was using missmatched defines for different translation units, for me it was a define (`-DKokkos_ENABLE_CUDA`, specifically)

**Comment by ibaned** [comment]
Yep, this is happening to me right now trying to compile with Kokkos master...

**Comment by ibaned** [comment]
Could we clarify what is needed exactly to resolve this?

**Comment by ibaned** [comment]
Looks like ensuring `-arch=sm_70` or similar is in the arguments might be the key. This is a fairly obscure failure mode...

**Comment by rfbird** [comment]
@ibaned  is this:

https://github.com/kokkos/kokkos/blob/master/core/src/Cuda/Kokkos_Cuda_Half.hpp#L51 

missing Ampere specific checks? I was able to fix this issue on Turing but Ampere (A100) still barfs

**Comment by ibaned** [comment]
@rfbird I don't know, I'm not familiar with that part of the code. I'm more or less in the same boat as you working around it as a user.

**Comment by ibaned** [comment]
A little bit more explanation on my failure case: I was using the modern CMake support for CUDA, but Kokkos reinvented that wheel and the two systems are not compatible. When using Kokkos now I *don't* mark my source files as language CUDA in CMake anymore.

**Comment by pvelesko** [comment]
> Looks like ensuring `-arch=sm_70` or similar is in the arguments might be the key. This is a fairly obscure failure mode...

I ran into this error as well, added a `-arch=sm_75` to my code that includes Kokkos and the issue was resolved. I am using `nvcc_wrapper` provided by Kokkos. Shouldn't it take care of this?

**Comment by masterleinad** [comment]
> I ran into this error as well, added a `-arch=sm_75` to my code that includes Kokkos and the issue was resolved. I am using `nvcc_wrapper` provided by Kokkos. Shouldn't it take care of this?

How are you linking to `Kokkos`? If you use `CMake`, the flag should be enforced by `Kokkos` already. `nvcc_wrapper` itself doesn't add any flags, though.

**Comment by pvelesko** [comment]
@masterleinad  I was using Make. I thought nvcc_wrapper would add things like that. Using CMake now without having to add anything.

**Comment by jrobcary** [comment]
Seeing this error also.  gcc-9.4.0, cuda-11.5.  My flags include 

`-gencode=arch=compute_75,code=sm_75`

**Comment by mschmidt271** [comment]
Also getting the same error with kokkos-3.4.01 with gcc-7.5.0, cuda-11.5, and providing `-DKokkos_ARCH_TURING75=ON`.

Like @pvelesko, I was able to successfully build after providing `-arch=sm_75` as a top-level `CMAKE_CXX_FLAGS`.

**Comment by jrobcary** [comment]
BTW, we are able to build Trilinos.  Not able to build a package using it.
