### PR TITLE
Workaround compiler bug in definition of `reciprocal_overflow_threshold`

### LINKED ISSUE #4485: Nightly build failure with gcc on Power9+Volta70 in Kokkos_NumericTraits with constexpr T Kokkos::Experimental::Impl::safe_minimum: error: is not a constant expression
Various nightly builds with cuda/9.2 and cuda/10.{0,1} and/or gcc/6 or gcc/7.2 on Power9 + Volta are failing in Kokkos_NumericTraits with apparent issues handling `long double` in constexpr usage:

**Sample output snip**
```
04:14:38 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_cuda_9288_gcc_720_volta-dbg/kokkos/core/src/Kokkos_NumericTraits.hpp: In instantiation of ‘constexpr T Kokkos::Experimental::Impl::safe_minimum(T) [with T = long double]’:
04:14:38 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_cuda_9288_gcc_720_volta-dbg/kokkos/core/src/Kokkos_NumericTraits.hpp:151:122:   required from here
04:14:38 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_cuda_9288_gcc_720_volta-dbg/kokkos/core/src/Kokkos_NumericTraits.hpp:145:29: error: ‘(1.0e+0l / 1.79769313486231570800000000000001e+308l)’ is not a constant expression
04:14:38    constexpr auto small = one / huge;
```

**Sample reproducer** (cuda/9.2+gcc/7.2 Cuda_Serial debug build):
```
module load cmake/3.19.3 cuda/9.2.88 gcc/7.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=Power9,Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --with-cuda-options=enable_lambda  --no-examples --with-options=enable_large_mem_tests --debug
```

This is following merge of #4473 @dalg24 are you able to take a look?

Edit: This seems to be more specifically an issue with gcc, not just with the cuda builds

### PR DESCRIPTION
**Pull request by dalg24**
Fix #4485 (`1 / norm_min_v<T>` cannot be evaluated at compile time)
Giving up and aliasing `reciprocal_overflow_threshold` to `norm_min` which is fine for IEEE-754 floating-point types

cc @mhoemmen

### CODE REVIEW

File: core/unit_test/TestNumericTraits.hpp [hunk 1]
```diff
@@ -161,6 +161,13 @@ struct TestNumericTraits {
       printf("inverse of reciprocal overflow threshold is inf\n");
       ++e;
     }
+    using Kokkos::Experimental::epsilon;
+    auto const fpo =
+        1 / (reciprocal_overflow_threshold<T>::value * (1 - epsilon<T>::value));
+    if (fpo + fpo != fpo) {
+      printf("inverse of fp smaller than threshold does not overflow\n");
+      ++e;
+    }
```
Comment (dalg24) [inline core/unit_test/TestNumericTraits.hpp:170]: withdrawing additional assertion...

File: core/src/Kokkos_NumericTraits.hpp [hunk 2]
```diff
@@ -135,20 +135,32 @@ template <> struct denorm_min_helper<float> { static constexpr float value = __F
 template <> struct denorm_min_helper<double> { static constexpr double value = __DBL_DENORM_MIN__; };
 template <> struct denorm_min_helper<long double> { static constexpr long double value = __LDBL_DENORM_MIN__; };
 #endif
+// GCC <10.3 is not able to evaluate T(1) / norm_min<T>::value at compile time when passing -frounding-math
+// https://godbolt.org/z/zj9svb1T7
+// Similar issue was reported on IBM Power without the compiler option
+#define KOKKOS_IMPL_WORKAROUND_CONSTANT_EXPRESSION_COMPILER_BUG
```
Comment (mhoemmen) [inline core/src/Kokkos_NumericTraits.hpp:141]: Do we need to add an `#ifndef KOKKOS_IMPL_WORKAROUND_CONSTANT_EXPRESSION_COMPILER_BUG` above this line?  Not sure what the convention is in Kokkos for using that macro.

File: core/src/Kokkos_NumericTraits.hpp [hunk 3]
```diff
@@ -135,20 +135,32 @@ template <> struct denorm_min_helper<float> { static constexpr float value = __F
...
-  constexpr auto one   = static_cast<T>(1);
-  constexpr auto eps   = epsilon_helper<T>::value;
-  constexpr auto tiny  = norm_min_helper<T>::value;
-  constexpr auto huge  = finite_max_helper<T>::value;
-  constexpr auto small = one / huge;
+  constexpr auto one  = static_cast<T>(1);
+  constexpr auto eps  = epsilon_helper<T>::value;
+  constexpr auto tiny = norm_min_helper<T>::value;
+  constexpr auto huge = finite_max_helper<T>::value;
+  constexpr auto small = one / huge;  // error: is not a constant expression
```
Comment (mhoemmen) [inline core/src/Kokkos_NumericTraits.hpp:150]: Alas, C++ doesn't have conditional `constexpr` yet.

**Review by mhoemmen — APPROVED** [review]

File: core/src/Kokkos_NumericTraits.hpp (hunk 3 above)
Comment (dalg24) [reply core/src/Kokkos_NumericTraits.hpp:150]: No and that would not help if it did

File: core/src/Kokkos_NumericTraits.hpp (hunk 2 above)
Comment (dalg24) [reply core/src/Kokkos_NumericTraits.hpp:141]: No it is only meant for local use.  I might as well have commented the code below.

**Review by nliber — APPROVED** [review]

File: core/src/Kokkos_NumericTraits.hpp [hunk 4]
```diff
@@ -135,20 +135,32 @@ template <> struct denorm_min_helper<float> { static constexpr float value = __F
 template <> struct denorm_min_helper<double> { static constexpr double value = __DBL_DENORM_MIN__; };
 template <> struct denorm_min_helper<long double> { static constexpr long double value = __LDBL_DENORM_MIN__; };
 #endif
+// GCC <10.3 is not able to evaluate T(1) / norm_min<T>::value at compile time when passing -frounding-math
```
Comment (dalg24) [inline core/src/Kokkos_NumericTraits.hpp:138]: I meant `1 / finite_max_v<T>`

**Comment by dalg24** [comment]
Failure (performance test) is unrelated
