### ISSUE TITLE
Nightly test failure, intel/2021.3 icpc (intel classic) -Werror: Kokkos_CopyViews.hpp(3498): error #1011: missing return statement at end of non-void function

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7031]
**Describe the bug**

Nightly builds with intel/2021.3 using the intel classic compiler icpc are hitting the following warning triggering -Werror failures:
```
20:40:39 /home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/src/Kokkos_CopyViews.hpp(3498): error #1011: missing return statement at end of non-void function "Kokkos::Impl::create_mirror(const Kokkos::View<T, P...> &, const Kokkos::Impl::ViewCtorProp<ViewCtorArgs...> &) [with T=int *, P=<Kokkos::DefaultExecutionSpace>, ViewCtorArgs=<Kokkos::Impl::WithoutInitializing_t>]"
20:40:39   }
20:40:39   ^
20:40:39           detected during:
20:40:39             instantiation of "auto Kokkos::Impl::create_mirror(const Kokkos::View<T, P...> &, const Kokkos::Impl::ViewCtorProp<ViewCtorArgs...> &) [with T=int *, P=<Kokkos::DefaultExecutionSpace>, ViewCtorArgs=<Kokkos::Impl::WithoutInitializing_t>]" at line 3513
20:40:39             instantiation of "std::enable_if_t<std::is_void<Kokkos::ViewTraits<T, P...>::specialize>::value, Kokkos::View<T, P...>::HostMirror> Kokkos::create_mirror(Kokkos::Impl::WithoutInitializing_t, const Kokkos::View<T, P...> &) [with T=int *, P=<Kokkos::DefaultExecutionSpace>]" at line 40 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/unit_test/TestCreateMirror.cpp"
20:40:39             instantiation of "void test_create_mirror_properties(const View &) [with View=Kokkos::View<int *, Kokkos::DefaultExecutionSpace>]" at line 95 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_2021_3_openmp_pthread_serial/kokkos/core/unit_test/TestCreateMirror.cpp"
```

This began after merge of the following commits
**Changes:
    Test DualView resize/realloc for types without default constructor — [arndtd](https://jenkins-son.sandia.gov/user/arndtd/) / [githubweb](https://github.com/kokkos/kokkos/commit/cadab6c1ed26cfef885fdb29c6d3eace98862f3e)
    Use parallel_for instead of parallel_reduce for check — [arndtd](https://jenkins-son.sandia.gov/user/arndtd/) / [githubweb](https://github.com/kokkos/kokkos/commit/2b7b98a1a6e9138389813c6e4115672459f02195)
    Refactor: Replace SFINAE by `if constexpr` for `create_mirror*` functions (#6955) — [github](https://jenkins-son.sandia.gov/user/github/) / [githubweb](https://github.com/kokkos/kokkos/commit/0410363d77b78d32937a8b77e01c8373cf90230d)**:

**Please include the following for a minimal reproducer**

**Reproducer** (Blake all queue):
```bash
module load sems-cmake sems-intel/2021.3

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --ldflags=""  --kokkos-path=$KOKKOS_PATH  --no-examples   --with-options=enable_large_mem_tests
```

**Comment by dalg24** [comment]
Please try
```diff
diff --git a/core/src/Kokkos_CopyViews.hpp b/core/src/Kokkos_CopyViews.hpp
index 7dce03c71..9ff8041f4 100644
--- a/core/src/Kokkos_CopyViews.hpp
+++ b/core/src/Kokkos_CopyViews.hpp
@@ -3495,6 +3495,9 @@ inline auto create_mirror(const Kokkos::View<T, P...>& src,
     using dst_type = typename View<T, P...>::HostMirror;
     return dst_type(prop_copy, src.layout());
   }
+#if defined KOKKOS_COMPILER_INTEL
+  __builtin_unreachable();
+#endif
 }
 }  // namespace Impl

**Comment by ndellingwood** [comment]
@dalg24 thanks, I had to apply your suggestion in a few extra places and it resolved the warnings

**Comment by ndellingwood** [comment]
PR #7034 up with the workarounds
