### ISSUE TITLE
gcc/9.2 compilation -Werror with c++20 standard: kokkos/core/unit_test/TestGraph.hpp:121:58: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#3476]
Nightly builds began failing due to `Werror` after merge of PR #3362 with gcc/9.2 with all backends and c++20 standard 

**Sample error message** (multiple occurrences):
```bash
kokkos/core/unit_test/TestGraph.hpp:121:58: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
```

**Sample reproducer** (serial case)
```bash
module load sems-env sems-cmake/3.12.2 sems-gcc/9.2.0

# Via generate_makefile
$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial --arch=SNB,Volta70 --compiler=g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="20"  --kokkos-path=$KOKKOS_PATH --no-examples

# Corresponding cmake line
cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_VOLTA70=ON -DKokkos_ARCH_SNB=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH

```

**Comment by ndellingwood** [comment]
I put in a PR #3477 with the minimal change of capturing "this" in the lambdas where the -Werror was thrown, I can close it PR if something more substantial is required

**Comment by dhollman** [comment]
See #3485 for probably the simplest fix. We should actually be testing this anyway (assuming we want to support both, which for an immediately-invoked lambda seems reasonable), since the `[&]` has a non-`const` call operator, which is more restrictive in terms of where it can be called than the `[=]` which has a `const` one.
