### ISSUE TITLE
Nightly build error: gcc/7.2,8.2 builds with SKX arch, Kokkos_SIMD_AVX512.hpp:680:22: error: ‘_mm512_cmplt_pd_mask’ was not declared in this scope

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5313]
**Describe the bug**
Following the change to require c++17, nightly builds with gcc/7.2, 8.2 for SKX architecture began failing to compile with output:
```
In file included from /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD.hpp:53,
                 from /home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/unit_tests/TestSIMD.cpp:47:
/home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp: In member function ‘Kokkos::Experimental::simd<double, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> >::mask_type Kokkos::Experimental::simd<double, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> >::operator<(const Kokkos::Experimental::simd<double, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> >&) const’:
/home/jenkins/blake-new/workspace/Kokkos_develop_blake_gcc_openmp_pthread_serial_820/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp:680:22: error: ‘_mm512_cmplt_pd_mask’ was not declared in this scope
     return mask_type(_mm512_cmplt_pd_mask(m_value, other.m_value));
                      ^~~~~~~~~~~~~~~~~~~~
```

**Please also include the following items to support reproducing the bug**
**Reproducer** (Blake testbed):
```
module load cmake/3.19.3 gcc/8.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial --arch=SKX --compiler=g++ --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --no-examples   --with-options=enable_large_mem_tests --debug
```

**Comment by PhilMiller** [comment]
Does the same configuration pass with GCC 9.x? That might be a good excuse to require a less ancient version

**Comment by PhilMiller** [comment]
> Does the same configuration pass with GCC 9.x? That might be a good excuse to require a less ancient version

If so, this potentially informs #5285

**Comment by ndellingwood** [comment]
@PhilMiller this also occurs with gcc/9.2.0 with the same configuration on the same system (Blake, SKX arch)

**Comment by crtrott** [comment]
@ibaned I think this is in your wheelhouse. Any idea why it would fail?

**Comment by ibaned** [comment]
I'm not sure. According to this it is part of AVX512F:

https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm512_cmplt_pd_mask&ig_expand=1214,1215

I don't have access to Blake right now, just requested it

**Comment by ibaned** [comment]
I just compiled successfully and ran the unit test on Blake with GCC 9.2... I'll try GCC 7.2 next

**Comment by ibaned** [comment]
reproduced with GCC 7.2 and @ndellingwood 's exact `generate_makefile` command

**Comment by ibaned** [comment]
These intrinsics are not provided by GCC 7.2.0 and older, but are provided by GCC 8.1.0 and newer

**Comment by ibaned** [comment]
Working on a fix to always use older-compiler-supported intrinsics

**Comment by ibaned** [comment]
PR #5318 should fix this, tested on Blake. Thanks for pointing this out @ndellingwood !

**Comment by crtrott** [comment]
looks like this fails in DEBUG build type with GCC 8:

```
cmake -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_SKX=ON -DKokkos_ENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=DEBUG ../
```

```
[100%] Building CXX object simd/unit_tests/CMakeFiles/KokkosSimd_UnitTest_SIMD.dir/TestSIMD.cpp.o
In file included from /ascldap/users/crtrott/Kokkos/kokkos/simd/src/Kokkos_SIMD.hpp:53,
                 from /ascldap/users/crtrott/Kokkos/kokkos/simd/unit_tests/TestSIMD.cpp:47:
/ascldap/users/crtrott/Kokkos/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp: In member function 'Kokkos::Experimental::simd<double, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> >::mask_type Kokkos::Experimental::simd<double, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> >::operator<(const Kokkos::Experimental::simd<double, Kokkos::Experimental::simd_abi::avx512_fixed_size<8> >&) const':
/ascldap/users/crtrott/Kokkos/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp:680:22: error: '_mm512_cmplt_pd_mask' was not declared in this scope
     return mask_type(_mm512_cmplt_pd_mask(m_value, other.m_value));
                      ^~~~~~~~~~~~~~~~~~~~
/ascldap/users/crtrott/Kokkos/kokkos/simd/src/Kokkos_SIMD_AVX512.hpp:680:22: note: suggested alternative: '_mm512_cmp_pd_mask'
     return mask_type(_mm512_cmplt_pd_mask(m_value, other.m_value));
                      ^~~~~~~~~~~~~~~~~~~~
                      _mm512_cmp_pd_mask

```

**Comment by ibaned** [comment]
@crtrott this should have been fixed by https://github.com/kokkos/kokkos/pull/5318 . One thing is that pull request was only merged into the 3.7 release branch but maybe it didn't get to develop? Either way if you merge that pull request into whatever branch you're using it shouldn't call `cmplt` anymore.

**Comment by ibaned** [comment]
Oh I guess you're saying even some GCC 8 builds fail too?

**Comment by crtrott** [comment]
Yeah looks like the definition of those intrinsics is protected by `_OPTIMIZE_` ...

```
/home/projects/x86-64/gcc/8.2.0/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/avx512fintrin.h
```

**Comment by crtrott** [comment]
And yeah: compiles with -O1 but fails with -O0 ...
```
/ascldap/users/projects/x86-64/gcc/8.2.0/bin/g++ -DKOKKOS_DEPENDENCE -I/ascldap/users/crtrott/Kokkos/kokkos/tpls/gtest -I/ascldap/users/crtrott/Kokkos/kokkos/build -I/ascldap/users/crtrott/Kokkos/kokkos/build/core/src -I/ascldap/users/crtrott/Kokkos/kokkos/core/src -I/ascldap/users/crtrott/Kokkos/kokkos/core/src/../../tpls/desul/include -I/ascldap/users/crtrott/Kokkos/kokkos/build/containers/src -I/ascldap/users/crtrott/Kokkos/kokkos/containers/src -I/ascldap/users/crtrott/Kokkos/kokkos/build/algorithms/src -I/ascldap/users/crtrott/Kokkos/kokkos/algorithms/src -I/ascldap/users/crtrott/Kokkos/kokkos/build/simd/src -I/ascldap/users/crtrott/Kokkos/kokkos/simd/src -g -march=skylake-avx512 -mtune=skylake-avx512 -std=gnu++17 -o CMakeFiles/KokkosSimd_UnitTest_SIMD.dir/TestSIMD.cpp.o -c /ascldap/users/crtrott/Kokkos/kokkos/simd/unit_tests/TestSIMD.cpp -O1
```

**Comment by ibaned** [comment]
Just to be clear, you're pointing out that trying to call `cmplt` would fail in non-optimized builds with GCC 8. but the pull request I put up has Kokkos *never* call `cmplt` under any circumstances. So this is just additional detail but nothing needs to be fixed in the code anymore right?

**Comment by ajpowelsnl** [comment]
@ibaned , @crtrott -- has this issue been resolved with Dan's PR?

**Comment by ibaned** [comment]
@ajpowelsnl I recommended to @crtrott to merge my PR into develop, but I don't know if that has been done

**Comment by ajpowelsnl** [comment]
Hi @ibaned and @ndellingwood -- has this issue been fully resolved as of Kokkos-3.7?  If so, would you please close with a comment, confirming completion and merging?

**Comment by PhilMiller** [comment]
Daniel's PR fixed it for 3.7, and Nathan cherry picked that to develop. This is fully resolved.
