### ISSUE TITLE
kokkos-devel does not build now: error: 'aligned_alloc' is not a member of 'std'; did you mean 'aligned_union'?

### ISSUE THREAD

**Issue by barracuda156** [kokkos/kokkos#6367]
Commit 8d8b24a1f165b56c1debe457ef8d6291bb1a8b01 has broken the build with GCC 12.3.0 for me:

```
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_kokkos/kokkos-devel/work/kokkos-ca3687e637c12225e824ee626e69fc9fea8cebd2/core/src/impl/Kokkos_HostSpace.cpp: In member function 'void* Kokkos::HostSpace::impl_allocate(const char*, size_t, size_t, Kokkos::Tools::SpaceHandle) const':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_kokkos/kokkos-devel/work/kokkos-ca3687e637c12225e824ee626e69fc9fea8cebd2/core/src/impl/Kokkos_HostSpace.cpp:95:16: error: 'aligned_alloc' is not a member of 'std'; did you mean 'aligned_union'?
   95 |     ptr = std::aligned_alloc(alignment, size);
      |                ^~~~~~~~~~~~~
      |                aligned_union
make[2]: *** [core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_HostSpace.cpp.o] Error 1
```

P. S. Passing `-std=c++17` does not help.

**Comment by barracuda156** [comment]
I guess, a check should be done if `aligned_alloc` is available, and if not, then `posix_memalign` should be used.

**Comment by jwakely** [comment]
> I guess, a check should be done if `aligned_alloc` is available, and if not, then `posix_memalign` should be used.

Or check for `__cpp_aligned_new` and use the aligned version of `operator new`, which should deal with using aligned_alloc or posix_memalign or whatever the OS supports.

**Comment by masterleinad** [comment]
@barracuda156 Is `aligned_alloc` (in the global namespace) available using your toolchain?

**Comment by barracuda156** [comment]
> @barracuda156 Is `aligned_alloc` (in the global namespace) available using your toolchain?

@masterleinad It is not there before macOS 10.15: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92143#c6

**Comment by manuel5975p** [comment]
std::aligned_alloc should be standard since C++17: https://en.cppreference.com/w/cpp/memory/c/aligned_alloc
Did you enable -std=c++17?

**Comment by barracuda156** [comment]
> std::aligned_alloc should be standard since C++17: https://en.cppreference.com/w/cpp/memory/c/aligned_alloc
> Did you enable -std=c++17?

@manuel5975p It is only available when implemented in the OS to begin with. C++17 does not provide it on its own.

**Comment by jwakely** [comment]
> C++17 does not provide it on its own.

Pedantically, this statement is meaningless. C++17 is a standard and says `std::aligned_alloc` exists, that's all.

Typical C++17 *implementations* do not provide their own, they use the version provided by the C library. And concretely, libstdc++ does not provide its own.

**Comment by jwakely** [comment]
@manuel5975p also, did you read the initial comment, which clearly says "P. S. Passing `-std=c++17` does not help."

**Comment by dalg24** [comment]
I expect this is fixed now.  Feel free to re-open if you are still seeing issues.

**Comment by barracuda156** [comment]
@dalg24 Yes, we are good now, thank you.
