### ISSUE TITLE
Kokkos Hip Atomics compile failure(s) with ROCm 3.9

### ISSUE THREAD

**Issue by robertmaynard** [kokkos/kokkos#3581]
The VTK-m project is seeing compile failures when upgrading from ROCm 3.8 to 3.9. Currently we are seeing issues with functions such as `atomic_fetch_and`.

Compile error:

```
kokkos_atomic.cpp:24:18: error: reference to __device__ function 'atomic_fetch_and' in __host__ __device__ function
  return Kokkos::atomic_fetch_and(pointer, operand);
                 ^
kokkos_atomic.cpp:34:10: note: called by 'expose_issue_host'
    *a = AtomicAnd(a, ~(T(0x1u) << 1));
         ^
/workspaces/install/include/HIP/Kokkos_HIP_Atomic.hpp:559:46: note: 'atomic_fetch_and' declared here
__inline__ __device__ unsigned long long int atomic_fetch_and(
```

Reproducer:
```cxx
#include "hip/hip_runtime.h"

#include <atomic>
#include <type_traits>
#include <Kokkos_Core.hpp>
#include <Kokkos_Atomic.hpp>

template <typename T>
__host__ __device__ inline T AtomicAnd(
  T* pointer,
  T operand)
{
  //fences removed...
  return Kokkos::atomic_fetch_and(pointer, operand);
}

__global__ void expose_issue_device(unsigned long long *a) {
    using T = unsigned long long;
    *a = AtomicAnd(a, ~(T(0x1u) << 1));
}

void expose_issue_host(unsigned long long *a) {
    using T = unsigned long long;
    *a = AtomicAnd(a, ~(T(0x1u) << 1));
}

__global__ void expose_issue_device(unsigned long *a) {
    using T = unsigned long;
    *a = AtomicAnd(a, ~(T(0x1u) << 1));
}

void expose_issue_host(unsigned long *a) {
    using T = unsigned long;
    *a = AtomicAnd(a, ~(T(0x1u) << 1));
}

```

**Comment by Rombur** [comment]
I can reproduce it with ROCm 3.9. This looks very similar to the bug report that @calewis opened on llvm's bugzilla https://bugs.llvm.org/show_bug.cgi?id=46922

**Comment by Rombur** [comment]
I am able to compile the test when moving `Kokkos::atomic_fetch_and` inside `expose_issue_device(unsigned long long *a)` and `expose_issue_host(unsigned long long *a)`.

**Comment by calewis** [comment]
@robertmaynard we did confirm that it's not exactly the same that arose in clang-cuda issue since your example code compiles on the CUDA backend using clang-cuda.  The issue appears to be that the presence of an exact match ignores`__host__ __device__` annotations (I don't know if this is correct HIP or not).  So when you call from a `__host__ __device__` function you get an exact match on atomic_fetch_and in the HIP backend but it's a device function so the host version can't compile.  If you call the `atomic_fetch_and` from inside a host only function it seems okay.  

All that said I don't yet know how to fix it, I'm just updating the issue with what we think we know at the moment.

**Comment by crtrott** [comment]
Fixed in #3588

**Comment by robertmaynard** [comment]
Excellent, I will verify locally next week and report back.

**Comment by robertmaynard** [comment]
Verified locally that #3588 fixes my issue. Thank you!
