### ISSUE TITLE
clang/8 + cuda/10.0 build failures following CUDA graph merge

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#3559]
clang/8 + cuda/10 nightly builds began failing after merge of PR #3369  with error messages:

```bash
20:59:28 /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_clang8_cuda/kokkos/core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp:169:9: error: no matching function for call to 'cudaGraphAddDependencies'
20:59:28         cudaGraphAddDependencies(m_graph, &pred_cuda_node, &cuda_node, 1));
20:59:28         ^~~~~~~~~~~~~~~~~~~~~~~~
20:59:28 /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_clang8_cuda/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:72:41: note: expanded from macro 'CUDA_SAFE_CALL'
20:59:28   Kokkos::Impl::cuda_internal_safe_call(call, #call, __FILE__, __LINE__)
20:59:28                                         ^~~~
20:59:28 /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_clang8_cuda/kokkos/core/src/Kokkos_GraphNode.hpp:186:16: note: in instantiation of function template specialization 'Kokkos::Impl::GraphImpl<Kokkos::Cuda>::add_predecessor<std::shared_ptr<Kokkos::Impl::GraphNodeImpl<Kokkos::Cuda, Kokkos::Impl::GraphNodeKernelImpl<Kokkos::Cuda, Kokkos::RangePolicy<Kokkos::Cuda, Kokkos::Impl::IsGraphKernelTag>, Test::CountTestFunctor<Kokkos::Cuda>, Kokkos::ParallelForTag>, Kokkos::Experimental::GraphNodeRef<Kokkos::Cuda, Kokkos::Experimental::TypeErasedTag, Kokkos::Experimental::TypeErasedTag> > >, Kokkos::Experimental::GraphNodeRef<Kokkos::Cuda, Kokkos::Experimental::TypeErasedTag, Kokkos::Experimental::TypeErasedTag> >' requested here
20:59:28     graph_ptr->add_predecessor(rv.m_node_impl, *this);
20:59:28                ^
20:59:28 /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_clang8_cuda/kokkos/core/src/Kokkos_Graph.hpp:175:10: note: in instantiation of function template specialization 'Kokkos::Experimental::create_graph<Kokkos::Cuda, (lambda at /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_clang8_cuda/kokkos/core/unit_test/TestGraph.hpp:121:58)>' requested here
20:59:28   return create_graph(ExecutionSpace{}, (Closure &&) arg_closure);
20:59:28          ^
20:59:28 /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_clang8_cuda/kokkos/core/unit_test/TestGraph.hpp:121:29: note: in instantiation of function template specialization 'Kokkos::Experimental::create_graph<Kokkos::Cuda, (lambda at /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_clang8_cuda/kokkos/core/unit_test/TestGraph.hpp:121:58)>' requested here
20:59:28       Kokkos::Experimental::create_graph<TEST_EXECSPACE>([&](auto root) {
20:59:28                             ^
20:59:28 /home/projects/x86-64/cuda/10.0/include/cuda_runtime_api.h:9017:39: note: candidate function not viable: 2nd argument ('CUgraphNode_st *const *') would lose const qualifier
20:59:28 extern __host__ cudaError_t CUDARTAPI cudaGraphAddDependencies(cudaGraph_t graph, cudaGraphNode_t *from, cudaGraphNode_t *to, size_t numDependencies);
```

Sample reproducer (kokkos-dev-2):
```bash
module load sems-env sems-cmake/3.12.2 clang/8.0 cuda/10.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=SNB,Volta70 --compiler=clang++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --with-cuda --kokkos-path=$KOKKOS_PATH --with-options=disable_deprecated_code --with-cuda-options=enable_lambda  --no-examples 
```

Edit: Fixed mistaken PR listed above

**Comment by ndellingwood** [comment]
@crtrott @e10harvey this doesn't appear related to #3549, but brings up the question if we are dropping support for clang+cuda with clang < version 9?

**Comment by dalg24** [comment]
We will bring this up in the developer meeting but yes the intent is to drop support for compiling CUDA with LLVM/Clang version prior to 9.0.0

**Comment by ndellingwood** [comment]
@dalg24 thanks for the update, should this be marked as CompilerIssue and WontFix?

**Comment by dalg24** [comment]
Yes

**Comment by dalg24** [comment]
@ndellingwood looking at what you posted the failures seem related to #3369

**Comment by crtrott** [comment]
maybe related to #3562

**Comment by ndellingwood** [comment]
@dalg24 @crtrott you're correct, I added the incorrect PR in the original message, edited to update

**Comment by dalg24** [comment]
Looks like a duplicate of #3562 now that I look closer at it.  Meaning that I expect #3562 will fix this as well.
