### ISSUE TITLE
gcc/9.2.0 and clang/9 with c++20 compilation failures in incremental/Test05_ParallelReduce_RangePolicy: "error: no matching function for call to ‘Test::NonTrivialReduceFunctor::NonTrivialReduceFunctor"

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#3568]
Nightly gcc/9.2 and clang/9 builds (all backends) with c++20 enabled began failing after merge of #3542  with error messages:

```
23:32:39 /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_gcc920_openmp_serial_cpp20/kokkos/core/unit_test/incremental/Test05_ParallelReduce_RangePolicy.hpp:131:29: error: no matching function for call to ‘Test::NonTrivialReduceFunctor::NonTrivialReduceFunctor(<brace-enclosed initializer list>)’
23:32:39   131 |                             NonTrivialReduceFunctor{}, sum);
23:32:39       |                             ^~~~~~~~~~~~~~~~~~~~~~~~~
23:32:39 In file included from /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_gcc920_openmp_serial_cpp20/TestAll_2020-11-02_22.31.20/gcc/9.2.0/Serial-release/core/unit_test/generated/Test05_ParallelReduce_RangePolicy_SERIAL.cpp:53:
23:32:39 /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_gcc920_openmp_serial_cpp20/kokkos/core/unit_test/incremental/Test05_ParallelReduce_RangePolicy.hpp:72:3: note: candidate: ‘constexpr Test::NonTrivialReduceFunctor::NonTrivialReduceFunctor(Test::NonTrivialReduceFunctor&&)’
23:32:39    72 |   NonTrivialReduceFunctor(NonTrivialReduceFunctor &&)      = default;
23:32:39       |   ^~~~~~~~~~~~~~~~~~~~~~~
23:32:39 /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_gcc920_openmp_serial_cpp20/kokkos/core/unit_test/incremental/Test05_ParallelReduce_RangePolicy.hpp:72:3: note:   candidate expects 1 argument, 0 provided
23:32:39 /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_gcc920_openmp_serial_cpp20/kokkos/core/unit_test/incremental/Test05_ParallelReduce_RangePolicy.hpp:71:3: note: candidate: ‘constexpr Test::NonTrivialReduceFunctor::NonTrivialReduceFunctor(const Test::NonTrivialReduceFunctor&)’
23:32:39    71 |   NonTrivialReduceFunctor(NonTrivialReduceFunctor const &) = default;
23:32:39       |   ^~~~~~~~~~~~~~~~~~~~~~~
23:32:39 /home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_gcc920_openmp_serial_cpp20/kokkos/core/unit_test/incremental/Test05_ParallelReduce_RangePolicy.hpp:71:3: note:   candidate expects 1 argument, 0 provided
...
```

Sample reproducer (gcc/9.2, serial backend):
```bash
module load sems-env sems-cmake/3.12.2 sems-gcc/9.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial --arch=SNB,Volta70 –compiler=g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="20" --kokkos-path=$KOKKOS_PATH --with-options=disable_deprecated_code --no-examples
```

**Comment by ndellingwood** [comment]
@masterleinad if I add a default ctor `NonTrivialReduceFunctor() = default;` the compiler is happy with c++20 enabled, is this the right thing to do?

**Comment by dalg24** [comment]
That works.  The default constructor should have been implicitly generated by the compiler...

**Comment by masterleinad** [comment]
> @masterleinad if I add a default ctor `NonTrivialReduceFunctor() = default;` the compiler is happy with c++20 enabled, is this the right thing to do?

Yes, the class remains non-trivially-copyable: https://godbolt.org/z/x5afx8.
