### PR TITLE
Fix nvcc warnings in mdspan

### PR DESCRIPTION
**Pull request by masterleinad**
Corresponds to https://github.com/kokkos/mdspan/pull/440.
If we are not including `mdspan` as system includes or when using `MSVC+Cuda` (where the supression doesn't seem to work properly), we are getting warnigs such as (Makefile build with Cuda using the 4.7.02 branch)
```
/var/jenkins/workspace/Kokkos_PR-8728/tpls/mdspan/include/mdspan/../experimental/__p0009_bits/utility.hpp(219): error #20013-D: calling a constexpr __host__ function("max") from a __host__ __device__ function("check_mul_result_is_nonnegative_and_representable") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during:
            instantiation of "__nv_bool Kokkos::detail::check_mul_result_is_nonnegative_and_representable(T, T) [with T=std::size_t]" 
/usr/include/c++/9/type_traits(2924): here
            instantiation of "const __nv_bool std::is_assignable_v [with _Tp=Kokkos::mdspan<uint32_t, Kokkos::extents<std::size_t, 18446744073709551615UL>, Kokkos::Experimental::layout_left_padded<18446744073709551615UL>, Kokkos::Impl::SpaceAwareAccessor<Kokkos::CudaSpace::memory_space, Kokkos::Impl::ReferenceCountedAccessor<uint32_t, Kokkos::CudaSpace::memory_space, Kokkos::default_accessor<uint32_t>>>>, _Up=Kokkos::mdspan<uint32_t, Kokkos::extents<std::size_t, 18446744073709551615UL>, Kokkos::Experimental::layout_left_padded<18446744073709551615UL>, Kokkos::Impl::SpaceAwareAccessor<Kokkos::CudaSpace::memory_space, Kokkos::Impl::ReferenceCountedAccessor<uint32_t, Kokkos::CudaSpace::memory_space, Kokkos::default_accessor<uint32_t>>>>]" 
/var/jenkins/workspace/Kokkos_PR-8728/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp(48): here
/var/jenkins/workspace/Kokkos_PR-8728/tpls/mdspan/include/mdspan/../experimental/__p0009_bits/utility.hpp(201): error #20013-D: calling a constexpr __host__ function("min") from a __host__ __device__ function("in_range") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during:
            instantiation of "__nv_bool Kokkos::detail::in_range<R,T>(T) noexcept [with R=std::size_t, T=size_t]" 
/usr/include/c++/9/type_traits(2924): here
```
or (MSVC+Cuda)
```
2025-12-11T13:15:48.8447466Z D:\a\kokkos\kokkos\tpls\mdspan\include\experimental\__p0009_bits\utility.hpp(219): warning #20013-D: calling a constexpr __host__ function("max") from a __host__ __device__ function("check_mul_result_is_nonnegative_and_representable") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this. [D:\a\kokkos\kokkos\build\algorithms\unit_tests\Kokkos_AlgorithmsUnitTest_StdSet_A.vcxproj]
2025-12-11T13:15:48.8451584Z       return a <= std::numeric_limits<T>::max() / b;
2025-12-11T13:15:48.8454510Z                   ^
2025-12-11T13:15:48.8457518Z             detected during:
2025-12-11T13:15:48.8461252Z               instantiation of "__nv_bool Kokkos::detail::check_mul_result_is_nonnegative_and_representable(T, T) [with T=size_t]" at line 328 of C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\type_traits
2025-12-11T13:15:48.8466658Z               instantiation of "const __nv_bool std::is_convertible_v [with _From=Kokkos::extents<size_t, 18446744073709551615ULL>, _To=Kokkos::extents<size_t, 18446744073709551615ULL>]" at line 328 of C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\type_traits
2025-12-11T13:15:48.8470689Z               instantiation of "const __nv_bool std::is_convertible_v [with _From=const Kokkos::Experimental::layout_left_padded<18446744073709551615ULL>::mapping<Kokkos::extents<size_t, 18446744073709551615ULL>> &, _To=Kokkos::Experimental::layout_left_padded<18446744073709551615ULL>::mapping<Kokkos::extents<size_t, 18446744073709551615ULL>>]" at line 35 of D:\a\kokkos\kokkos\core\src\Cuda/Kokkos_Cuda_UniqueToken.hpp
2025-12-11T13:15:48.8473154Z   
2025-12-11T13:15:48.8476322Z   Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"
2025-12-11T13:15:48.8478123Z   
```
with `nvcc`.

### CODE REVIEW

**Comment by masterleinad** [comment]
jenkins CI is failing in HIP-ROCM-6.3 spuriously. The GitLab CI failures are also unrelated.

**Review by dalg24 — APPROVED** [review]

File: tpls/mdspan/include/experimental/__p0009_bits/macros.hpp [hunk 1]
```diff
@@ -21,6 +21,9 @@
 #include <cstdio>
 #include <cstdlib>
 #include <type_traits> // std::is_void
+#if defined(MDSPAN_IMPL_HAS_SYCL)
+#include <sycl/sycl.hpp> // sycl::ext::oneapi::experimental::printf
+#endif
```
Comment (ldh4) [inline tpls/mdspan/include/experimental/__p0009_bits/macros.hpp:26]: Why was this added as part of this PR?

Comment (masterleinad) [reply tpls/mdspan/include/experimental/__p0009_bits/macros.hpp:26]: This fix was merged before the one we are interested in here so I had to inlcude it as well as part of the mdspan update.

**Review by ldh4 — APPROVED** [review]

**Review by tcclevenger — APPROVED** [review]

File: tpls/mdspan/include/experimental/__p0009_bits/macros.hpp (hunk 1 above)
Comment (ndellingwood) [reply tpls/mdspan/include/experimental/__p0009_bits/macros.hpp:26]: so this is the full snapshot corresponding to sha b6d5a171817c2d359d0271852e2cfffd067d436a ?

Comment (masterleinad) [reply tpls/mdspan/include/experimental/__p0009_bits/macros.hpp:26]: > so this is the full snapshot corresponding to sha b6d5a171817c2d359d0271852e2cfffd067d436a ?

Yes

**Review by ndellingwood — APPROVED** [review]

**Comment by ndellingwood** [comment]
Should this get cherry-pick to rc 5.0.1?

**Comment by dalg24** [comment]
> Should this get cherry-pick to rc 5.0.1?

Sure

**Comment by ndellingwood** [comment]
With cuda/12.4+gcc/11.3 this update seem to be triggering compiler issues with Trilinos:
```
[1273/4979] Building CXX object packages/stokhos/src/CMakeFiles/stokhos_tpetra_sd_mp_16_serial.dir/Tpetra_SD_LocalCrsMatrixOperator_MP_Vector_16_Serial.cpp.o
FAILED: packages/stokhos/src/CMakeFiles/stokhos_tpetra_sd_mp_16_serial.dir/Tpetra_SD_LocalCrsMatrixOperator_MP_Vector_16_Serial.cpp.o
...
/ascldap/users/ndellin/Trilinos/packages/sacado/src/Sacado_Fad_Kokkos_Specialization.hpp: In function 'auto Kokkos::subview(const Kokkos::DynRankView<T, Kokkos::LayoutContiguous<Layout, Stride>, Args ...>&, Args ...)':
/ascldap/users/ndellin/Trilinos/packages/sacado/src/Sacado_Fad_Kokkos_Specialization.hpp:133:95: error: 'iterator_traits' is not a member of 'cuda::std::__4'; did you mean 'std::iterator_traits'?
  133 |   if constexpr (std::is_same_v<typename sub_mdspan_t::layout_type,
      |                                                                                               ^
/net/watson.sandia.gov/storage/fast/projects/sems/install/rhel9-x86_64/sems/tpl/gcc/11.5.0/gcc/11.4.0/tr7kod2/bin/../lib/gcc/x86_64-pc-linux-gnu/11.4.0/../../../../include/c++/11.4.0/bits/cpp_type_traits.h:423:26: note: 'std::iterator_traits' declared here
  423 |   template<typename> struct iterator_traits;
      |                          ^~~~~~~~~~~~~~~
/ascldap/users/ndellin/Trilinos/packages/sacado/src/Sacado_Fad_Kokkos_Specialization.hpp:133:147: error: template argument 1 is invalid
  133 |   if constexpr (std::is_same_v<typename sub_mdspan_t::layout_type,
      |                                                                                                                                                   ^
/ascldap/users/ndellin/Trilinos/packages/sacado/src/Sacado_Fad_Kokkos_Specialization.hpp:133:20: error: parse error in template argument list
  133 |   if constexpr (std::is_same_v<typename sub_mdspan_t::layout_type,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ascldap/users/ndellin/Trilinos/packages/sacado/src/Sacado_Fad_Kokkos_Specialization.hpp:133:20: error: variable template-id 'is_same_v<<expression error> >' in nested-name-specifier
/net/watson.sandia.gov/storage/fast/projects/sems/install/rhel9-x86_64/sems/tpl/gcc/11.5.0/gcc/11.4.0/tr7kod2/bin/../lib/gcc/x86_64-pc-linux-gnu/11.4.0/../../../../include/c++/11.4.0/type_traits:3251:1: note: 'template<class _Tp, class _Up> constexpr const bool std::is_same_v<_Tp, _Up>' declared here
 3251 |   inline constexpr bool is_same_v = __is_same(_Tp, _Up);
      | ^ ~~~~~~~
/ascldap/users/ndellin/Trilinos/packages/sacado/src/Sacado_Fad_Kokkos_Specialization.hpp:133:164: error: expected initializer before ',' token
  133 |   if constexpr (std::is_same_v<typename sub_mdspan_t::layout_type,
      |                                                                                                                                                                    ^
/ascldap/users/ndellin/Trilinos/packages/sacado/src/Sacado_Fad_Kokkos_Specialization.hpp:133:164: error: expected ')' before ',' token
  133 |   if constexpr (std::is_same_v<typename sub_mdspan_t::layout_type,
      |              ~                                                                                                                                                     ^
      |                                                                                                                                                                    )
/ascldap/users/ndellin/Trilinos/packages/sacado/src/Sacado_Fad_Kokkos_Specialization.hpp:133:181: error: the value of 'layout_type' is not usable in a constant expression
  133 |   if constexpr (std::is_same_v<typename sub_mdspan_t::layout_type,
```

This is not present in builds with cuda/12.6 or cuda/12.8

**Comment by ndellingwood** [comment]
Adding guards for cuda version worked around the issue for me
```diff
diff --git a/tpls/mdspan/include/experimental/__p0009_bits/utility.hpp b/tpls/mdspan/include/experimental/__p0009_bits/utility.hpp
index 1ebc8a839..2d8a93845 100644
--- a/tpls/mdspan/include/experimental/__p0009_bits/utility.hpp
+++ b/tpls/mdspan/include/experimental/__p0009_bits/utility.hpp
@@ -4,7 +4,7 @@
 #include <type_traits>
 #include <array>
 #include <utility>
-#if defined(MDSPAN_IMPL_HAS_CUDA) && defined(__NVCC__)
+#if defined(MDSPAN_IMPL_HAS_CUDA) && defined(__NVCC__) && (__CUDACC_VER_MAJOR__ * 100 + __CUDACC_VER_MINOR__ * 10 >= 1260)
 #include <cuda/std/limits>
 #else
 #include <limits>
@@ -203,7 +203,7 @@ MDSPAN_INLINE_FUNCTION constexpr bool cmp_greater_equal(T t, U u) noexcept {
 
 template <class R, class T>
 MDSPAN_INLINE_FUNCTION constexpr bool in_range(T t) noexcept {
-#if defined(MDSPAN_IMPL_HAS_CUDA) && defined(__NVCC__)
+#if defined(MDSPAN_IMPL_HAS_CUDA) && defined(__NVCC__) && (__CUDACC_VER_MAJOR__ * 100 + __CUDACC_VER_MINOR__ * 10 >= 1260)
   using cuda::std::numeric_limits;
 #else
   using std::numeric_limits;
@@ -226,7 +226,7 @@ check_mul_result_is_nonnegative_and_representable(T a, T b) {
   if constexpr (std::is_signed_v<T>) {
     if ( a < 0 || b < 0 ) return false;
   }
-#if defined(MDSPAN_IMPL_HAS_CUDA) && defined(__NVCC__)
+#if defined(MDSPAN_IMPL_HAS_CUDA) && defined(__NVCC__) && (__CUDACC_VER_MAJOR__ * 100 + __CUDACC_VER_MINOR__ * 10 >= 1260)
   using cuda::std::numeric_limits;
 #else
   using std::numeric_limits;
```

**Comment by masterleinad** [comment]
I'm surprised we don't see any such issue in our CI where we are also testing with `Cuda-12.2` (`nvcc`) and `Cuda-11.8` (clang).

**Comment by ndellingwood** [comment]
@masterleinad yeah, though this has been the case (Kokkos CI fine, downstream usage troubles) with some other PRs as well for example the partition_space update including ranges headers was fine in Kokkos CI, but had breakages with Trilinos https://github.com/kokkos/kokkos/pull/8556#issuecomment-3429931845
