### ISSUE TITLE
Trilinos nightly failure, gcc/11.3.0 Serial build, incompatible change with Sacado

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7258]
**Describe the bug**

Nightly Trilinos build with gcc/11.3.0, Serial backend, is failing to compile unit tests with output (might be intermixed due to make -jN compilation):

```
20:31:35 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests_Serial.cpp:15:
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests.hpp: In instantiation of 'void Kokkos_View_Fad_Resize_UnitTest<FadType, Layout, Device>::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const [with FadType = Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5> >; Layout = Kokkos::LayoutContiguous<Kokkos::LayoutLeft>; Device = Kokkos::Serial; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]':
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests_Serial.cpp:19:1:   required from here
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests.hpp:958:17: error: no matching function for call to 'resize(ViewType&, const size_type&, long unsigned int, long unsigned int)'
20:31:35   958 |   Kokkos::resize(v, num_rows, num_cols+1, fad_size+1);
20:31:35       |   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20:31:35 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/kokkos/core/src/Kokkos_Core.hpp:68,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:112,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/src/new_design/Sacado_Fad_Exp_GeneralFadTraits.hpp:197,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/src/Sacado.hpp:32,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests.hpp:12,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests_Serial.cpp:15:
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3043:1: note: candidate: 'template<class T, class ... P, class ... ViewCtorArgs> std::enable_if_t<(is_same_v<typename Kokkos::View<DataType, Properties>::array_layout, Kokkos::LayoutLeft> || is_same_v<typename Kokkos::View<DataType, Properties>::array_layout, Kokkos::LayoutRight>)> Kokkos::resize(const Kokkos::Impl::ViewCtorProp<ViewCtorArgs ...>&, Kokkos::View<D, P ...>&, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t)'
20:31:35  3043 | resize(const Impl::ViewCtorProp<ViewCtorArgs...>& arg_prop,
20:31:35       | ^~~~~~
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3043:1: note:   template argument deduction/substitution failed:
20:31:35 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests_Serial.cpp:15:
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests.hpp:958:17: note:   'ViewType' {aka 'Kokkos::View<Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5> >**, Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Serial>'} is not derived from 'const Kokkos::Impl::ViewCtorProp<ViewCtorArgs ...>'
20:31:35   958 |   Kokkos::resize(v, num_rows, num_cols+1, fad_size+1);
20:31:35       |   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20:31:35 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/kokkos/core/src/Kokkos_Core.hpp:68,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp:112,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/src/new_design/Sacado_Fad_Exp_GeneralFadTraits.hpp:197,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/src/Sacado.hpp:32,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests.hpp:12,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests_Serial.cpp:15:
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3061:1: note: candidate: 'template<class T, class ... P> std::enable_if_t<(is_same_v<typename Kokkos::View<DataType, Properties>::array_layout, Kokkos::LayoutLeft> || is_same_v<typename Kokkos::View<DataType, Properties>::array_layout, Kokkos::LayoutRight>)> Kokkos::resize(Kokkos::View<D, P ...>&, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t)'
20:31:35  3061 | resize(Kokkos::View<T, P...>& v, const size_t n0 = KOKKOS_IMPL_CTOR_DEFAULT_ARG,
20:31:35       | ^~~~~~
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3061:1: note:   template argument deduction/substitution failed:
20:31:35 In file included from /projects/x86-64-icelake-rocky8/compilers/gcc/11.3.0/gcc/8.5.0/base/3kidadg/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../include/c++/11.3.0/bits/move.h:57,
20:31:35                  from /projects/x86-64-icelake-rocky8/compilers/gcc/11.3.0/gcc/8.5.0/base/3kidadg/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../include/c++/11.3.0/bits/stl_pair.h:59,
20:31:35                  from /projects/x86-64-icelake-rocky8/compilers/gcc/11.3.0/gcc/8.5.0/base/3kidadg/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../include/c++/11.3.0/bits/stl_algobase.h:64,
20:31:35                  from /projects/x86-64-icelake-rocky8/compilers/gcc/11.3.0/gcc/8.5.0/base/3kidadg/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../include/c++/11.3.0/bits/char_traits.h:39,
20:31:35                  from /projects/x86-64-icelake-rocky8/compilers/gcc/11.3.0/gcc/8.5.0/base/3kidadg/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../include/c++/11.3.0/string:40,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/teuchos/core/src/Teuchos_ConfigDefs.hpp:51,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/teuchos/core/src/Teuchos_TypeNameTraits.hpp:33,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/teuchos/core/src/Teuchos_TestForException.hpp:17,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/teuchos/core/src/Teuchos_Assert.hpp:14,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/teuchos/core/src/Teuchos_VerbosityLevel.hpp:19,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/teuchos/core/src/Teuchos_Describable.hpp:13,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestBase.hpp:19,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestHarness.hpp:19,
20:31:35                  from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests_Serial.cpp:10:
20:31:35 /projects/x86-64-icelake-rocky8/compilers/gcc/11.3.0/gcc/8.5.0/base/3kidadg/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../include/c++/11.3.0/type_traits: In substitution of 'template<bool _Cond, class _Tp> using enable_if_t = typename std::enable_if::type [with bool _Cond = false; _Tp = void]':
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/kokkos/core/src/Kokkos_CopyViews.hpp:3061:1:   required by substitution of 'template<class T, class ... P> std::enable_if_t<(is_same_v<typename Kokkos::View<DataType, Properties>::array_layout, Kokkos::LayoutLeft> || is_same_v<typename Kokkos::View<DataType, Properties>::array_layout, Kokkos::LayoutRight>)> Kokkos::resize(Kokkos::View<D, P ...>&, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t) [with T = Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5> >**; P = {Kokkos::LayoutContiguous<Kokkos::LayoutLeft, 1>, Kokkos::Serial}]'
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests.hpp:958:17:   required from 'void Kokkos_View_Fad_Resize_UnitTest<FadType, Layout, Device>::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const [with FadType = Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::StaticFixedStorage<double, 5> >; Layout = Kokkos::LayoutContiguous<Kokkos::LayoutLeft>; Device = Kokkos::Serial; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]'
20:31:35 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests_Serial.cpp:19:1:   required from here
```

The most recent run included the fixes from https://github.com/kokkos/kokkos/pull/7253 , changes below are from initial failure (this was mentioned in #7251 as I mistakenly assumed a likely connection since the failure began with the same run of nightlies)

**Changes**

Fix misspelled cmake variable, for some systems leading to not compiling all tests — [Christian Robert Trott](https://jenkins-son.sandia.gov/user/crtrott/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail0)
Fix overlooked naming test in https://github.com/kokkos/kokkos/pull/7222 — [Christian Robert Trott](https://jenkins-son.sandia.gov/user/crtrott/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail1)
Fixup [Experimental::]SYCL — [dalg24](https://jenkins-son.sandia.gov/user/dalg24/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail2)
Use macros to protect use of SharedSpace — [Christian Robert Trott](https://jenkins-son.sandia.gov/user/crtrott/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail3)
core(graph): promote instantiate to public API — [romin.tomasetti](https://jenkins-son.sandia.gov/user/romin.tomasetti/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail4)
Enforce modernize-type-traits (https://github.com/kokkos/kokkos/pull/7227) — [github](https://jenkins-son.sandia.gov/user/github/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail5)
typo: kokkkos -> kokkos — [romin.tomasetti](https://jenkins-son.sandia.gov/user/romin.tomasetti/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail6)
core(view): aligning HostMirror and host_mirror_type — [romin.tomasetti](https://jenkins-son.sandia.gov/user/romin.tomasetti/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail7)
Add support for CUDA unified memory architectures i.e. Grace Hopper (https://github.com/kokkos/kokkos/pull/6823) — [github](https://jenkins-son.sandia.gov/user/github/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail8)
Using CUDA limits to set extents for blocks,grids (https://github.com/kokkos/kokkos/pull/7235) — [github](https://jenkins-son.sandia.gov/user/github/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail9)
Fix minor typing error. (https://github.com/kokkos/kokkos/pull/2314) — [github](https://jenkins-son.sandia.gov/user/github/) / [detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/707/changes#detail10)

**Please include the following for a minimal reproducer**

**Reproducer** (blake testbed):
```bash
# Repo prep
git clone -b develop https://github.com/trilinos/Trilinos.git
TRILINOS_DIR=$PWD/Trilinos
git clone -b develop https://github.com/kokkos/kokkos.git
KOKKOS_DIR=$PWD/kokkos
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
KOKKOSKERNELS_DIR=$PWD/kokkos-kernels

cd $TRILINOS_DIR
ln -s ${KOKKOS_DIR}/kokkos kokkos
ln -s ${KOKKOSKERNELS_DIR}/kokkos-kernels kokkos-kernels
cd -

mkdir -p Build
cd Build

# Setup environment
salloc -N 1 -p all

module purge
module load cmake gcc/11.3.0 openmpi/4.1.5 openblas/0.3.23
module load boost/1.82.0 hdf5/1.14.1-2 zlib/1.2.13 netcdf-c/4.9.2
module load metis/5.1.0 parmetis/4.0.3
module list
 
export NETCDF_ROOT=${NETCDF_C_ROOT}
export PNETCDF_ROOT=${NETCDF_C_ROOT}
export CONFIG_HDF5_LIBS="-L${HDF5_ROOT}/lib;${HDF5_ROOT}/lib/libhdf5_hl.a;${HDF5_ROOT}/lib/libhdf5.a;-lz;-ldl"
export CONFIG_NETCDF_LIBS="-L${NETCDF_C_ROOT}/lib;${NETCDF_C_ROOT}/lib/libnetcdf.a;${CONFIG_HDF5_LIBS}"

# Configuration
cmake \
  -D CMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
  -D CMAKE_CXX_COMPILER="`which mpicxx`" \
  -D CMAKE_C_COMPILER="`which mpicc`" \
  -D CMAKE_Fortran_COMPILER="`which mpifort`" \
  -DTPL_ENABLE_MPI=ON \
  -DTPL_ENABLE_BLAS:BOOL=ON \
   -DBLAS_LIBRARY_DIRS:FILEPATH=${OPENBLAS_ROOT}/lib \
   -DBLAS_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_LAPACK:BOOL=ON \
   -DLAPACK_INCLUDE_DIRS:FILEPATH=${OPENBLAS_ROOT}/include \
   -DLAPACK_LIBRARY_DIRS:FILEPATH=${OPENBLAS_ROOT}/lib \
   -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_Boost=ON \
   -DBoost_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -DBoost_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
  -DTPL_ENABLE_BoostLib=ON \
   -DBoostLib_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -DBoostLib_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
  -DTPL_ENABLE_Zlib=ON \
   -DZlib_INCLUDE_DIRS:PATH="${ZLIB_ROOT}/include" \
   -DTPL_Zlib_LIBRARIES:PATH="${ZLIB_ROOT}/lib/libz.a" \
  -DTPL_ENABLE_HDF5=ON \
   -DHDF5_INCLUDE_DIRS:PATH="${HDF5_ROOT}/include" \
   -DTPL_HDF5_LIBRARIES:PATH="${CONFIG_HDF5_LIBS}" \
  -DTPL_ENABLE_Netcdf=ON \
   -DNetcdf_INCLUDE_DIRS:PATH="${NETCDF_ROOT}/include" \
   -DTPL_Netcdf_LIBRARIES:PATH="${CONFIG_NETCDF_LIBS}" \
  -D TPL_ENABLE_METIS:BOOL=ON \
   -D METIS_INCLUDE_DIRS:PATH="${METIS_ROOT}/include" \
   -D METIS_LIBRARY_DIRS:PATH="${METIS_ROOT}/lib" \
   -D METIS_LIBRARY_NAMES:STRING="metis" \
  -D TPL_ENABLE_ParMETIS:BOOL=ON \
   -D ParMETIS_INCLUDE_DIRS:PATH="${PARMETIS_ROOT}/include;${METIS_ROOT}/include" \
   -D ParMETIS_LIBRARY_DIRS:PATH="${PARMETIS_ROOT}/lib" \
   -D ParMETIS_LIBRARY_NAMES:STRING="parmetis" \
\
  -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
  -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
  -DTrilinos_ENABLE_COMPLEX=ON \
  -DTrilinos_ENABLE_OpenMP=OFF \
  -DTrilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=ON \
   -D Kokkos_ENABLE_TESTS=ON \
  -D Kokkos_ARCH_SKX=ON \
   -D Kokkos_ENABLE_IMPL_MDSPAN=OFF \
  -DTrilinos_ENABLE_KokkosKernels=ON \
   -D KokkosKernels_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Sacado=ON \
   -D Sacado_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Stokhos=ON \
   -D Stokhos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Intrepid2=ON \
   -D Intrepid2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Amesos2=ON \
   -D Amesos2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Ifpack2=ON \
   -D Ifpack2_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Zoltan2=ON \
   -D Zoltan2_ENABLE_TESTS=ON \
\
  -DTPL_ENABLE_Matio=OFF \
\
-DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
-DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
  -DTrilinos_ENABLE_INSTALLATION_TESTING=OFF \
$TRILINOS_DIR

make -j16
```

**Comment by masterleinad** [comment]
Sacado defined `Kokkos::ContiguousLayout` in the `Kokkos` namespace, see
https://github.com/trilinos/Trilinos/blob/2ad26029e5e3592de143b1640480382a296c401a/packages/sacado/src/Kokkos_LayoutContiguous.hpp#L30-L74
and specilaizes std::is_same for this class, see https://github.com/trilinos/Trilinos/blob/2ad26029e5e3592de143b1640480382a296c401a/packages/sacado/src/Kokkos_LayoutContiguous.hpp#L76-L87. We could think about relaxing the requirements for `Kokkos::resize` but this clearly needs changes on the `Sacado`-side.

**Comment by ndellingwood** [comment]
@masterleinad thanks for quickly identifying the issue. I think allowing the use of `Kokkos::resize` will be necessary, there is definitely other codes that make calls to `resize` that would be broken if unable to do so in a generic way for example based on a templated View type

**Comment by ndellingwood** [comment]
I'll close after confirming in tonight's nightly build that the issue is resolved

**Comment by ndellingwood** [comment]
Nightly test passed 👍
