### ISSUE TITLE
Nightly test failure, cuda/12.2+gcc/8.5: TestRangePolicyCTAD.cpp(23): error: no instance of constructor "RangePolicy" matches the argument list

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6843]
**Describe the bug**

Nightly builds with cuda/12.2+gcc/8.5.0 fail to compile `TestRangePolicyCTAD` with output:

```
22:34:29 /home/jenkins/caraway-new/workspace/Kokkos_develop_carawayA100_cuda1170_cuda_serial/kokkos/core/unit_test/TestRangePolicyCTAD.cpp(23): error: no instance of constructor "RangePolicy" matches the argument list
22:34:29             argument types are: (int64_t, int64_t)
22:34:29   using PolicyMaker = decltype(::Kokkos::RangePolicy(std::declval<Args>()...));
22:34:29                                                      ^
22:34:29           detected during:
22:34:29             instantiation of type "<unnamed>::PolicyMaker<<unnamed>::TestRangePolicyCTAD::i64, <unnamed>::TestRangePolicyCTAD::i64>" at line 27
22:34:29             instantiation of "const bool <unnamed>::IsSamePolicy [with Policy=Kokkos::RangePolicy<>, Args=<<unnamed>::TestRangePolicyCTAD::i64, <unnamed>::TestRangePolicyCTAD::i64>]" at line 58
22:34:29 
22:34:29 /home/jenkins/caraway-new/workspace/Kokkos_develop_carawayA100_cuda1170_cuda_serial/kokkos/core/unit_test/TestRangePolicyCTAD.cpp(23): error: cannot deduce class template arguments
22:34:29   using PolicyMaker = decltype(::Kokkos::RangePolicy(std::declval<Args>()...));
22:34:29                                ^
22:34:29           detected during:
22:34:29             instantiation of type "<unnamed>::PolicyMaker<<unnamed>::TestRangePolicyCTAD::i64, <unnamed>::TestRangePolicyCTAD::i64>" at line 27
22:34:29             instantiation of "const bool <unnamed>::IsSamePolicy [with Policy=Kokkos::RangePolicy<>, Args=<<unnamed>::TestRangePolicyCTAD::i64, <unnamed>::TestRangePolicyCTAD::i64>]" at line 58
22:34:29 
22:34:29 /home/jenkins/caraway-new/workspace/Kokkos_develop_carawayA100_cuda1170_cuda_serial/kokkos/core/unit_test/TestRangePolicyCTAD.cpp(58): error: static assertion failed
22:34:29     static_assert(IsSamePolicy<Kokkos::RangePolicy<>, i64, i64>);
```

This follows merge of #6803 

**Please include the following for a minimal reproducer**

**Reproducer** (Caraway A100 queue)

```bash
${KOKKOS_PATH}/generate_makefile.bash --with-cuda --compiler=${KOKKOS_PATH}/bin/nvcc_wrapper --arch=AMPERE80 --kokkos-path=${KOKKOS_PATH} --with-cuda-options=enable_lambda
```

**Comment by nliber** [comment]
@ndellingwood I'm seeing it under Cuda 12.3 as well (I tried various cuda/gcc combos).

The CUDA compiler bug looks to be that CTAD deduction doesn't work inside the unevaluated context of `decltype`.  I'll put up a PR just to disable testing under any version of NVCC.

**Comment by dalg24** [comment]
> The CUDA compiler bug looks to be the one we already know about: CTAD deduction doesn't work inside the unevaluated context of `decltype`.
> 
> I'll put up a PR just to disable testing under any version of NVCC.

Do we have alternatives that do not involve disabling for all NVCC versions?

**Comment by masterleinad** [comment]
Our CI happily compiles the test so it's not clear why you are seeing something different. Maybe, the `gcc` version is the problem? We are using at least `gcc-9.4` with newer `nvcc` versions in our CI.

**Comment by ndellingwood** [comment]
@masterleinad the failing builds use gcc/8.5

**Comment by masterleinad** [comment]
> @masterleinad the failing builds use gcc/8.5

Right, I was wondering if it's sufficient to check for gcc-9.4 or newer since our CI indicates that that combination works.

**Comment by ndellingwood** [comment]
PR #6850 resolved the compilation error (manually tested)
