### PR TITLE
Avoid warnings for ZeroMemset in View constructor

### LINKED ISSUE #4237: Kokkos updates breaking Trilinos builds 8/12/2021
A recent update to Kokkos on 8/12/2021 is breaking builds with Trilinos, in particular the Sacado package. Looking at the error message and recent changes, most likely PR #4226 triggered the issue

This is for a build with cuda/10.1 on Volta70 arch:

```
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/kokkos/core/src/impl/Kokkos_ViewMapping.hpp(2895): error: no instance of constructor "Kokkos::View<DataType, Properties...>::View [with DataType=InnerFadType *, Properties=<Kokkos::Serial::memory_space, Kokkos::MemoryTraits<1U>>]" matches the argument list
18:56:43             argument types are: (InnerFadType *, size_t)
18:56:43           detected during:
18:56:43             instantiation of "void Kokkos::Impl::ViewValueFunctor<DeviceType, ValueType, false>::execute(__nv_bool) [with DeviceType=Kokkos::HostSpace::execution_space, ValueType=InnerFadType]" 
18:56:43 (2931): here
18:56:43             instantiation of "void Kokkos::Impl::ViewValueFunctor<DeviceType, ValueType, false>::construct_shared_allocation() [with DeviceType=Kokkos::HostSpace::execution_space, ValueType=InnerFadType]" 
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp(1426): here
18:56:43             instantiation of "Kokkos::Impl::SharedAllocationRecord<void, void> *Kokkos::Impl::ViewMapping<Traits, std::enable_if<<expression>, Traits::specialize>::type>::allocate_shared(const Kokkos::Impl::ViewCtorProp<P...> &, const Traits::array_layout &) [with Traits=Kokkos::ViewTraits<SFadType **, Kokkos::LayoutLeft, Kokkos::Serial>, P=<std::__cxx11::string, std::integral_constant<unsigned int, 0U>, Kokkos::HostSpace::memory_space, Kokkos::HostSpace::execution_space>]" 
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/kokkos/core/src/Kokkos_View.hpp(1552): here
18:56:43             instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::Impl::ViewCtorProp<P...> &, const std::enable_if<<expression>, Kokkos::ViewTraits<DataType, Properties...>::array_layout>::type &) [with DataType=SFadType **, Properties=<Kokkos::LayoutLeft, Kokkos::Serial>, P=<std::__cxx11::string>]" 
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/kokkos/core/src/Kokkos_View.hpp(1697): here
18:56:43             instantiation of "Kokkos::View<DataType, Properties...>::View(const Label &, std::enable_if<Kokkos::Impl::is_view_label<Label>::value, const size_t>::type, size_t, size_t, size_t, size_t, size_t, size_t, size_t) [with DataType=SFadType **, Properties=<Kokkos::LayoutLeft, Kokkos::Serial>, Label=char [6]]" 
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/sacado/test/UnitTests/Fad_Fad_KokkosTests.hpp(124): here
18:56:43             instantiation of "void Kokkos_View_FadFad_DeepCopy_UnitTest<FadFadType, Layout, Device>::runUnitTestImpl(Teuchos::FancyOStream &, __nv_bool &) const [with FadFadType=SFadType, Layout=Kokkos::LayoutLeft, Device=Kokkos::Serial]" 
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/sacado/test/UnitTests/Fad_Fad_KokkosTests_Serial.cpp(40): here
18:56:43 
18:56:43 1 error detected in the compilation of "/tmp/tmpxft_00003298_00000000-6_Fad_Fad_KokkosTests_Serial.cpp1.ii".
```

Nightly Build Reproducer (weaver testbed):
```
# Create symbolic links to kokkos and kokkos-kernels in Trilinos for source override
export TRILINOS_DIR=<somepath-to-trilinos-source>
export KOKKOS_DIR=<somepath>
export KOKKOSKERNELS_DIR=<somepath>

cd $TRILINOS_DIR
  # the n and f flags were needed for Jenkins, probably not needed in a local interactive build
ln -snf ${KOKKOS_DIR} kokkos
ln -snf ${KOKKOSKERNELS_DIR} kokkos-kernels


# Modules and environment
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/weaver
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt

module list
export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper
export TRILINOS_INSTALL_DIR=${PWD}/install

cd <your-build-dir>

# Configuration
cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
 -DCMAKE_CXX_STANDARD="14" \
 -DTrilinos_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
 -DSEACASIoss_structured_cgns_assembly_copy_DISABLE=ON \
 -DSEACASIoss_structured_cgns_assembly_copy_fpp_DISABLE=ON \
 -DIntrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1_DISABLE=ON \
 -DKokkosCore_UnitTest_CudaTimingBased_MPI_1_DISABLE=ON \
$TRILINOS_DIR
```

Since this occurs in Sacado (and mayalso occur with tests from Stokhos), a potentially more simplified general test configuration (I haven't verified):

```
# load modules, newer cmake, cuda/10.1

export TRILINOS_DIR=<somepath-to-trilinos-source>
export KOKKOS_DIR=<somepath>
export KOKKOSKERNELS_DIR=<somepath>

cd $TRILINOS_DIR
  # the n and f flags were needed for Jenkins, probably not needed in a local interactive build
ln -n ${KOKKOS_DIR} kokkos
ln -n ${KOKKOSKERNELS_DIR} kokkos-kernels

export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper
export TRILINOS_INSTALL_DIR=${PWD}/install

cd <your-build-dir>

# Configuration
cmake \
 -GNinja \
 -DCMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
 -DCMAKE_CXX_STANDARD="14" \
 -DTrilinos_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
 -DTrilinos_ENABLE_Sacado=ON \
 -DTrilinos_ENABLE_Kokkos=ON \
 -DKokkos_ENABLE_CUDA=ON \
 -DKokkos_ARCH_VOLTA70=ON \
 -DKokkos_ENABLE_CUDA_UVM=ON \
 -DKokkosCore_UnitTest_CudaTimingBased_MPI_1_DISABLE=ON \
$TRILINOS_DIR
```

### LINKED ISSUE #4238: Kokkos updates breaking nightly gcc/8.3.0, gcc/9, gcc/10 builds: Kokkos_HostSpace.hpp:312:12: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type
Kokkos nightly builds with gcc/8.3.0 and cuda/11.1+gcc/8.3.0 failed with error message

```
18:19:45 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda111_gcc830/kokkos/core/src/Kokkos_HostSpace.hpp:312:12: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘using value_type = using value_type = using value_type = using value_type = class Kokkos::complex<double>’ {aka ‘class Kokkos::complex<double>’}; use assignment or value-initialization instead [-Werror=class-memaccess]
18:19:45      std::memset(dst.data(), 0, sizeof(ValueType) * dst.size());
18:19:45      ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:19:45 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda111_gcc830/kokkos/core/src/Kokkos_Complex.hpp:67:34: note: ‘using value_type = using value_type = using value_type = using value_type = class Kokkos::complex<double>’ {aka ‘class Kokkos::complex<double>’} declared here
18:19:45      alignas(2 * sizeof(RealType))
```

Likely following from merge of PR #4226 , @masterleinad are you able to take a look?
Issue #4237 may be related.

Reproducer instructions (cuda build):
```
module load sems-env sems-cmake/3.17.1 sems-cuda/11.1 sems-gcc/8.3.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --with-cuda-options=enable_lambda  --no-examples --with-options=enable_large_mem_tests
```

### PR DESCRIPTION
**Pull request by masterleinad**
@ndellingwood Can you please check that this fixes https://github.com/kokkos/kokkos/issues/4238 and https://github.com/kokkos/kokkos/issues/4237?

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Comment by ndellingwood** [comment]
This resolved the gcc >= 8 nightly builds of Kokkos; I manually tested a Trilinos build that missed the merge of this PR last night and compilation passes, thanks @masterleinad
