### ISSUE TITLE
`invalid controlling predicate` when compiling OpenMP loop with Kokkos

### ISSUE THREAD

**Issue by XzzX** [kokkos/kokkos#4904]
Parallelizing a simple loop over `std::vector` with iterators using OpenMP compiles fine without Kokkos but results in `invalid controlling predicate` when linked with Kokkos with CUDA support.

MWE
```
    std::vector<double> abc(1000);
#pragma omp parallel for
    for (auto it = abc.begin(); it < abc.end(); ++it)
    {   
       *it += 2;
    } 
```

I compiled this example with `CMake` and `find_package` for Kokkos and OpenMP.
G++11, Kokkos develop branch, CUDA/11.4

**Comment by ajpowelsnl** [comment]
Is the problem just linking , or is it at the compiling stage?

**Comment by crtrott** [comment]
Non Kokkos reproducer, works with pure G++ (11.1) but not nvcc (11.6)
main.cpp:
```c++
#include <cmath>
#include <vector>
int main(int argc, char* argv[]) {
  std::vector<double> abc(1000);
  #pragma omp parallel for
  for (auto it = abc.begin(); it < abc.end(); ++it)
  {
    *it += 2;
  }
}
```
NVCC fails:
```
[crtrott@kokkos-dev-2 test]$ nvcc -arch=sm_70 -ccbin g++ -std=c++14 -O3 -g -Xcompiler -fopenmp -x cu main.cpp
main.cpp: In function 'int main(int, char**)':
main.cpp:6:1: error: invalid controlling predicate
    6 |   for (auto it = abc.begin(); it < abc.end(); ++it)
      | ^ ~
```

g++ works:
```
[crtrott@kokkos-dev-2 test]$ g++ -std=c++14 -O3 -g -fopenmp main.cpp
```

**Comment by crtrott** [comment]
```
[crtrott@kokkos-dev-2 test]$ g++ --version
g++ (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[crtrott@kokkos-dev-2 test]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Thu_Feb_10_18:23:41_PST_2022
Cuda compilation tools, release 11.6, V11.6.112
Build cuda_11.6.r11.6/compiler.30978841_0
```

**Comment by matt-stack** [comment]
Bug submitted to NVIDIA, will update here

**Comment by matt-stack** [comment]
Hello, this has been fixed and will be in Cuda 11.8 release. When that is available for download, please give that a try and let me know if you run into any issues. 

One thing to note, there seems to be one small bug remaining, and that is if you use the pre-increment in the for:
for (auto it = abc.begin(); it < abc.end(); ++it)

For the pre-released compiler I tested on, this gives an error "invalid increment expression". I have asked the compiler team for a fix, but I am not sure it will make it in time for Cuda 11.8.0. More likely it will be in the next minor release update after that. However, it seems to work with no issue if you use post-increment:
for (auto it = abc.begin(); it < abc.end(); it++)

**Comment by matt-stack** [comment]
Hi all, wanted to update here and report that the pre-increment issue has also been addressed and the fix will be in Cuda 12. The post-increment should work in Cuda 11.8 release. Thank you

**Comment by ajpowelsnl** [comment]
Thank you so much for the fix and the update!

**Comment by crtrott** [comment]
Closed because its user code failing to compile which hits a bug in NVCC, partial fix available in 11.8 of CUDA.
