### ISSUE TITLE
Nightly Trilinos integration build failure: cuda/11.4.2+gcc/10.1.0, Cuda backend, `TestGraph.hpp:525:117: error: no matching function for call to 'Test::FetchValuesAndContribute`...

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7316]
**Describe the bug**

Nightly Kokkos integration test builds with cuda/11.4.2+gcc/10.1.0 posting here https://trilinos-cdash.sandia.gov/build/1851535:  are failing to compile with output:

```
Standard Error 	

trilinos/workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp: In member function 'virtual void Test::serial_graph_end_of_submit_control_flow_Test::TestBody()':
[workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp:525](https://github.com/trilinos/Trilinos//blob/dbf8aaa628e8e64f33c3ec05065ff2567b8f041d/workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp#L525):117: error: no matching function for call to 'Test::FetchValuesAndContribute<Kokkos::View<int*, Kokkos::Serial>, 5, 2>::FetchValuesAndContribute(view_t&, const size_t [2], std::integral_constant<long unsigned int, 5>&, const int&)'
  525 |   Kokkos::parallel_for(
      |                                                                                                                     ^
[CTest: warning matched] [workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp:374](https://github.com/trilinos/Trilinos//blob/dbf8aaa628e8e64f33c3ec05065ff2567b8f041d/workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp#L374):1: note: candidate: 'Test::FetchValuesAndContribute<ViewType, TargetIndex, NumIndices>::FetchValuesAndContribute(ViewType, Kokkos::Array<long unsigned int, NumIndices>, std::integral_constant<long unsigned int, _Nm>, typename ViewType::value_type) [with ViewType = Kokkos::View<int*, Kokkos::Serial>; long unsigned int TargetIndex = 5; long unsigned int NumIndices = 2; typename ViewType::value_type = int]'
  374 |   FetchValuesAndContribute(ViewType data_,
      | ^ ~~~~~~~~~~~~~~~~~~~~~~
[CTest: warning matched] [workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp:375](https://github.com/trilinos/Trilinos//blob/dbf8aaa628e8e64f33c3ec05065ff2567b8f041d/workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp#L375):1: note:   no known conversion for argument 2 from 'const size_t [2]' {aka 'const long unsigned int [2]'} to 'Kokkos::Array<long unsigned int, 2, void>'
  374 |   FetchValuesAndContribute(ViewType data_,
      |                                          ~
  375 |                            Kokkos::Array<size_t, NumIndices> indices_,
      | ^       
[CTest: warning matched] [workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp:369](https://github.com/trilinos/Trilinos//blob/dbf8aaa628e8e64f33c3ec05065ff2567b8f041d/workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp#L369):1: note: candidate: 'Test::FetchValuesAndContribute<ViewType, TargetIndex, NumIndices>::FetchValuesAndContribute(ViewType, std::integral_constant<long unsigned int, _Nm>, typename ViewType::value_type) [with ViewType = Kokkos::View<int*, Kokkos::Serial>; long unsigned int TargetIndex = 5; long unsigned int NumIndices = 2; typename ViewType::value_type = int]'
  369 |   FetchValuesAndContribute(ViewType data_,
      | ^ ~~~~~~~~~~~~~~~~~~~~~~
[CTest: warning matched] [workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp:369](https://github.com/trilinos/Trilinos//blob/dbf8aaa628e8e64f33c3ec05065ff2567b8f041d/workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp#L369):1: note:   candidate expects 3 arguments, 4 provided
[CTest: warning matched] [workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp:361](https://github.com/trilinos/Trilinos//blob/dbf8aaa628e8e64f33c3ec05065ff2567b8f041d/workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp#L361):8: note: candidate: 'Test::FetchValuesAndContribute<Kokkos::View<int*, Kokkos::Serial>, 5, 2>::FetchValuesAndContribute(const Test::FetchValuesAndContribute<Kokkos::View<int*, Kokkos::Serial>, 5, 2>&)'
  361 | struct FetchValuesAndContribute {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
[CTest: warning matched] [workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp:361](https://github.com/trilinos/Trilinos//blob/dbf8aaa628e8e64f33c3ec05065ff2567b8f041d/workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp#L361):8: note:   candidate expects 1 argument, 4 provided
[CTest: warning matched] [workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp:361](https://github.com/trilinos/Trilinos//blob/dbf8aaa628e8e64f33c3ec05065ff2567b8f041d/workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp#L361):8: note: candidate: 'Test::FetchValuesAndContribute<Kokkos::View<int*, Kokkos::Serial>, 5, 2>::FetchValuesAndContribute(Test::FetchValuesAndContribute<Kokkos::View<int*, Kokkos::Serial>, 5, 2>&&)'
[CTest: warning matched] [workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp:361](https://github.com/trilinos/Trilinos//blob/dbf8aaa628e8e64f33c3ec05065ff2567b8f041d/workspace/Trilinos_nightly_pipeline/Trilinos/kokkos/core/unit_test/TestGraph.hpp#L361):8: note:   candidate expects 1 argument, 4 provided
```

with targets Kokkos_CoreUnitTest_Serial1 and Kokkos_CoreUnitTest_Cuda1

This began with changes merged between 9/5/2024 and 9/6/2024

This test is launched through the Trilinos AT testing framework, I'll need to extract a reproducer and post

**Please include the following for a minimal reproducer**

1. Compilers (with versions)
2. Kokkos release or commit used (i.e., the sha1 number)
3. Platform, architecture and backend
4. CMake configure command
5. Output from CMake configure command
6. Minimum, complete code needed to reproduce the bug
7. Command line needed to reproduce the bug
8. `KokkosCore_config.h` header file (generated during the build)
9. Please provide any additional relevant error logs

**Comment by ndellingwood** [comment]
Here is a simple Trilinos configuration reproducing the error

```
module load sems-cmake sems-gcc/10.1.0 sems-cuda/11.4.2 sems-openmpi/4.1.6 sems-openblas/0.3.12 sems-ninja

TRILINOS_DIR=$PWD/../..
#export KOKKOS_PATH=$TRILINOS_DIR/packages/kokkos
export KOKKOS_PATH=$HOME/kokkos
export OMPI_CXX=$KOKKOS_PATH/bin/nvcc_wrapper


cmake \
 -DCMAKE_BUILD_TYPE:STRING=RELEASE \
 -DCMAKE_CXX_STANDARD:STRING=17 \
 -DTPL_ENABLE_MPI=ON \
 -DTPL_ENABLE_CUDA=ON \
 -DTPL_ENABLE_BLAS:BOOL=ON \
  -DBLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -DBLAS_LIBRARY_NAMES:STRING="openblas" \
 -DTPL_ENABLE_LAPACK:BOOL=ON \
  -DLAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include" \
  -DLAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
 -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
\
 -DTrilinos_ENABLE_Kokkos:BOOL=ON \
 -DKokkos_ENABLE_TESTS:BOOL=ON \
 -DKokkos_ENABLE_CUDA:BOOL=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
$TRILINOS_DIR
```

I'll test a build with just kokkos, which should demonstrate the error as well

**Comment by ndellingwood** [comment]
Standalone kokkos reproducer:

```bash
module load sems-cmake sems-gcc/10.1.0 sems-cuda/11.4.2

cmake -DCMAKE_CXX_COMPILER=$KOKKOS_PATH/bin/nvcc_wrapper -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_VOLTA70=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF $KOKKOS_PATH
```

Nightly testing with sems-cuda/11.4.2 + sems-gcc/8.5.0 does not show the issue, so likely tickling some compiler issue with the cuda/11.4.2 + gcc/10.1.0 combo
