### PR TITLE
Fix nightlies -- workaround compiler bug in GCC 9.1 and 9.2

### LINKED ISSUE #6107: Nightly failures with in builds with gcc/9.1, 9.2 in toolchain: TestBitManipulationBuiltins.hpp: error: no matching function for call to ‘TestBitCastFunction<Space>::check...
**Describe the bug**
Nightly builds with gcc/9.1 or gcc/9.2 in the toolchain failed to compile the `TestBitManipulationBuiltins.hpp` unit test following merge of #6101  with error output:

cuda/11.7 and cuda/11.2 with gcc/9.2
```
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:812:27: error: no matching function for call to ‘TestBitCastFunction<Space>::check<int>(float) const’
09:12:03   812 |       if (!check<int>(12.34f)) {
09:12:03       |                           ^
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:792:1: note: candidate: ‘template<class Space> template<class To, class From> static bool TestBitCastFunction<Space>::check(const From&)’
09:12:03   792 |   static KOKKOS_FUNCTION bool check(const From& from) {
09:12:03       | ^ ~~~
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:792:1: note:   template argument deduction/substitution failed:
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:812:27: note:   mismatched types ‘const From’ and ‘float’
09:12:03   812 |       if (!check<int>(12.34f)) {
09:12:03       |                           ^
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:818:43: error: no matching function for call to ‘TestBitCastFunction<Space>::check<long long unsigned int>(double) const’
09:12:03   818 |       if (!check<unsigned long long>(123.456)) {
09:12:03       |                                           ^
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:792:1: note: candidate: ‘template<class Space> template<class To, class From> static bool TestBitCastFunction<Space>::check(const From&)’
09:12:03   792 |   static KOKKOS_FUNCTION bool check(const From& from) {
09:12:03       | ^ ~~~
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:792:1: note:   template argument deduction/substitution failed:
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:818:43: note:   mismatched types ‘const From’ and ‘double’
09:12:03   818 |       if (!check<unsigned long long>(123.456)) {

```

@dalg24 can you investigate?

Reproducer:
```bash
module load sems-archive-env sems-archive-cmake/3.17.1 sems-archive-gcc/9.2.0 cuda/11.7

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --with-cuda-options=enable_lambda  --no-examples   --with-options=enable_large_mem_tests
```

### PR DESCRIPTION
**Pull request by dalg24**
Resolve #6107 

I was able to reproduce with the `gcc:9.2.0` docker image and did
```
wget https://github.com/Kitware/CMake/releases/download/v3.16.8/cmake-3.16.8-Linux-x86_64.sh
mkdir -p /opt/cmake
sh cmake-3.16.8-Linux-x86_64.sh --skip-license --prefix=/opt/cmake
git clone https://github.com/kokkos/kokkos.git --branch develop --depth 1
cd kokkos/
/opt/cmake/bin/cmake -B build -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_TESTS=ON
/opt/cmake/bin/cmake --build build --target Kokkos_CoreUnitTest_OpenMP --parallel 6
```
I checked that `gcc:9.3.0` did not need the workaround.

### CODE REVIEW

File: core/unit_test/TestBitManipulationBuiltins.hpp [hunk 1]
```diff
@@ -789,7 +789,14 @@ struct TestBitCastFunction {
     ASSERT_EQ(errors, 0) << "Failed check no error for bit_cast()";
   }
   template <typename To, typename From>
-  static KOKKOS_FUNCTION bool check(const From& from) {
+#if defined(KOKKOS_COMPILER_GCC) && (910 <= KOKKOS_COMPILER_GCC) && \
+    (KOKKOS_COMPILER_GCC < 930)
```
Comment (masterleinad) [inline core/unit_test/TestBitManipulationBuiltins.hpp:793]: AFAICT `KOKKOS_COMPILER_GCC` doesn't exist.
```suggestion
#if defined(KOKKOS_COMPILER_GNU) && (910 <= KOKKOS_COMPILER_GNU) && \
    (KOKKOS_COMPILER_GNU < 930)
```

**Review by masterleinad — APPROVED** [review]

File: core/unit_test/TestBitManipulationBuiltins.hpp [hunk 2]
```diff
@@ -789,7 +789,14 @@ struct TestBitCastFunction {
     ASSERT_EQ(errors, 0) << "Failed check no error for bit_cast()";
   }
   template <typename To, typename From>
-  static KOKKOS_FUNCTION bool check(const From& from) {
+#if defined(KOKKOS_COMPILER_GNU) && (910 <= KOKKOS_COMPILER_GNU) && \
```
Comment (ndellingwood) [inline core/unit_test/TestBitManipulationBuiltins.hpp:792]: I tested SHA 6b8f4736d41eef8e2e66fd2455efd4c115e2124f with the systems gcc/9.1 module, which turned out to be misnamed and really should have been gcc/9.0.1

@dalg24 With gcc/9.0.1 the compilation error is present, can the compiler check be updated to guard for gcc/9.0 as well?

```
[ndellin@kokkos-dev-2 Gcc9.1]$ g++ --version
g++ (GCC) 9.0.1 20190428 (prerelease)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
/ascldap/users/ndellin/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp: In member function ‘void TestBitCastFunction<Space>::operator()(int, int&) const’:
/ascldap/users/ndellin/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:819:29: error: no matching function for call to ‘TestBitCastFunction<Space>::check<int>(float) const’
  819 |       if (!check<int>(12.34f)) {
      |                             ^

```

Including `900` in the guard resolved the compilation error (I'm assuming the error will be present on 9.0.0 as well)

```suggestion
#if defined(KOKKOS_COMPILER_GNU) && (900 <= KOKKOS_COMPILER_GNU) && \
```

File: core/unit_test/TestBitManipulationBuiltins.hpp [hunk 3]
```diff
@@ -789,7 +789,14 @@ struct TestBitCastFunction {
     ASSERT_EQ(errors, 0) << "Failed check no error for bit_cast()";
   }
   template <typename To, typename From>
-  static KOKKOS_FUNCTION bool check(const From& from) {
+#if defined(KOKKOS_COMPILER_GNU) && (900 <= KOKKOS_COMPILER_GNU) && \
+    (KOKKOS_COMPILER_GNU < 930)
+  // workaround compiler bug in GCC 9.1 and GCC 9.2
```
Comment (dalg24) [inline core/unit_test/TestBitManipulationBuiltins.hpp:794]:
```suggestion
  // workaround compiler bug seen in GCC 9.0.1 and GCC 9.2.0
```

**Review by ndellingwood — APPROVED** [review]
Thanks @dalg24 !

**Review by ajpowelsnl — APPROVED** [review]

**Comment by dalg24** [comment]
HIP builds timed out.  Nathan confirmed that resolves the issue.  Merging.
