### ISSUE TITLE
Nightly Trilinos build errors, cuda/11.8.0, Stokhos package

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7415]
**Describe the bug**

Nightly Trilinos builds with cuda/11.8.0 failed to compile in the Stokhos package, where in this particular job kokkos was built as an external TPL:
```
03:49:25 /home/jenkins/jenkins-new/workspace/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/Trilinos/packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp(131): error: incomplete type is not allowed
03:49:25           detected during:
03:49:25             instantiation of "auto Kokkos::create_mirror(const Kokkos::Impl::ViewCtorProp<ViewCtorArgs...> &, const Kokkos::View<T, P...> &, std::enable_if_t<std::is_same_v, void> *) [with T=Sacado::MP::Vector<Tpetra::SFS_int_double_16_DFN_CPU_default_local_ordinal_type_default_global_ordinal_type_Tpetra_KokkosCompat_KokkosCudaWrapperNode> **, P=<Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, void>, ViewCtorArgs=<Kokkos::Impl::WithoutInitializing_t, Kokkos::HostSpace::memory_space>]" 
03:49:25 (182): here
03:49:25             instantiation of "auto Kokkos::create_mirror(Kokkos::Impl::WithoutInitializing_t, const Space &, const Kokkos::View<T, P...> &, std::enable_if_t<std::is_same_v, void> *) [with Space=Kokkos::HostSpace::memory_space, T=Sacado::MP::Vector<Tpetra::SFS_int_double_16_DFN_CPU_default_local_ordinal_type_default_global_ordinal_type_Tpetra_KokkosCompat_KokkosCudaWrapperNode> **, P=<Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, void>, Enable=void]" 
03:49:25 /home/jenkins/jenkins-new/workspace/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/Build/install_kokkos/include/Kokkos_CopyViews.hpp(3585): here
03:49:25             instantiation of "auto Kokkos::Impl::choose_create_mirror(const View &, const Kokkos::Impl::ViewCtorProp<ViewCtorArgs...> &) [with View=Kokkos::View<Sacado::MP::Vector<Tpetra::SFS_int_double_16_DFN_CPU_default_local_ordinal_type_default_global_ordinal_type_Tpetra_KokkosCompat_KokkosCudaWrapperNode> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, void>, ViewCtorArgs=<Kokkos::HostSpace::memory_space, Kokkos::Impl::WithoutInitializing_t>]" 
03:49:25 /home/jenkins/jenkins-new/workspace/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/Build/install_kokkos/include/Kokkos_CopyViews.hpp(3630): here
03:49:25             instantiation of "auto Kokkos::Impl::create_mirror_view(const Kokkos::View<T, P...> &, const Kokkos::Impl::ViewCtorProp<ViewCtorArgs...> &) [with T=Sacado::MP::Vector<Tpetra::SFS_int_double_16_DFN_CPU_default_local_ordinal_type_default_global_ordinal_type_Tpetra_KokkosCompat_KokkosCudaWrapperNode> **, P=<Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, void>, ViewCtorArgs=<Kokkos::HostSpace::memory_space, Kokkos::Impl::WithoutInitializing_t>]" 
03:49:25 /home/jenkins/jenkins-new/workspace/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/Build/install_kokkos/include/Kokkos_CopyViews.hpp(3668): here
03:49:25             instantiation of "auto Kokkos::create_mirror_view(Kokkos::Impl::WithoutInitializing_t, const Space &, const Kokkos::View<T, P...> &) [with Space=Kokkos::HostSpace::memory_space, T=Sacado::MP::Vector<Tpetra::SFS_int_double_16_DFN_CPU_default_local_ordinal_type_default_global_ordinal_type_Tpetra_KokkosCompat_KokkosCudaWrapperNode> **, P=<Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, void>, Enable=void]" 
03:49:25 /home/jenkins/jenkins-new/workspace/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/Trilinos/packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp(181): here
03:49:25             instantiation of "Tpetra::Details::WrappedDualView<DualViewType>::WrappedDualView(Tpetra::Details::WrappedDualView<DualViewType>::t_dev) [with DualViewType=Kokkos::DualView<Sacado::MP::Vector<Tpetra::SFS_int_double_16_DFN_CPU_default_local_ordinal_type_default_global_ordinal_type_Tpetra_KokkosCompat_KokkosCudaWrapperNode> **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, void>]" 
03:49:25 /home/jenkins/jenkins-new/workspace/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp(192): here
03:49:25             instantiation of "Tpetra::MultiVector<ST, LO, GO, NT>::wrapped_dual_view_type <unnamed>::allocDualView<ST,LO,GO,NT>(size_t, size_t, __nv_bool, __nv_bool) [with ST=Sacado::MP::Vector<Tpetra::SFS_int_double_16_DFN_CPU_default_local_ordinal_type_default_global_ordinal_type_Tpetra_KokkosCompat_KokkosCudaWrapperNode>, LO=Tpetra::default_local_ordinal_type, GO=Tpetra::default_global_ordinal_type, NT=Tpetra::Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
03:49:25 /home/jenkins/jenkins-new/workspace/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp(437): here
03:49:25             instantiation of "Tpetra::MultiVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>::MultiVector(const Teuchos::RCP<const Tpetra::MultiVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>::map_type> &, size_t, __nv_bool) [with Scalar=Sacado::MP::Vector<Tpetra::SFS_int_double_16_DFN_CPU_default_local_ordinal_type_default_global_ordinal_type_Tpetra_KokkosCompat_KokkosCudaWrapperNode>, LocalOrdinal=Tpetra::default_local_ordinal_type, GlobalOrdinal=Tpetra::default_global_ordinal_type, Node=Tpetra::Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
03:49:25 /home/jenkins/jenkins-new/workspace/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/Build/Build_Trilinos/packages/stokhos/src/Tpetra_MultiVector_MP_Vector_16_Cuda.cpp(18): here
...
```

This began occurring after merge of these commits (likely related to #7339):

**Changes**

Git (git https://github.com/kokkos/kokkos.git)

    Bump actions/cache from 4.0.2 to 4.1.0 ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/133/changes#detail))
    Bump github/codeql-action from 3.26.9 to 3.26.11 ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/133/changes#detail))
    graph: allow access to native graph object ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/133/changes#detail))
    Use hipMallocAsync when using HIP execution space (#7324) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/133/changes#detail))
    Refactor: Remove unnecessary `Mirror*Types` structs (#7339) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_AsTPLs_Trilinos_KokkosDev2_SemsCuda1180-nouvm/133/changes#detail))

**Please include the following for a minimal reproducer**

**Reproducer notes** (kokkos-dev-2):
```bash
# Repo prep
git clone -b develop https://github.com/trilinos/Trilinos.git
TRILINOS_DIR=$PWD/Trilinos
git clone -b develop https://github.com/kokkos/kokkos.git
KOKKOS_DIR=$PWD/kokkos
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
KOKKOSKERNELS_DIR=$PWD/kokkos-kernels

# Create Kokkos, KokkosKernels, and Trilinos Build dirs
export BUILDDIR=${WORKDIR}/Build
mkdir -p $BUILDDIR
cd $BUILDDIR

export KOKKOS_BUILD=$BUILDDIR/Build_Kokkos
mkdir -p $KOKKOS_BUILD
export KOKKOSKERNELS_BUILD=$BUILDDIR/Build_KokkosKernels
mkdir -p $KOKKOSKERNELS_BUILD
export TRILINOS_BUILD=$BUILDDIR/Build_Trilinos
mkdir -p $TRILINOS_BUILD

# Environment
module load sems-gcc/11.4.0 sems-cuda/11.8.0 sems-openmpi/4.1.6 sems-cmake sems-openblas/0.3.26 sems-git sems-ninja
export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper

# Configure and install Kokkos
export KOKKOS_INSTALL=$BUILDDIR/install_kokkos
mkdir -p $KOKKOS_INSTALL
cd $KOKKOS_BUILD
echo "Configuring Kokkos in directory: $PWD"
cmake \
  -D CMAKE_CXX_COMPILER="$(which mpicxx)" \
  -D CMAKE_C_COMPILER="$(which mpicc)" \
  -D CMAKE_INSTALL_PREFIX=$KOKKOS_INSTALL \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D BUILD_SHARED_LIBS:BOOL=OFF \
\
  -D Kokkos_ENABLE_SERIAL=ON \
  -D Kokkos_ENABLE_CUDA=ON \
   -D Kokkos_ENABLE_TESTS=OFF \
  -D Kokkos_ARCH_VOLTA70=ON \
  -D Kokkos_ENABLE_COMPLEX_ALIGN=OFF \
  -DKokkos_ENABLE_IMPL_MDSPAN=OFF \
$KOKKOS_DIR
make install -j12

# Configure and install KokkosKernels
export KOKKOSKERNELS_INSTALL=$BUILDDIR/install_kokkos-kernels
mkdir -p $KOKKOSKERNELS_INSTALL
cd $KOKKOSKERNELS_BUILD
echo "Configuring KokkosKernels in directory: $PWD"
cmake \
  -D CMAKE_CXX_COMPILER="$(which mpicxx)" \
  -D CMAKE_C_COMPILER="$(which mpicc)" \
  -D CMAKE_INSTALL_PREFIX=$KOKKOSKERNELS_INSTALL \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D BUILD_SHARED_LIBS:BOOL=OFF \
\
  -D Kokkos_ROOT=$KOKKOS_INSTALL \
\
  -D KokkosKernels_INST_COMPLEX_DOUBLE=ON \
  -D KokkosKernels_INST_OFFSET_INT=OFF \
  -D KokkosKernels_INST_OFFSET_SIZE_T=ON \
  -D KokkosKernels_ENABLE_TESTS=OFF \
  -D KokkosKernels_ENABLE_TPL_BLAS=ON \
  -D KokkosKernels_ENABLE_TPL_LAPACK=ON \
  -D KokkosKernels_ENABLE_TPL_CUSPARSE=ON \
  -D KokkosKernels_ENABLE_TPL_CUBLAS=ON \
$KOKKOSKERNELS_DIR
make install -j12

# Configure Trilinos using Kokkos and KokkosKernels as TPLs
export TRILINOS_INSTALL=$BUILDDIR/install_trilinos
cd $TRILINOS_BUILD
rm -r CMake*
echo "Configuring Trilinos in directory: $PWD"
cmake \
  -D CMAKE_CXX_COMPILER="$(which mpicxx)" \
  -D CMAKE_C_COMPILER="$(which mpicc)" \
  -D CMAKE_Fortran_COMPILER="$(which mpifort)" \
  -D CMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL}" \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D BUILD_SHARED_LIBS:BOOL=OFF \
  -DTPL_ENABLE_MPI=ON \
  -DTPL_ENABLE_CUDA=ON \
  -DTPL_ENABLE_BLAS:STRING=ON \
   -DBLAS_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
   -DBLAS_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_LAPACK:STRING=ON \
   -DLAPACK_INCLUDE_DIRS:FILEPATH="$OPENBLAS_ROOT/include" \
   -DLAPACK_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
   -DLAPACK_LIBRARY_NAMES:STRING="openblas" \
  -DTPL_ENABLE_CUSPARSE:BOOL=ON \
  -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
  -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
  -DTrilinos_ENABLE_COMPLEX=ON \
  -DTrilinos_ENABLE_OpenMP=OFF \
\
  -DTPL_ENABLE_Kokkos=ON \
  -DTPL_ENABLE_KokkosKernels=ON \
  -D "CMAKE_PREFIX_PATH=${KOKKOS_INSTALL};${KOKKOSKERNELS_INSTALL}" \
  -DTpetra_IGNORE_KOKKOS_COMPATIBILITY=ON \
\
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Sacado=ON \
   -D Sacado_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Stokhos=ON \
   -D Stokhos_ENABLE_TESTS=ON \
\
  -DTPL_ENABLE_Matio=OFF \
\
  -DTrilinos_ENABLE_INSTALLATION_TESTING=OFF \
$TRILINOS_DIR

make -j16

export TPETRA_ASSUME_GPU_AWARE_MPI=0
ctest --output-on-failure
```

**Comment by pzehner** [comment]
I could reproduce the bug. In [this file](https://github.com/trilinos/Trilinos/blob/a90610d696683a548a5fc25059b3cbfe0d4bf7c0/packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp#L131), you use `Kokkos::Impl::MirrorType` which was deleted by #7339. This is an implementation detail struct, why are you using it?

**Comment by dalg24** [comment]
See https://github.com/kokkos/kokkos/issues/7413#issuecomment-2402196055
Not a bug in Kokkos

**Comment by ndellingwood** [comment]
@pzehner I believe the use is long-standing carry over of various View customization details, overdue for an update

**Comment by dalg24** [comment]
I expect it is resolved by https://github.com/trilinos/Trilinos/pull/13521
