### ISSUE TITLE
CUDA occupancy compilation error with Kokkos 4.2

### ISSUE THREAD

**Issue by aprokop** [kokkos/kokkos#6780]
**Describe the bug**

Setting occupancy seems to be broken in Kokkos 4.2 for the code that worked in Kokkos 4.1

**Please include the following for a minimal reproducer**

The following code worked in Kokkos 4.1 with Cuda but is broken in 4.2:
```c++
#include <Kokkos_Core.hpp>
int main(int argc, char *argv[]) {
  Kokkos::ScopeGuard guard(argc, argv);
  using ExecutionSpace = Kokkos::Cuda;
  Kokkos::parallel_for("blah",
    Kokkos::Experimental::prefer(
      Kokkos::RangePolicy<ExecutionSpace>(ExecutionSpace{}, 0, 10),
      Kokkos::Experimental::DesiredOccupancy{75}),
    KOKKOS_LAMBDA(int) {/* do nothing */}
  );
  return 0;
}
```
Using nvcc/11.5 with 4.1.00 and 4.2.00.

The error message is
```
kokkos-4.2.0/include/Cuda/Kokkos_Cuda_Instance.hpp(512): error:
  identifier "cudaFuncSetAttributes" is undefined
```

**Comment by masterleinad** [comment]
Broken in https://github.com/kokkos/kokkos/commit/4d8629f26c should be `cudaFuncSetAttribute` instead of `cudaFuncSetAttributes`.

**Comment by masterleinad** [comment]
A fix with test should look somewhat like
```C++
diff --git a/core/src/Cuda/Kokkos_Cuda_Instance.hpp b/core/src/Cuda/Kokkos_Cuda_Instance.hpp
index db764fb1b..660ef308b 100644
--- a/core/src/Cuda/Kokkos_Cuda_Instance.hpp
+++ b/core/src/Cuda/Kokkos_Cuda_Instance.hpp
@@ -449,10 +449,10 @@ class CudaInternal {
   }
 
   template <typename T, bool setCudaDevice = true>
-  cudaError_t cuda_func_set_attributes_wrapper(T* entry, cudaFuncAttribute attr,
+  cudaError_t cuda_func_set_attribute_wrapper(T* entry, cudaFuncAttribute attr,
                                                int value) const {
     if constexpr (setCudaDevice) set_cuda_device();
-    return cudaFuncSetAttributes(entry, attr, value);
+    return cudaFuncSetAttribute(entry, attr, value);
   }
 
   template <bool setCudaDevice = true>
diff --git a/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp b/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp
index 0dbe40d89..5661d49dd 100644
--- a/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp
+++ b/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp
@@ -222,7 +222,7 @@ inline void configure_shmem_preference(const KernelFuncPtr& func,
   // FIXME_CUDA_MULTIPLE_DEVICES
   auto set_cache_config = [&] {
     KOKKOS_IMPL_CUDA_SAFE_CALL(
-        (CudaInternal::singleton().cuda_func_set_attributes_wrapper(
+        (CudaInternal::singleton().cuda_func_set_attribute_wrapper(
             func, cudaFuncAttributePreferredSharedMemoryCarveout, carveout)));
     return carveout;
   };
diff --git a/core/unit_test/TestCommonPolicyConstructors.hpp b/core/unit_test/TestCommonPolicyConstructors.hpp
index ec5d1ae0f..24a58575f 100644
--- a/core/unit_test/TestCommonPolicyConstructors.hpp
+++ b/core/unit_test/TestCommonPolicyConstructors.hpp
@@ -85,6 +85,13 @@ void test_prefer_desired_occupancy() {
       prefer(policy_with_occ_and_hint, MaximizeOccupancy{});
   static_assert(
       !decltype(policy_drop_occ)::experimental_contains_desired_occupancy);
+
+  if constexpr(std::is_same_v<Policy, Kokkos::RangePolicy<>>)
+    Kokkos::parallel_for(policy_with_occ, KOKKOS_LAMBDA(int) {});
+  if constexpr(std::is_same_v<Policy, Kokkos::TeamPolicy<>>)
+    Kokkos::parallel_for(policy_with_occ, KOKKOS_LAMBDA(const Kokkos::TeamPolicy<>::member_type&) {});
+  if constexpr(std::is_same_v<Policy, Kokkos::MDRangePolicy<Kokkos::Rank<2>>>)
+    Kokkos::parallel_for(policy_with_occ, KOKKOS_LAMBDA(int, int) {});
 }
 
 TEST(TEST_CATEGORY, execution_policy_occupancy_and_hint) {
```
