### PR TITLE
Fix TestNumericTriats.hpp for SYCL with bfloat16 support

### LINKED ISSUE #6607: SYCL build failures for PV, intel/oneapi/2023.1.0: error: cannot convert 'const ...floating_point_wrapper<sycl::ext::oneapi::bfloat16>>' to 'float' without a conversion operator
**Describe the bug**
The nightly SYCL build with intel/oneapi/2023.1.0 is failing to compile due to conversion issues between bfloat half types and float with output:
```
01:30:11 /projects/x86-64-icelake-rocky8/compilers/intel-oneapi-compilers/2023.1.0/gcc/8.5.0/base/6g2jkiv/compiler/2023.1.0/linux/bin-llvm/../include/sycl/ext/oneapi/bfloat16.hpp:198:3: error: cannot convert 'const Kokkos::Experimental::Impl::BitComparisonWrapper<Kokkos::Experimental::Impl::floating_point_wrapper<sycl::ext::oneapi::bfloat16>>' to 'float' without a conversion operator
01:30:11   OP(bfloat16, /)
01:30:11   ^~~~~~~~~~~~~~~
01:30:11 /projects/x86-64-icelake-rocky8/compilers/intel-oneapi-compilers/2023.1.0/gcc/8.5.0/base/6g2jkiv/compiler/2023.1.0/linux/bin-llvm/../include/sycl/ext/oneapi/bfloat16.hpp:193:17: note: expanded from macro 'OP'
01:30:11     return type{static_cast<float>(lhs) op static_cast<float>(rhs)};           \
01:30:11                 ^~~~~~~~~~~~~~~~~~~~~~~
01:30:11 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestNumericTraits.hpp:118:27: note: in instantiation of function template specialization 'sycl::ext::oneapi::operator/<Kokkos::Experimental::Impl::BitComparisonWrapper<Kokkos::Experimental::Impl::floating_point_wrapper<sycl::ext::oneapi::bfloat16>>>' requested here
01:30:11     compare() = one + eps / 2;
01:30:11                           ^
01:30:11 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/src/SYCL/Kokkos_SYCL_ParallelReduce_Range.hpp:111:15: note: in instantiation of member function 'TestNumericTraits<Kokkos::Experimental::SYCL, Kokkos::Experimental::Impl::floating_point_wrapper<sycl::ext::oneapi::bfloat16>, Epsilon>::operator()' requested here
01:30:11               functor(WorkTag(), begin, update);
...
```

This likely follows from #6590 , @dalg24 or @masterleinad can you give guidance?

**Please also include the following items to support reproducing the bug**
Reproducer (blake PV queue):
```bash
salloc -N 1 -p PV

module load cmake intel-oneapi-compilers/2023.1.0 intel-oneapi-dpl/2022.1.0 git

$KOKKOS_PATH/generate_makefile.bash --with-sycl --arch=INTEL_PVC --compiler=icpx --cxxflags="-fp-model=precise" --cmake-flags=-DKokkos_ENABLE_ONEDPL=OFF

make -j
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #6607. The problem is that the compiler provided overloads
```
[...]
  template <typename T>                                                        \
  friend type operator op(const T &lhs, const bfloat16 &rhs) {                 \
    return type{static_cast<float>(lhs) op static_cast<float>(rhs)};           \
  }
  OP(bfloat16, +)
  OP(bfloat16, -)
  OP(bfloat16, *)
  OP(bfloat16, /)
[...]
```
are the best match for
```
eps / 2;
```
when eps has type `BitComparisonWrapper<...>`. Just fixing the tests to cast `epsilon` to `bhalf_t` seems to be the easiest fix. Ultimately, this issue is similar to the problems we are seeing for comparisons where we ultimately added these for `BitComparisonWrapper<...>`. Duplicating all operators and math functions for that type doesn't seem feasible and thus this pull request just proposes to fix the test and we should probably note in the documentation that we are returning an `impl_type` that is supposed to be cast to `half_t` before doing anything else with it.

### CODE REVIEW

**Comment by masterleinad** [comment]
We are getting ambiguous overloads either if we use
```
eps / 2.
```
instead (since we provide a templated overload) or if we define a
```
operator/(floating_point_wrapper, int)
```
overload. So apart from the workaround here, we could revert #6590 (although we would still have the same issues for `nan`, `quiet_NaN`, and `signaling_NaN`) or implement all kinds of operators for `BitComparisonWrapper`.

**Comment by masterleinad** [comment]
Going forward, it might be a good idea to replace all these constants with `Kokkos::numeric_limits<T>::constant()` functions that could be non-`constexpr` for the `[b]float` types. In that case, we can return the correct type.

**Review by ndellingwood — APPROVED** [review]
These changes got me past the compilation errors in #6607 , thanks @masterleinad !
Unrelated to this PR but hopefully worth sharing, I'm seeing lots of warnings to replace `bit_cast` with a namespaced version `sycl::bit_cast` , e.g. 
```
/home/ndellin/kokkos/core/src/impl/Kokkos_Half_MathematicalFunctions.hpp:211:34: warning: 'bit_cast<Kokkos::Experimental::Impl::BitComparisonWrapper<Kokkos::Experimental::Impl::floating_point_wrapper<sycl::detail::half_impl::half>>, sycl::detail::half_impl::half>' is deprecated: use 'sycl::bit_cast' instead [-Wdeprecated-declarations]
  const bit_type bit_pattern_x = bit_cast<bit_type>(
                                 ^
/projects/x86-64-icelake-rocky8/compilers/intel-oneapi-compilers/2023.1.0/gcc/8.5.0/base/6g2jkiv/compiler/2023.1.0/linux/bin-llvm/../include/sycl/bit_cast.hpp:56:1: note: 'bit_cast<Kokkos::Experimental::Impl::BitComparisonWrapper<Kokkos::Experimental::Impl::floating_point_wrapper<sycl::detail::half_impl::half>>, sycl::detail::half_impl::half>' has been explicitly marked deprecated here
__SYCL2020_DEPRECATED("use 'sycl::bit_cast' instead")
...
```

**Comment by masterleinad** [comment]
> Unrelated to this PR but hopefully worth sharing, I'm seeing lots of warnings to replace `bit_cast` with a namespaced version `sycl::bit_cast` , e.g.

Yeah, we already have a version check for that. The warnings should disappear for the `oneAPI 2024.0.0` release.

**Review by ndellingwood — DISMISSED** [review]
@masterleinad the build took awhile, once it made it through`Kokkos_CoreUnitTest_SYCL1A` I ran into more compilation errors:

```
/projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h:65:21: error: constexpr variable '__mask' must be initialized by a constant expression
    constexpr _UInt __mask = (__is_ascending) ? 1 << ::std::numeric_limits<_Int>::digits : ~_UInt(0) >> 1;
                    ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h:200:34: note: in instantiation of function template specialization 'oneapi::dpl::__par_backend_hetero::__order_preserving_cast<true, long long, 0>' requested here
                    auto __val = __order_preserving_cast<__is_ascending>(__val_rng[__val_idx]);
                                 ^
/projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h:614:37: note: in instantiation of function template specialization 'oneapi::dpl::__par_backend_hetero::__radix_sort_count_submit<oneapi::dpl::__par_backend_hetero::__internal::__composite<oneapi::dpl::__par_backend_hetero::__radix_sort_count_kernel<4, true, true>, '_', 'Z', 'T', 'S', 'N', '6', 'o', 'n', 'e', 'a', 'p', 'i', '3', 'd', 'p', 'l', '2', '0', '_', '_', 'p', 'a', 'r', '_', 'b', 'a', 'c', 'k', 'e', 'n', 'd', '_', 'h', 'e', 't', 'e', 'r', 'o', '2', '5', '_', '_', 'r', 'a', 'd', 'i', 'x', '_', 's', 'o', 'r', 't', '_', 'c', 'o', 'u', 'n', 't', '_', 'k', 'e', 'r', 'n', 'e', 'l', 'I', 'L', 'j', '4', 'E', 'L', 'b', '1', 'E', 'L', 'b', '1', 'E', 'J', 'N', 'S', '0', '_', '9', 'e', 'x', 'e', 'c', 'u', 't', 'i', 'o', 'n', '5', '_', '_', 'd', 'p', 'l', '1', '7', 'D', 'e', 'f', 'a', 'u', 'l', 't', 'K', 'e', 'r', 'n', 'e', 'l', 'N', 'a', 'm', 'e', 'E', 'N', 'S', '0', '_', '8', '_', '_', 'r', 'a', 'n', 'g', 'e', 's', '1', '0', 'g', 'u', 'a', 'r', 'd', '_', 'v', 'i', 'e', 'w', 'I', 'P', 'x', 'E', 'E', 'N', '4', 's', 'y', 'c', 'l', '3', '_', 'V', '1', '6', 'b', 'u', 'f', 'f', 'e', 'r', 'I', 'j', 'L', 'i', '1', 'E', 'N', 'S', 'B', '_', '6', 'd', 'e', 't', 'a', 'i', 'l', '1', '7', 'a', 'l', 'i', 'g', 'n', 'e', 'd', '_', 'a', 'l', 'l', 'o', 'c', 'a', 't', 'o', 'r', 'I', 'j', 'E', 'E', 'v', 'E', 'E', 'E', 'E', 'E'>, 4U, true, oneapi::dpl::execution::device_policy<> &, oneapi::dpl::__ranges::guard_view<long long *>, sycl::buffer<unsigned int, 1, sycl::detail::aligned_allocator<unsigned int>, void>, sycl::kernel>' requested here
        sycl::event __count_event = __radix_sort_count_submit<_RadixCountKernel, __radix_bits, __is_ascending>(
                                    ^
/projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h:760:105: note: in instantiation of function template specialization 'oneapi::dpl::__par_backend_hetero::__parallel_radix_sort_iteration<4, true, true>::submit<oneapi::dpl::execution::device_policy<> &, oneapi::dpl::__ranges::guard_view<long long *>, oneapi::dpl::__ranges::all_view<long long, sycl::access::mode::read_write, sycl::access::target::global_buffer, sycl::access::placeholder::true_t> &, sycl::buffer<unsigned int, 1, sycl::detail::aligned_allocator<unsigned int>, void>>' requested here
                __event = __parallel_radix_sort_iteration<__radix_bits, __is_ascending, /*even=*/true>::submit(
                                                                                                        ^
/projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/glue_algorithm_impl.h:656:30: note: in instantiation of function template specialization 'oneapi::dpl::__internal::__pattern_sort<oneapi::dpl::execution::device_policy<> &, long long *, oneapi::dpl::__internal::__pstl_less>' requested here
    oneapi::dpl::__internal::__pattern_sort(
                             ^
/projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/glue_algorithm_impl.h:667:18: note: in instantiation of function template specialization 'oneapi::dpl::sort<oneapi::dpl::execution::device_policy<> &, long long *, oneapi::dpl::__internal::__pstl_less>' requested here
    oneapi::dpl::sort(::std::forward<_ExecutionPolicy>(__exec), __first, __last,
                 ^
/home/ndellin/kokkos/algorithms/unit_tests/../src/sorting/./impl/Kokkos_SortImpl.hpp:221:16: note: in instantiation of function template specialization 'oneapi::dpl::sort<oneapi::dpl::execution::device_policy<> &, long long *>' requested here
  oneapi::dpl::sort(policy, view.data(), view.data() + n,
               ^
/home/ndellin/kokkos/algorithms/unit_tests/../src/sorting/./impl/Kokkos_SortImpl.hpp:292:5: note: in instantiation of function template specialization 'Kokkos::Impl::sort_onedpl<long long *, Kokkos::Experimental::SYCL>' requested here
    sort_onedpl(exec, view);
    ^
/home/ndellin/kokkos/algorithms/unit_tests/../src/sorting/Kokkos_SortPublicAPI.hpp:59:11: note: in instantiation of function template specialization 'Kokkos::Impl::sort_device_view_without_comparator<long long *, Kokkos::Experimental::SYCL>' requested here
    Impl::sort_device_view_without_comparator(exec, view);
          ^
/home/ndellin/kokkos/algorithms/unit_tests/TestSort.hpp:179:11: note: in instantiation of function template specialization 'Kokkos::sort<Kokkos::Experimental::SYCL, long long *, Kokkos::Experimental::SYCL>' requested here
  Kokkos::sort(exec, element_);
```

**Comment by ndellingwood** [comment]
> the build took awhile, once it made it through`Kokkos_CoreUnitTest_SYCL1A` I ran into more compilation

ug, typo in my cmake line to disable onedpl, sorry. Rebuilding...

**Review by ndellingwood — APPROVED** [review]

**Comment by dalg24** [comment]
The fix you propose looks good to me but why is it only failing with SYCL?  I expected we'd see it with CUDA too.
https://github.com/kokkos/kokkos/blob/aa2ff89fbf30d33627c1648c6aa39404ac8e7c0b/core/unit_test/TestNumericTraits.hpp#L221-L224

**Comment by masterleinad** [comment]
> The fix you propose looks good to me but why is it only failing with SYCL? I expected we'd see it with CUDA too.

The overload selected for `Cuda` is
```
__device__ __forceinline__ __half operator/(const __half &lh, const __half &rh) { return __hdiv(lh, rh); }
```

**Comment by masterleinad** [comment]
If we don't provide better `operator/` overloads ourselves, it all depends on the compiler implementation which overload is selected and which implicit conversions are performed and those turn out to be unsuitable for `SYCL`.

**Review by crtrott — APPROVED** [review]
