### PR TITLE
Add test for current CTAD support with RangePolicy

### PR DESCRIPTION
**Pull request by dalg24**
Extracted from #5517
Intended as a base for discussion when adding deduction guides in a follow up PR.

Adding a compile-only test to showcase what currently works before we make changes.

### CODE REVIEW

**Comment by dalg24** [comment]
Retest this please

**Comment by ajpowelsnl** [comment]
- @nliber - this PR is relevant to #5257

**Comment by ndellingwood** [comment]
Testing with intel/19.0.5 icpc compiler (which has some issues with ctad related usage) produced some errors:
```
/ascldap/users/ndellin/kokkos/core/unit_test/TestRangePolicyCTAD.cpp(30): error #177: member "<unnamed>::TestRangePolicyCTAD::nes" was declared but never referenced
        nes;
        ^

/ascldap/users/ndellin/kokkos/core/unit_test/TestRangePolicyCTAD.cpp(32): error #177: member "<unnamed>::TestRangePolicyCTAD::i64" was declared but never referenced
    [[maybe_unused]] static inline int64_t i64;
                                           ^

/ascldap/users/ndellin/kokkos/core/unit_test/TestRangePolicyCTAD.cpp(33): error #177: member "<unnamed>::TestRangePolicyCTAD::i32" was declared but never referenced
    [[maybe_unused]] static inline int32_t i32;
                                           ^

/ascldap/users/ndellin/kokkos/core/unit_test/TestRangePolicyCTAD.cpp(23): error #177: function "<unnamed>::TestRangePolicyCTAD::ImplicitlyConvertibleToDefaultExecutionSpace::operator Kokkos::DefaultExecutionSpace" was declared but never referenced
      [[maybe_unused]] operator Kokkos::DefaultExecutionSpace() const;
```

**Comment by dalg24** [comment]
How about now?

**Comment by ndellingwood** [comment]
@dalg24 looks like some issues remain (or were masked before your recent push)
```
/ascldap/users/ndellin/kokkos/core/unit_test/TestRangePolicyCTAD.cpp(32): error #177: function "<unnamed>::TestRangePolicyCTAD::ImplicitlyConvertibleToDefaultExecutionSpace::operator Kokkos::DefaultExecutionSpace" was declared but never referenced
      [[maybe_unused]] operator Kokkos::DefaultExecutionSpace() const;
```

**Comment by nliber** [comment]
@ndellingwood I think I got rid of the declared but never referenced warning.

**Comment by ndellingwood** [comment]
@nliber looks like it worked with intel/19.0.5 icpc 👍

**Comment by pzehner** [comment]
I tested it successfully using the Intel compiler version 2024.0.2 targeting the PVC (GPU Max 1550) architecture.
CMake flags were `-DKokkos_ARCH_INTEL_PVC=ON -DKokkos_ENABLE_COMPILER_WARNINGS=ON -DKokkos_ENABLE_DEBUG=ON -DKokkos_ENABLE_SYCL=ON -DKokkos_ENABLE_TESTS=ON -DCMAKE_CXX_COMPILER=icpx -DCMAKE_CXX_FLAGS="-fp-model=precise"`, on `Release` and `Debug` modes.

**Review by masterleinad — COMMENTED** [review]
Any good reason not to use `TEST_EXECSPACE` instead of `Kokkos::DefaultExecutionSace` aka `des`?

**Comment by dalg24** [comment]
> Any good reason not to use `TEST_EXECSPACE` instead of `Kokkos::DefaultExecutionSace` aka `des`?

`TEST_EXECSPACE` is not defined for compile-only tests.

File: core/unit_test/TestRangePolicyCTAD.cpp [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+
+  KOKKOS_TEST_RANGE_POLICY(Kokkos::RangePolicy<>, i64, i64, cs);
+  KOKKOS_TEST_RANGE_POLICY(Kokkos::RangePolicy<>, i64, i32, cs);
+  KOKKOS_TEST_RANGE_POLICY(Kokkos::RangePolicy<>, i32, i64, cs);
+  KOKKOS_TEST_RANGE_POLICY(Kokkos::RangePolicy<>, i32, i32, cs);
+
+  // RangePolicy(execution_space, index_type, index_type)
+
+  // none (ambiguous deduction for template arguments)
+
```
Comment (masterleinad) [inline core/unit_test/TestRangePolicyCTAD.cpp:73]: This should work after https://github.com/kokkos/kokkos/pull/6841 but I don't care much if we merge this one first and then update the test in the other pull request or the other way around.

Comment (dalg24) [reply core/unit_test/TestRangePolicyCTAD.cpp:73]: This PR was about understanding current support.
I had not realized that CTAD worked when passing a leading execution space argument with GCC but I am not sure it is worth including here.

Comment (masterleinad) [reply core/unit_test/TestRangePolicyCTAD.cpp:73]: I can confirm that #6841 is enough to be able to add
```diff
diff --git a/core/unit_test/TestRangePolicyCTAD.cpp b/core/unit_test/TestRangePolicyCTAD.cpp
index d554c33bd..a35a3cc1a 100644
--- a/core/unit_test/TestRangePolicyCTAD.cpp
+++ b/core/unit_test/TestRangePolicyCTAD.cpp
@@ -69,7 +69,10 @@ struct TestRangePolicyCTAD {
 
   // RangePolicy(execution_space, index_type, index_type)
 
-  // none (ambiguous deduction for template arguments)
+  KOKKOS_TEST_RANGE_POLICY(Kokkos::RangePolicy<>, des, i64, i64);
+  KOKKOS_TEST_RANGE_POLICY(Kokkos::RangePolicy<>, des, i32, i32);
+  KOKKOS_TEST_RANGE_POLICY(Kokkos::RangePolicy<>, nes, i64, i64);
+  KOKKOS_TEST_RANGE_POLICY(Kokkos::RangePolicy<>, nes, i32, i32);
 
   // RangePolicy(execution_space, index_type, index_type, Args...)
```
with `clang++`.

**Review by crtrott — APPROVED** [review]

**Comment by dalg24** [comment]
Ignoring unrelated HIP and SYCL failures
