### ISSUE TITLE
Nightly build errors, host build with gcc/11.4 using nvcc_wrapper

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#8596]
**Describe the bug**

Nightly builds testing a Serial build of Kokkos with gcc/11.4.0 but using nvcc_wrapper began failing with error message:

```
23:38:35 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_nvccwrapper_nocuda_gcc1140/kokkos/core/src/Serial/Kokkos_Serial_Parallel_Range.hpp(52): error: function "Kokkos::Impl::ViewCopy<ViewTypeA, ViewTypeB, Layout, ExecSpace, 1, iType>::ViewCopy(const Kokkos::Impl::ViewCopy<Kokkos::View<int *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::AnonymousSpace::execution_space, Kokkos::AnonymousSpace::memory_space>, Kokkos::MemoryTraits<0U>>, Kokkos::View<const std::__detail::__platform_wait_t *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::AnonymousSpace::execution_space, Kokkos::AnonymousSpace::memory_space>, Kokkos::MemoryTraits<0U>>, Kokkos::LayoutRight, Kokkos::HostSpace::execution_space, 1, int64_t> &) [with ViewTypeA=Kokkos::View<int *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::AnonymousSpace::execution_space, Kokkos::AnonymousSpace::memory_space>, Kokkos::MemoryTraits<0U>>, ViewTypeB=Kokkos::View<const std::__detail::__platform_wait_t *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::AnonymousSpace::execution_space, Kokkos::AnonymousSpace::memory_space>, Kokkos::MemoryTraits<0U>>, Layout=Kokkos::LayoutRight, ExecSpace=Kokkos::HostSpace::execution_space, iType=int64_t]" (declared implicitly) cannot be referenced -- it is a deleted function
23:38:35         : m_functor(arg_functor), m_policy(arg_policy) {}
23:38:35                    ^
...
```

This began after merge of the following

**Changes**

    HIP: get multi processor count from the instance device prop ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkosdev2_nvccwrapper_nocuda_gcc1140/1156/changes#cfe76e58f093791bc8442d72682676e244c310e9) / [githubweb](https://github.com/kokkos/kokkos/commit/cfe76e58f093791bc8442d72682676e244c310e9))
    Revert "core: modernization of `partition_space` (#8556)" ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkosdev2_nvccwrapper_nocuda_gcc1140/1156/changes#6d34bb38bf84d85f02df395e4636420ae282f76b) / [githubweb](https://github.com/kokkos/kokkos/commit/6d34bb38bf84d85f02df395e4636420ae282f76b))
    Remove HPX from the GA continuous-integration-linux group ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkosdev2_nvccwrapper_nocuda_gcc1140/1156/changes#eef52bb85ddeb3c0e148e4ca1501b2bda580140d) / [githubweb](https://github.com/kokkos/kokkos/commit/eef52bb85ddeb3c0e148e4ca1501b2bda580140d))
    enable view hooks for new mdspan-based view implementation (#8459) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkosdev2_nvccwrapper_nocuda_gcc1140/1156/changes#f10ca8ecee098c5af2212cf6700f07604660f8d4) / [githubweb](https://github.com/kokkos/kokkos/commit/f10ca8ecee098c5af2212cf6700f07604660f8d4))
    BasicView: Suppress uninitialized warnings (#8038) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkosdev2_nvccwrapper_nocuda_gcc1140/1156/changes#69284efd5a64ad49bedc211d69d7baeac4a962ba) / [githubweb](https://github.com/kokkos/kokkos/commit/69284efd5a64ad49bedc211d69d7baeac4a962ba))
    Update development version to 5.0.99 (#8590) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkosdev2_nvccwrapper_nocuda_gcc1140/1156/changes#3c0e08ca2beed81e8d62e0924d2847a66e4f9621) / [githubweb](https://github.com/kokkos/kokkos/commit/3c0e08ca2beed81e8d62e0924d2847a66e4f9621))
    Fix README reference to C++17 and SNL copyright ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkosdev2_nvccwrapper_nocuda_gcc1140/1156/changes#a39ab53ea21a241e2a37dec203956ddde8ee9c19) / [githubweb](https://github.com/kokkos/kokkos/commit/a39ab53ea21a241e2a37dec203956ddde8ee9c19))
**Please include the following for a minimal reproducer**

**Reproducer notes**:
```bash
# Environment - kokkos-dev-2 specific
source /local-projects/spack/share/spack/setup-env.sh
module use /local-projects/spack-module-aliases/
module purge
module load cmake/3.31.8 gcc/11.5.0 cuda/12.2.2

# Configure
export KOKKOS_PATH=<path-to-src>

cmake -DCMAKE_CXX_COMPILER=$KOKKOS_PATH/bin/nvcc_wrapper -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF $KOKKOS_PATH

make -j16
```

Edit: updated modules

**Comment by dalg24** [comment]
Please try reverting the ViewHooks changes

**Comment by ndellingwood** [comment]
@dalg24 I reverted #8459 and compilation was successful

**Comment by ndellingwood** [comment]
This error did not reproduce with gcc/11.4.0+cuda/12.4.0
