### ISSUE TITLE
Jenkins errors in Kokkos_SharedAlloc.cpp with debug build

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1511]
@ibaned The following errors in `Kokkos_SharedAlloc.cpp` occurred with Melvin Jenkins job, possibly related to PR #1483?

Debug build with intel/16.0.1
SHA: 2ee639e10c702f91b6c0506518b08c16298f6f8d Merge pull request #1510 from ndellingwood/dualview-deprecated

```
11:10:18 /home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp(64): error: no instance of function template "Kokkos::atomic_exchange" matches the argument list
11:10:18             argument types are: (Kokkos::Impl::SharedAllocationRecord<void, void> **, std::nullptr_t)
11:10:18       while ( ( root_next = Kokkos::atomic_exchange( & root->m_next , nullptr ) ) == nullptr );
11:10:18                             ^
11:10:18 
11:10:18 /home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp(118): error: no instance of function template "Kokkos::atomic_exchange" matches the argument list
11:10:18             argument types are: (Kokkos::Impl::SharedAllocationRecord<void, void> **, std::nullptr_t)
11:10:18     while ( ( root_next = Kokkos::atomic_exchange( & arg_root->m_next , nullptr ) ) == nullptr );
11:10:18                           ^
11:10:18 
11:10:18 /home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp(173): error: no instance of function template "Kokkos::atomic_exchange" matches the argument list
11:10:18             argument types are: (Kokkos::Impl::SharedAllocationRecord<void, void> **, std::nullptr_t)
11:10:18       while ( ( m_next = Kokkos::atomic_exchange( & m_root->m_next , nullptr ) ) == nullptr );
11:10:18                          ^
11:10:18 
11:10:18 /home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp(234): error: no instance of function template "Kokkos::atomic_exchange" matches the argument list
11:10:18             argument types are: (Kokkos::Impl::SharedAllocationRecord<void, void> **, std::nullptr_t)
11:10:18       while ( ( root_next = Kokkos::atomic_exchange( & arg_record->m_root->m_next , nullptr ) ) == nullptr );
```

**Comment by ndellingwood** [comment]
PR #1512 issued by @swbova to address the issue.
