### ISSUE TITLE
HPX/1.3 backend compilation error

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#3463]
Following merge of #3206 the hpx backend has compilation errors with hpx/1.3 in nightly builds on apollo

Sample error message:
```bash
In file included from /home/ndellin/kokkos/core/src/Kokkos_View.hpp:56:0,
                 from /home/ndellin/kokkos/core/src/Kokkos_Parallel.hpp:53,
                 from /home/ndellin/kokkos/core/src/Kokkos_Serial.hpp:57,
                 from /home/ndellin/kokkos/core/src/decl/Kokkos_Declare_SERIAL.hpp:3,
                 from /home/ndellin/kokkos/testing/HPX/KokkosCore_Config_DeclareBackend.hpp:46,
                 from /home/ndellin/kokkos/core/src/Kokkos_Core.hpp:53,
                 from /home/ndellin/kokkos/core/unit_test/TestTeam.hpp:50,
                 from /home/ndellin/kokkos/core/unit_test/hpx/TestHPX_Team.cpp:46:
/home/ndellin/kokkos/core/src/Kokkos_ExecPolicy.hpp: In instantiation of ‘Kokkos::TeamPolicy<Properties>::TeamPolicy(int, const Kokkos::AUTO_t&, const Kokkos::AUTO_t&) [with Properties = {Kokkos::Experimental::HPX, Test::{anonymous}::TestTeamPolicy<Kokkos::Experimental::HPX, Kokkos::Schedule<Kokkos::Static> >::NoOpTag}]’:
/home/ndellin/kokkos/core/unit_test/TestTeam.hpp:126:54:   required from ‘static void Test::{anonymous}::TestTeamPolicy<ExecSpace, ScheduleType>::test_constructors() [with ExecSpace = Kokkos::Experimental::HPX; ScheduleType = Kokkos::Schedule<Kokkos::Static>]’
/home/ndellin/kokkos/core/unit_test/TestTeam.hpp:150:22:   required from ‘static void Test::{anonymous}::TestTeamPolicy<ExecSpace, ScheduleType>::test_for(size_t) [with ExecSpace = Kokkos::Experimental::HPX; ScheduleType = Kokkos::Schedule<Kokkos::Static>; size_t = long unsigned int]’
/home/ndellin/kokkos/core/unit_test/hpx/TestHPX_Team.cpp:51:70:   required from here

/home/ndellin/kokkos/core/src/Kokkos_ExecPolicy.hpp:592:76: error: no matching function for call to ‘Kokkos::Impl::TeamPolicyInternal<Kokkos::Experimental::HPX, Kokkos::Experimental::HPX, Test::{anonymous}::TestTeamPolicy<Kokkos::Experimental::HPX, Kokkos::Schedule<Kokkos::Static> >::NoOpTag>::TeamPolicyInternal(int&, const Kokkos::AUTO_t&, const Kokkos::AUTO_t&)’
       : internal_policy(league_size_request, Kokkos::AUTO(), Kokkos::AUTO()) {}
```

Reproducer instructions:
```bash
module load sems-env sems-cmake/3.12.2 compilers/hpx/1.3.0 sems-gcc/6.1.0 binutils

export KOKKOS_PATH=${HOME}/kokkos

$KOKKOS_PATH/generate_makefile.bash --with-devices=HPX --arch=SNB,Volta70 --compiler=g++ --cxxflags="-O3  " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --with-options=disable_deprecated_code --no-examples
```

I did a bisection on merge commits to confirm when compilation errors begen:
FAILING SHA 153d255355c1465f39b1c0bd72f282bad29d277c
PASSING SHA 6f3025d57f16780a59cd8b49bacb52937ceeaba8

**Comment by ndellingwood** [comment]
Compilation failure addressed by #3466, unit test failure addressed by #3470
