### ISSUE TITLE
Build errors following desul atomic inc/dec update - Cuda_OpenMP clang/7+cuda/9.2 build for Kepler

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4360]
New build errors began with following desul atomic inc/dec update in #4345 in a Cuda_OpenMP build with clang/7+cuda/9.2 for Kepler

```
/ascldap/users/ndellin/kokkos/core/unit_test/TestAtomicOperations.hpp:364:12: error: reference to __device__ function 'atomic_wrapping_fetch_inc' in __host__ __device__ function
    desul::atomic_wrapping_fetch_inc(&data(), (T)i1,
           ^
/ascldap/users/ndellin/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:86:7: note: in instantiation of member function 'TestAtomicOperations::WrappingIncFunctor<unsigned int, Kokkos::OpenMP>::operator()' requested here
      functor(iwork);
      ^
/ascldap/users/ndellin/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:114:7: note: in instantiation of function template specialization 'Kokkos::Impl::ParallelFor<TestAtomicOperations::WrappingIncFunctor<unsigned int, Kokkos::OpenMP>, Kokkos::RangePolicy<Kokkos::OpenMP>, Kokkos::OpenMP>::exec_range<void>' requested here
      exec_range<WorkTag>(m_functor, m_policy.begin(), m_policy.end());
      ^
/ascldap/users/ndellin/kokkos/core/src/Kokkos_Parallel.hpp:165:11: note: in instantiation of member function 'Kokkos::Impl::ParallelFor<TestAtomicOperations::WrappingIncFunctor<unsigned int, Kokkos::OpenMP>, Kokkos::RangePolicy<Kokkos::OpenMP>, Kokkos::OpenMP>::execute' requested here
  closure.execute();
          ^
/ascldap/users/ndellin/kokkos/core/unit_test/TestAtomicOperations.hpp:386:11: note: in instantiation of function template specialization 'Kokkos::parallel_for<TestAtomicOperations::WrappingIncFunctor<unsigned int, Kokkos::OpenMP> >' requested here
  Kokkos::parallel_for(1, f);
          ^
/ascldap/users/ndellin/kokkos/core/unit_test/TestAtomicOperations.hpp:411:17: note: in instantiation of function template specialization 'TestAtomicOperations::WrappingIncAtomic<unsigned int, Kokkos::OpenMP>' requested here
  T res       = WrappingIncAtomic<T, DeviceType>(i0, i1);
                ^
/ascldap/users/ndellin/kokkos/core/unit_test/TestAtomicOperations.hpp:1181:20: note: in instantiation of function template specialization 'TestAtomicOperations::WrappingIncAtomicTest<unsigned int, Kokkos::OpenMP>' requested here
    case 1: return WrappingIncAtomicTest<T, DeviceType>((T)i0, (T)i1);
                   ^
/ascldap/users/ndellin/kokkos/core/unit_test/TestAtomicOperations_unsignedint.hpp:78:32: note: in instantiation of function template specialization 'TestAtomicOperations::AtomicOperationsTestUnsignedIntegralType<unsigned int, Kokkos::OpenMP>' requested here
        (TestAtomicOperations::AtomicOperationsTestUnsignedIntegralType<
                               ^
/ascldap/users/ndellin/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:86:7: note: called by 'exec_range<void>'
      functor(iwork);
      ^
/ascldap/users/ndellin/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:114:7: note: called by 'execute'
      exec_range<WorkTag>(m_functor, m_policy.begin(), m_policy.end());
      ^
/ascldap/users/ndellin/kokkos/core/src/Kokkos_Parallel.hpp:165:11: note: called by 'parallel_for<TestAtomicOperations::WrappingIncFunctor<unsigned int, Kokkos::OpenMP> >'
  closure.execute();
          ^
/ascldap/users/ndellin/kokkos/core/unit_test/TestAtomicOperations.hpp:386:11: note: called by 'WrappingIncAtomic<unsigned int, Kokkos::OpenMP>'
  Kokkos::parallel_for(1, f);
          ^
/ascldap/users/ndellin/kokkos/core/unit_test/TestAtomicOperations.hpp:411:17: note: called by 'WrappingIncAtomicTest<unsigned int, Kokkos::OpenMP>'
  T res       = WrappingIncAtomic<T, DeviceType>(i0, i1);
                ^
/ascldap/users/ndellin/kokkos/core/unit_test/TestAtomicOperations.hpp:1181:20: note: called by 'AtomicOperationsTestUnsignedIntegralType<unsigned int, Kokkos::OpenMP>'
    case 1: return WrappingIncAtomicTest<T, DeviceType>((T)i0, (T)i1);
                   ^
/ascldap/users/ndellin/kokkos/core/unit_test/TestAtomicOperations_unsignedint.hpp:78:32: note: called by 'TestBody'
        (TestAtomicOperations::AtomicOperationsTestUnsignedIntegralType<
                               ^
/ascldap/users/ndellin/kokkos/core/src/desul/atomics/CUDA.hpp:104:32: note: 'atomic_wrapping_fetch_inc' declared here
__device__ inline unsigned int atomic_wrapping_fetch_inc(unsigned int* dest,
```

Reproducer info (kokkos-dev testbed):
```
module load sems-env sems-cmake/3.17.1 sems-clang/7.0.1 sems-cuda/9.2

cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized --gcc-toolchain=<path-to-gcc/base>" -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_KEPLER35=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_DEPRECATED_CODE=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF $KOKKOS_PATH
```

Edit: updated reproducer to list modules loaded and machine tested

**Comment by dalg24** [comment]
Can you try to move `DESUL_IMPL_CUDA_HOST_ATOMIC_WRAPPING_FETCH_{INC,DEC}` out of the `ifdef DESUL_HAVE_CUDA_ATOMICS_ASM` in the `CUDA.hpp` header?

**Comment by ajpowelsnl** [comment]
@dalg24 -- use clang and arch pascale or kepler, i.e. , something pre- Volta

**Comment by ajpowelsnl** [comment]
Morning @ndellingwood -- Would you please look into this issue?  Damien and Christian recommended that you use a clang compiler , and an architecture setting of Pascale or Kepler, which is to say something pre - Volta.  Please let me know if you have any questions!

**Comment by ndellingwood** [comment]
@ndellingwood this error occurred in nightly build with clang/7 and Kepler arch, listed in the reproducer line https://github.com/kokkos/kokkos/issues/4360#issue-1006770498

**Comment by ndellingwood** [comment]
@ajpowelsnl this error occurred in nightly build with clang/7 and Kepler arch, listed in the reproducer line #4360 (comment)

**Comment by ndellingwood** [comment]
@ajpowelsnl I updated the #4367 PR, apologies for delayed response

**Comment by ajpowelsnl** [comment]
> @ajpowelsnl I updated the #4367 PR, apologies for delayed response

Thanks for the help, @ndellingwood , and I didn't notice a delay -- you're on it!

**Comment by ndellingwood** [comment]
Hi @ajpowelsnl , Damien ended up putting in PR #4367 with a different solution to the issue. The failing clang/7+cuda/9.2 nightly test on Kepler is now passing again, so this issue can be closed and timeframe changed to release 3.5. I don't want to disrupt the project space and issue tracking, can you relabel this for 3.5? Thanks

**Comment by ajpowelsnl** [comment]
@ndellingwood -- Many thanks for the heads up!  I'll close the issue, and put it in 3.5.
