### PR TITLE
 Fix KOKKOS_VERSION_* macros

### PR DESCRIPTION
**Pull request by masterleinad**
The current syntax undefines `KOKKOS_VERSION_PATCH` if its value is 0.

### CODE REVIEW

**Review by nmm0 — APPROVED** [review]
Woops!

**Review by ldh4 — APPROVED** [review]

**Review by dalg24 — COMMENTED** [review]
Please confirm that the tests we have in place caught that

**Comment by dalg24** [comment]
Looks like it
```
/Users/qdi/CLionProjects/kokkos/core/unit_test/TestVersionMacros.cpp:32:15: error: static assertion failed: KOKKOS_VERSION_PATCH macro is not defined! [clang-diagnostic-error]
   32 | static_assert(false, "KOKKOS_VERSION_PATCH macro is not defined!");
      |               ^~~~~
```
Good

**Comment by dalg24** [comment]
BTW did you notice because you built locally or was it some automated testing on the new rc branch?

File: cmake/KokkosCore_config.h.in [hunk 1]
```diff
@@ -9,10 +9,10 @@
...
 // KOKKOS_VERSION / 100 % 100 is the minor version
 // KOKKOS_VERSION / 10000 is the major version
-#cmakedefine KOKKOS_VERSION @KOKKOS_VERSION@
-#cmakedefine KOKKOS_VERSION_MAJOR @KOKKOS_VERSION_MAJOR@
-#cmakedefine KOKKOS_VERSION_MINOR @KOKKOS_VERSION_MINOR@
-#cmakedefine KOKKOS_VERSION_PATCH @KOKKOS_VERSION_PATCH@
+#define KOKKOS_VERSION @KOKKOS_VERSION@
+#define KOKKOS_VERSION_MAJOR @KOKKOS_VERSION_MAJOR@
+#define KOKKOS_VERSION_MINOR @KOKKOS_VERSION_MINOR@
+#define KOKKOS_VERSION_PATCH @KOKKOS_VERSION_PATCH@
```
[the remark this answers is not in the document]
Comment (crtrott) [reply cmake/KokkosCore_config.h.in:15]: Yeah agreed.

**Comment by ndellingwood** [comment]
This should get a changelog entry for 4.6, or was the issue introduced this release cycle?

**Comment by dalg24** [comment]
No.  It was introduced in #7665, which is not included in previous releases.

**Comment by masterleinad** [comment]
> BTW did you notice because you built locally or was it some automated testing on the new rc branch?

I got notifications from the GitLab CI that all builds failed.
