### PR TITLE
Kokkos_Cuda.hpp: Fix shadow warning with cuda/11.0

### PR DESCRIPTION
**Pull request by ndellingwood**
The shadow warning triggered -Werror compilation errors in cuda/11.0 nightly builds for example with configuration:
```
$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=SNB,Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --with-cuda-options=enable_lambda  --no-examples
```

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Comment by ndellingwood** [comment]
Hip-ROCm-4.2-C++17 build error seems to be CI glitch:
```
ERROR: The container started but didn't run the expected command. Please double check your ENTRYPOINT does execute the command passed as docker run argument, as required by official docker images (see https://github.com/docker-library/official-images#consistency for entrypoint consistency requirements).
Alternatively you can force image entrypoint to be disabled by adding option `--entrypoint=''`.
```

**Comment by ndellingwood** [comment]
retest this please

**Review by masterleinad — APPROVED** [review]

**Comment by dalg24** [comment]
I fail to see what would be shadowed by this parameter name.  Would you post the warning that was emitted?

**Comment by ndellingwood** [comment]
> I fail to see what would be shadowed by this parameter name. Would you post the warning that was emitted?

@dalg24 sure, I should've done so with the PR. The warning was strange to me, occurs with cuda/11.0+gcc/9.3.0, does not happen in other builds with older cuda versions or cuda/11.1+gcc/8.3.0

```
21:24:42 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda110_gcc920_cpp17/kokkos/core/src/Kokkos_Cuda.hpp:288:1: error: declaration of ‘exec_space’ shadows a global declaration [-Werror=shadow]
21:24:42   288 |   }
21:24:42       | ^
21:24:42 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda110_gcc920_cpp17/kokkos/core/perf_test/test_atomic_minmax_simple.cpp:17:7: note: shadowed declaration is here
21:24:42    17 | using exec_space = Kokkos::DefaultExecutionSpace;
21:24:42       |       ^~~~~~~~~~
```

**Comment by dalg24** [comment]
Thank you
