### PR TITLE
Fixup use provided execution space when copying host inaccessible reduction result

### PR DESCRIPTION
**Pull request by dalg24**
Spotted when auditing use of 2-arguments `Impl::DeepCopy` throughout the codebase.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Comment by dalg24** [comment]
The current version is incorrect
```
/var/jenkins/workspace/Kokkos_PR-6777/core/src/HIP/Kokkos_HIP_ParallelReduce_Team.hpp:274:11: error: no matching constructor for initialization of 'DeepCopy<Kokkos::HostSpace, Kokkos::HIPSpace>'
          DeepCopy<HostSpace, HIPSpace>(m_policy.space(), m_result_ptr,
          ^                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/jenkins/workspace/Kokkos_PR-6777/core/src/Kokkos_Parallel_Reduce.hpp:1517:13: note: in instantiation of member function 'Kokkos::Impl::ParallelReduce<Kokkos::Impl::CombinedFunctorReducer<(lambda at /var/jenkins/workspace/Kokkos_PR-6777/core/perf_test/PerfTest_CustomReduction.cpp:40:7), Kokkos::Impl::FunctorAnalysis<Kokkos::Impl::FunctorPatternInterface::REDUCE, Kokkos::TeamPolicy<>, Kokkos::Max<double>, double>::Reducer>, Kokkos::TeamPolicy<>, Kokkos::HIP>::execute' requested here
    closure.execute();
            ^
/var/jenkins/workspace/Kokkos_PR-6777/core/src/Kokkos_Parallel_Reduce.hpp:1533:5: note: in instantiation of member function 'Kokkos::Impl::ParallelReduceAdaptor<Kokkos::TeamPolicy<>, (lambda at /var/jenkins/workspace/Kokkos_PR-6777/core/perf_test/PerfTest_CustomReduction.cpp:40:7), Kokkos::Max<double>>::execute_impl' requested here
    execute_impl(label, policy, functor, return_value);
    ^
/var/jenkins/workspace/Kokkos_PR-6777/core/src/Kokkos_Parallel_Reduce.hpp:1769:69: note: in instantiation of function template specialization 'Kokkos::Impl::ParallelReduceAdaptor<Kokkos::TeamPolicy<>, (lambda at /var/jenkins/workspace/Kokkos_PR-6777/core/perf_test/PerfTest_CustomReduction.cpp:40:7), Kokkos::Max<double>>::execute<Kokkos::Max<double>>' requested here
  Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::execute(
                                                                    ^
/var/jenkins/workspace/Kokkos_PR-6777/core/perf_test/PerfTest_CustomReduction.cpp:38:11: note: in instantiation of function template specialization 'Kokkos::parallel_reduce<Kokkos::TeamPolicy<>, (lambda at /var/jenkins/workspace/Kokkos_PR-6777/core/perf_test/PerfTest_CustomReduction.cpp:40:7), Kokkos::Max<double>>' requested here
  Kokkos::parallel_reduce(

**Comment by dalg24** [comment]
Fixed.  Had forgotten to had the trailing execution space parameter in `DeepCoy<DstMemSpace, SrcMemSpace[, ExecSpace]>`

**Comment by dalg24** [comment]
The HIP failure is unrelated and was fixed in #6778
Everything else passed
```
In file included from /var/jenkins/workspace/Kokkos_PR-6777/build/core/unit_test/generated/Test01_execspace_HIP.cpp:27:
/var/jenkins/workspace/Kokkos_PR-6777/core/unit_test/incremental/Test01_execspace.hpp:66:34: error: no member named 'in_parallel' in 'Kokkos::HIP'
    int in_parallel = ExecSpace::in_parallel();
                                 ^
/var/jenkins/workspace/Kokkos_PR-6777/core/unit_test/incremental/Test01_execspace.hpp:85:8: note: in instantiation of member function 'Test::TestIncrExecSpace<Kokkos::HIP>::testit' requested here
  test.testit();
       ^
1 error generated when compiling for gfx908.
[ 12%] Building CXX object core/unit_test/CMakeFiles/Kokkos_IncrementalTest_SERIAL.dir/generated/Test02_atomic_host_SERIAL.cpp.o
make[2]: *** [core/unit_test/CMakeFiles/Kokkos_IncrementalTest_HIP.dir/build.make:79: core/unit_test/CMakeFiles/Kokkos_IncrementalTest_HIP.dir/generated/Test01_execspace_HIP.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1934: core/unit_test/CMakeFiles/Kokkos_IncrementalTest_HIP.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Review by Rombur — APPROVED** [review]
