### ISSUE TITLE
Nightly build failures, intel/19.0.5 icpc, Kokkos_BasicView.hpp(43): error #854...

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7404]
**Describe the bug**

Nightly builds with intel/19.0.5 fail to compile with the following type of error:
```
11:45:16 In file included from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Kokkos_View.hpp(26),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Kokkos_Parallel.hpp(31),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Kokkos_MemoryPool.hpp(26),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Kokkos_TaskScheduler.hpp(34),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Serial/Kokkos_Serial.hpp(37),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/decl/Kokkos_Declare_SERIAL.hpp(21),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/TestAll_2024-10-04_11.44.36/intel/19.0.5/Serial-debug/KokkosCore_Config_DeclareBackend.hpp(22),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Kokkos_Core.hpp(45),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/impl/Kokkos_Core.cpp(21):
11:45:16 /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/View/Kokkos_BasicView.hpp(43): error #854: const variable "Kokkos::Impl::subview_ctor_tag" requires an initializer -- class "Kokkos::Impl::SubViewCtorTag" has no user-provided default constructor
11:45:16   } subview_ctor_tag;
11:45:16     ^
```

This follows merge of #7385 , @crtrott 

**Please include the following for a minimal reproducer**

**Reproducer**:
```bash
module load sems-cmake sems-intel/19.0.5

cmake -DCMAKE_CXX_COMPILER=icpc -DCMAKE_CXX_FLAGS="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -diag-disable=1011 -diag-disable=869" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=DEBUG -DKokkos_ENABLE_DEBUG=ON -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF $KOKKOS_PATH
```

**Comment by ndellingwood** [comment]
With the -Werror resolved by #7419, I did additional testing with intel icpc (2021.10) and encountered ICE in several unit tests with the Serial backend that seem triggered when configuring with a specific arch (I tested with SKX).
Neither adding the `-no-ip` flag (which has helped with similar issues in the past, for example with Trilinos) nor disabling MDSPAN (`-DKokkos_ENABLE_IMPL_MDSPAN=OFF`) circumvented the issues. When an arch is not specified, the ICE is not present.

I manually disabled the tests with the changes below, @dalg24 should I consider putting in a PR for discussion?
```diff
diff --git a/containers/unit_tests/CMakeLists.txt b/containers/unit_tests/CMakeLists.txt
index cf1cf2b85..8e97039b9 100644
--- a/containers/unit_tests/CMakeLists.txt
+++ b/containers/unit_tests/CMakeLists.txt
@@ -42,6 +42,10 @@ foreach(Tag Threads;Serial;OpenMP;HPX;Cuda;HIP;SYCL)
     if(KOKKOS_ENABLE_CUDA AND WIN32)
       list(REMOVE_ITEM UnitTestSources ${dir}/TestCuda_DynViewAPI_generic.cpp)
     endif()
+    # internal error: 101003_1112
+    if(KOKKOS_ENABLE_SERIAL AND KOKKOS_CXX_COMPILER_ID STREQUAL Intel)
+      list(REMOVE_ITEM UnitTestSources ${dir}/TestSerial_DynViewAPI_generic.cpp)
+    endif()
 
     # FIXME_NVHPC: NVC++-S-0000-Internal compiler error. extractor: bad opc       0
     if(KOKKOS_ENABLE_CUDA AND KOKKOS_CXX_COMPILER_ID STREQUAL NVHPC)
diff --git a/core/src/View/Kokkos_BasicView.hpp b/core/src/View/Kokkos_BasicView.hpp
index e1350afc2..39080bfd6 100644
--- a/core/src/View/Kokkos_BasicView.hpp
+++ b/core/src/View/Kokkos_BasicView.hpp
@@ -40,7 +40,7 @@ namespace Kokkos {
 namespace Impl {
 constexpr inline struct SubViewCtorTag {
   explicit SubViewCtorTag() = default;
-} subview_ctor_tag;
+} subview_ctor_tag{};
 
 template <class T>
 struct KokkosSliceToMDSpanSliceImpl {
diff --git a/core/unit_test/CMakeLists.txt b/core/unit_test/CMakeLists.txt
index f4386891c..59adca5b0 100644
--- a/core/unit_test/CMakeLists.txt
+++ b/core/unit_test/CMakeLists.txt
@@ -137,8 +137,7 @@ foreach(Tag Threads;Serial;OpenMP;Cuda;HPX;OpenMPTarget;OpenACC;HIP;SYCL)
     # command line in an intermediate compilation step even if CMake generated a response
     # file. That then exceeded the shell command line max length.
     set(${Tag}_SOURCES1A)
-    foreach(
-      Name
+    set(${Tag}_TESTNAMES1A
       Abort
       ArrayOps
       AtomicOperations_complexdouble
@@ -178,6 +177,10 @@ foreach(Tag Threads;Serial;OpenMP;Cuda;HPX;OpenMPTarget;OpenACC;HIP;SYCL)
       MathematicalFunctions3
       MathematicalSpecialFunctions
     )
+    if(KOKKOS_CXX_COMPILER_ID STREQUAL Intel)
+      list(REMOVE_ITEM ${Tag}_TESTNAMES1A LocalDeepCopy)
+    endif()
+    foreach(Name IN LISTS ${Tag}_TESTNAMES1A)
       set(file ${dir}/Test${Tag}_${Name}.cpp)
       # Write to a temporary intermediate file and call configure_file to avoid
       # updating timestamps triggering unnecessary rebuilds on subsequent cmake runs.
@@ -284,6 +287,9 @@ foreach(Tag Threads;Serial;OpenMP;Cuda;HPX;OpenMPTarget;OpenACC;HIP;SYCL)
     # See issue: https://github.com/kokkos/kokkos/issues/7084
     if(KOKKOS_CXX_COMPILER_ID STREQUAL Intel)
       list(REMOVE_ITEM ${Tag}_TESTNAMES2A ViewCopy_c)
+      list(REMOVE_ITEM ${Tag}_TESTNAMES2A ViewAPI_e)
+      list(REMOVE_ITEM ${Tag}_TESTNAMES2A TeamMDRange)
+#      list(REMOVE_ITEM ${Tag}_TESTNAMES2A ViewHooks)
     endif()
     foreach(Name IN LISTS ${Tag}_TESTNAMES2A)
       set(file ${dir}/Test${Tag}_${Name}.cpp)
@@ -304,8 +310,7 @@ foreach(Tag Threads;Serial;OpenMP;Cuda;HPX;OpenMPTarget;OpenACC;HIP;SYCL)
     endif()
 
     set(${Tag}_SOURCES2B)
-    foreach(
-      Name
+    set(${Tag}_TESTNAMES2B
       SubView_a
       SubView_b
       SubView_c01
@@ -314,6 +319,10 @@ foreach(Tag Threads;Serial;OpenMP;Cuda;HPX;OpenMPTarget;OpenACC;HIP;SYCL)
       SubView_c04
       SubView_c05
     )
+    if(KOKKOS_CXX_COMPILER_ID STREQUAL Intel)
+      list(REMOVE_ITEM ${Tag}_TESTNAMES2B SubView_b)
+    endif()
+    foreach(Name IN LISTS ${Tag}_TESTNAMES2B)
       set(file ${dir}/Test${Tag}_${Name}.cpp)
       # Write to a temporary intermediate file and call configure_file to avoid
       # updating timestamps triggering unnecessary rebuilds on subsequent cmake runs.
@@ -1055,6 +1064,9 @@ function(KOKKOS_ADD_INCREMENTAL_TEST DEVICE)
   # Iterate over incremental tests in directory
 
   append_glob(INCREMENTAL_FILE_LIST ${CMAKE_CURRENT_SOURCE_DIR}/incremental/*.hpp)
+  if(KOKKOS_CXX_COMPILER_ID STREQUAL Intel)
+    list(REMOVE_ITEM INCREMENTAL_FILE_LIST "${CMAKE_CURRENT_SOURCE_DIR}/incremental/Test06_ParallelFor_MDRangePolicy.hpp")
+  endif()
 
   set(DEVICE_NAME ${KOKKOS_${DEVICE}_NAME})
   foreach(CURRENT_FILE_PATH ${INCREMENTAL_FILE_LIST})
```

**Comment by dalg24** [comment]
> Should I consider putting in a PR for discussion?

I would say open a new issue about the ICE with Intel C++ compiler classic and post the diff there.
That will avoid unnecessarily burdening the CI.
