### ISSUE TITLE
Cuda rdc broken by PR #1799

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1802]
PR #1799 with fixes for mask warnings (reported #1796) broke some cuda < 9.0 builds

sample output:

`home/jenkins/slave/workspace/Kokkos_develop_kokkos-dev_cuda_75/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(2044): error`

**Comment by ndellingwood** [comment]
I missed guards for `KOKKOS_IMPL_CUDA_SYNCWARP_MASK` changes in a couple files, should have PR with fixes in shortly.

**Comment by ndellingwood** [comment]
PR #1803 issued with fix.
