### PR TITLE
SYCL: Don't define FALLBACK_ASSERT

### PR DESCRIPTION
**Pull request by masterleinad**
All Intel, Nvidia, and AMD devices we care about, should support device asserts without expliciting requesting to have a fallback in place. Removing the macros fixes lauch issues on AMD GPUs.

### CODE REVIEW

**Comment by masterleinad** [comment]
I verified that `Kokkos::abort` still tests OK on `Intel GPUs` with these changes when compiling in `Debug` mode.

File: .github/workflows/snl-ci.yml [hunk 1]
```diff
@@ -212,7 +212,7 @@ jobs:
             -DCMAKE_CXX_COMPILER=icpx \
             -DCMAKE_CXX_STANDARD=20 \
             -DCMAKE_BUILD_TYPE=Release \
-            -DCMAKE_CXX_FLAGS='-Werror -fp-model=precise -fsycl-device-code-split=per_kernel' \
+            -DCMAKE_CXX_FLAGS='-Werror -fp-model=precise -fsycl-device-code-split=per_kernel -Wno-zero-length-array' \
```
Comment (dalg24) [inline .github/workflows/snl-ci.yml:215]: Where are these zero-length array warnings coming from?
Why does it belong to this PR?

Comment (masterleinad) [reply .github/workflows/snl-ci.yml:215]: The first commit failed with warnings like
```
In file included from <built-in>:1:
/tmp/icpx-3bd1fefb13/Kokkos_HostBarrier-header-dd791a.h:25:36: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
   25 | const char* const kernel_names[] = {
      |                                    ^
``` 
for a couple files, see https://gitlab.spack.io/kokkos/kokkos/-/jobs/17049669. I didn't see this warning on Aurora, though.

Comment (dalg24) [reply .github/workflows/snl-ci.yml:215]: And this only manifest with the PR with our not defining `SYCL_FALLBACK_ASSERT`?!

Comment (masterleinad) [reply .github/workflows/snl-ci.yml:215]: Yes, apparently. We don't see the error/warning in any pull request AFAICT.

Comment (dalg24) [reply .github/workflows/snl-ci.yml:215]: Did you report it?

Comment (masterleinad) [reply .github/workflows/snl-ci.yml:215]: I can't reproduce on Aurora with a newer compiler version.

Comment (dalg24) [reply .github/workflows/snl-ci.yml:215]: Do you see it on older versions of the toolchain on that system (Aurora)

Comment (masterleinad) [reply .github/workflows/snl-ci.yml:215]: I can observe with the oldest functional compiler on Aurora
```
FAILED: core/src/CMakeFiles/kokkoscore.dir/__/__/tpls/desul/src/Lock_Array_SYCL.cpp.o 
/opt/aurora/24.180.3/updates/oneapi/compiler/eng-20240629/bin/icpx -DKOKKOS_DEPENDENCE -DONEDPL_USE_OPENMP_BACKEND=0 -DONEDPL_USE_TBB_BACKEND=1 -I/home/darndt/kokkos/build/core/src -I/home/darndt/kokkos/core/src -I/home/darndt/kokkos/build -I/home/darndt/kokkos/tpls/desul/include -I/home/darndt/kokkos/tpls/mdspan/include -isystem /opt/aurora/24.180.3/oneapi/dpl/2022.6/include -isystem /opt/aurora/24.180.3/oneapi/tbb/2021.13/include -Werror -Wno-pass-failed -Wall -Wextra -Wunused-parameter -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized -Wsuggest-override -O2 -g -DNDEBUG -std=gnu++17 -fsycl -fno-sycl-id-queries-fit-in-int -fsycl-dead-args-optimization -fsycl-unnamed-lambda -fno-sycl-rdc -DDESUL_SYCL_DEVICE_GLOBAL_SUPPORTED -fsycl-targets=spir64_gen -Xsycl-target-backend "-device 12.60.7" -MD -MT core/src/CMakeFiles/kokkoscore.dir/__/__/tpls/desul/src/Lock_Array_SYCL.cpp.o -MF core/src/CMakeFiles/kokkoscore.dir/__/__/tpls/desul/src/Lock_Array_SYCL.cpp.o.d -o core/src/CMakeFiles/kokkoscore.dir/__/__/tpls/desul/src/Lock_Array_SYCL.cpp.o -c /home/darndt/kokkos/tpls/desul/src/Lock_Array_SYCL.cpp
Compilation from IR - skipping loading of FCL
Build succeeded.
In file included from <built-in>:1:
/tmp/icpx-87eee13efa/Lock_Array_SYCL-header-acb483.h:25:36: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
   25 | const char* const kernel_names[] = {
      |                                    ^
1 error generated.
ninja: build stopped: cannot make progress due to previous errors.
```
That is after removing https://github.com/kokkos/kokkos/blob/f382e5f962af260dedb1a4bf09497db85fb51326/core/src/CMakeLists.txt#L114-L117. I don't see warnings for the changes here with that compiler.

The oneAPI 2024.2.1 module doesn't work there due to GLIBCXX incompatibilities.

**Review by dalg24 — COMMENTED** [review]
Do we want to recommend the user ignore the warning/set suppression flags on their own, or should we set a compile flag property for older toolchains?

**Comment by masterleinad** [comment]
> Do we want to recommend the user ignore the warning/set suppression flags on their own, or should we set a compile flag property for older toolchains?

https://gitlab.spack.io/masterleinad/kokkos/-/jobs/17070464/raw shows a build with oneAPI 2024.2.1 and without `-Werror`. There are a total of 19 warnings with
```
warning: zero size arrays are an extension [-Wzero-length-array]
```
Most of them for `Kokkos` source files but also repeatedly for `/tmp/icpx-717ac0acbe/tstHeader-header-35d325.h` and similar. All these files are compiler-generated. Since this is not `Kokkos`' fault and it's not an excessive amount, I think it's fine for to just suppress the warnings in the CI.

**Review by dalg24 — APPROVED** [review]

**Review by JBludau — APPROVED** [review]
looks good to me
