### ISSUE TITLE
Kokkos updates breaking nightly gcc/8.3.0, gcc/9, gcc/10 builds: Kokkos_HostSpace.hpp:312:12: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4238]
Kokkos nightly builds with gcc/8.3.0 and cuda/11.1+gcc/8.3.0 failed with error message

```
18:19:45 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda111_gcc830/kokkos/core/src/Kokkos_HostSpace.hpp:312:12: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘using value_type = using value_type = using value_type = using value_type = class Kokkos::complex<double>’ {aka ‘class Kokkos::complex<double>’}; use assignment or value-initialization instead [-Werror=class-memaccess]
18:19:45      std::memset(dst.data(), 0, sizeof(ValueType) * dst.size());
18:19:45      ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:19:45 /data/jenkins-new/workspace/kokkos_semsrhel7gpu01_cuda111_gcc830/kokkos/core/src/Kokkos_Complex.hpp:67:34: note: ‘using value_type = using value_type = using value_type = using value_type = class Kokkos::complex<double>’ {aka ‘class Kokkos::complex<double>’} declared here
18:19:45      alignas(2 * sizeof(RealType))
```

Likely following from merge of PR #4226 , @masterleinad are you able to take a look?
Issue #4237 may be related.

Reproducer instructions (cuda build):
```
module load sems-env sems-cmake/3.17.1 sems-cuda/11.1 sems-gcc/8.3.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --with-cuda-options=enable_lambda  --no-examples --with-options=enable_large_mem_tests
```

**Comment by ndellingwood** [comment]
#4240 resolved nightly build errors using gcc >= version 8, thanks @masterleinad
