### ISSUE TITLE
Internal copy of desul atomics fails to build with hipcc 5.4

### ISSUE THREAD

**Issue by simon-schlepphorst** [kokkos/kokkos#6306]
Using todays develop branch (as well as release 4.0.01) and hipcc 5.4.22801, I get the following compiler error:

```
Building CXX object kokkos/core/src/CMakeFiles/kokkoscore.dir/__/__/tpls/desul/src/Lock_Array_HIP.cpp.o
In file included from kokkos/kokkos/tpls/desul/src/Lock_Array_HIP.cpp:10:
In file included from kokkos/kokkos/core/src/../../tpls/desul/include/desul/atomics/Lock_Array.hpp:12:
In file included from kokkos/kokkos/core/src/../../tpls/desul/include/desul/atomics/Compare_Exchange.hpp:15:
In file included from kokkos/kokkos/core/src/../../tpls/desul/include/desul/atomics/Compare_Exchange_GCC.hpp:12:
kokkos/kokkos/core/src/../../tpls/desul/include/desul/atomics/Common.hpp:102:1: error: unknown type name '__host__'
DESUL_INLINE_FUNCTION bool atomic_is_lock_free() noexcept {
^
kokkos/kokkos/core/src/../../tpls/desul/include/desul/atomics/Macros.hpp:72:38: note: expanded from macro 'DESUL_INLINE_FUNCTION'
#define DESUL_INLINE_FUNCTION inline __host__ __device__
                                     ^
```

According to issue #3391 the keyword `__host__` is defined in `hip/hip_runtime.h`.

The issue is solved by placing `#include <desul/atomics/Compare_Exchange.hpp>` after `#include <desul/atomics/Lock_Array_HIP.hpp>`:
https://github.com/kokkos/kokkos/blob/4d1c6c351490cc8660e2392ead9fce1af7e379f5/tpls/desul/include/desul/atomics/Lock_Array.hpp#L12-L22

**Comment by Rombur** [comment]
How did you configure Kokkos? Which compiler are you using?

**Comment by simon-schlepphorst** [comment]
```
export CXX="hipcc"

cmake \
     -DKokkos_ARCH_ZEN3=ON \
     -DKokkos_ARCH_VEGA90A=ON \
     -DKokkos_ENABLE_OPENMP=ON \
     -DKokkos_ENABLE_HIP=ON \
     -DKokkos_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS=ON \
     -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
     -B build
 ```
 
 ```
 $ hipcc --version
HIP version: 5.4.22801-
clang version 15.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by Rombur** [comment]
I just tried `develop` with the same configuration as you and it works. Are you configuring Kokkos in a clean directory?

**Comment by simon-schlepphorst** [comment]
Yes, freshly cloned repository and empty `build` directory.

I suppose the installation of the compiler on the machine I have access to behaves differently.

Either I have to reorder the includes in `Lock_Array.hpp` or include `hip_runtime.h` via command line switch for all files.
```
export CXXFLAGS="-include <FULL_PATH_TO>/hip/hip_runtime.h"
```
Otherwise compilation fails with the error from above.

**Comment by Rombur** [comment]
Can you do `make VERBOSE=1` and show exactly the compile line when the error appears.

**Comment by simon-schlepphorst** [comment]
Sure.
I've just abbreviated absolute paths with `$HOME` and `$HIP_PATH` variables afterwards.

```
cd $HOME/kokkos/build/core/src && $HIP_PATH/bin/hipcc -DKOKKOS_DEPENDENCE -I$HOME/kokkos/build/core/src -I$HOME/kokkos/core/src -I$HOME/kokkos/build -I$HOME/kokkos/core/src/../../tpls/desul/include -O2 -g -DNDEBUG -march=znver3 -mtune=znver3 -fno-gpu-rdc --offload-arch=gfx90a -fopenmp=libomp -std=gnu++17 -MD -MT core/src/CMakeFiles/kokkoscore.dir/__/__/tpls/desul/src/Lock_Array_HIP.cpp.o -MF CMakeFiles/kokkoscore.dir/__/__/tpls/desul/src/Lock_Array_HIP.cpp.o.d -o CMakeFiles/kokkoscore.dir/__/__/tpls/desul/src/Lock_Array_HIP.cpp.o -c $HOME/kokkos/tpls/desul/src/Lock_Array_HIP.cpp
```
