### PR TITLE
Workaround problem with LDBL_EPSILON problem with XL

### LINKED ISSUE #3934: cuda+xl compilation error in numeric traits
cuda/10.1 builds on Power with xl/16.1.1 as host compiler fail to compile on develop and release-candidate-3.4.0 (SHA d3a6b0a959512e6fe6d6bb062b585bf005441c6b) branches with errors of the form:

```
/ascldap/users/ndellin/kokkos/core/src/Kokkos_NumericTraits.hpp(98): error: a constexpr static data member declaration requires an in-class initializer

/ascldap/users/ndellin/kokkos/core/src/Kokkos_NumericTraits.hpp(98): error: data member initializer is not allowed
```

The error message doesn't really make sense (there is an in-class initializer), seems a compiler hiccup.
Extra note, replacing `LDBL_EPSILON` with `DBL_EPSILON`, though incorrect value for the `long double` type, allows compilation to complete.

Sample reproducer instructions for white testbed (this is using the launch compiler, and not nvcc_wrapper):
```
module load git cmake/3.19.3 cuda/10.1.105 gcc/7.2.0 ibm/xl/16.1.1

export XLC_USR_CONFIG=/opt/ibm/xlC/16.1.1/etc/xlc.cfg.rhel.7.6.gcc.7.2.0.cuda.10.1

cmake -DCMAKE_CXX_COMPILER=xlc++ -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -qxflag=disable__cplusplusOverride" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_PASCAL60=ON -DKokkos_ARCH_POWER8=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RELEASE" $KOKKOS_PATH
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #3934. XL seems to have a problem with using LDBL_EPSILON. Work around that issue by computing the machine epsilon for `long double` ourselves.

@ndellingwood Can you please check that this works for you?

### CODE REVIEW

**Comment by ndellingwood** [comment]
@masterleinad I ran into compilation errors with a Cuda_Serial build, beginning with this one

```
/ascldap/users/ndellin/kokkos-bk/core/src/impl/Kokkos_AnalyzePolicy.hpp:80:72: error: template argument for template template parameter must be a class template or type alias template
template< class ...Ts> using apply = typename T::template base_traits< msvc_workaround_get_next_base_traits, Ts...> ;
                                                                       ^
/ascldap/users/ndellin/kokkos-bk/core/src/impl/Kokkos_Utilities.hpp:235:54: note: in instantiation of template class 'Kokkos::Impl::msvc_workaround_get_next_base_traits<Kokkos::Impl::ExecutionSpaceTrait>' requested here
struct linearize_bases< GetBase, T, Ts...>  : public GetBase< T> ::template apply< Ts...>  {
                                                     ^
/ascldap/users/ndellin/kokkos-bk/core/src/impl/Kokkos_AnalyzePolicy.hpp:92:84: note: in instantiation of template class 'Kokkos::Impl::linearize_bases<msvc_workaround_get_next_base_traits, Kokkos::Impl::ExecutionSpaceTrait, Kokkos::Impl::IndexTypeTrait, Kokkos::Impl::ScheduleTrait, Kokkos::Impl::IterationPatternTrait, Kokkos::Impl::WorkItemPropertyTrait, Kokkos::Impl::LaunchBoundsTrait, Kokkos::Impl::OccupancyControlTrait, Kokkos::Impl::GraphKernelTrait, Kokkos::Impl::WorkTagTrait>' requested here
struct AnalyzeExecPolicyBaseTraits< type_list< TraitSpecifications...> >  : public linearize_bases< msvc_workaround_get_next_base_traits, TraitSpecifications...>  {
                                                                                   ^
/ascldap/users/ndellin/kokkos-bk/core/src/impl/Kokkos_AnalyzePolicy.hpp:127:54: note: in instantiation of template class 'Kokkos::Impl::AnalyzeExecPolicyBaseTraits<Kokkos::Impl::type_list<Kokkos::Impl::ExecutionSpaceTrait, Kokkos::Impl::IndexTypeTrait, Kokkos::Impl::ScheduleTrait, Kokkos::Impl::IterationPatternTrait, Kokkos::Impl::WorkItemPropertyTrait, Kokkos::Impl::LaunchBoundsTrait, Kokkos::Impl::OccupancyControlTrait, Kokkos::Impl::GraphKernelTrait, Kokkos::Impl::WorkTagTrait> >' requested here
template<> struct AnalyzeExecPolicy< void>  : public AnalyzeExecPolicyBaseTraits< type_list< ExecutionSpaceTrait, IndexTypeTrait, ScheduleTrait, IterationPatternTrait, WorkItemPropertyTrait, LaunchBoundsTrait, OccupancyControlTrait, GraphKernelTrait, WorkTagTrait> >  {
```

I tested using this configuration (the xlc usr cnf files were pregenerated) with SHA 796ea4886996fc1b64c517a0243c847c35c21d19 as tip of this PR:

```
module load git cmake/3.19.3 cuda/10.1.105 gcc/7.2.0 ibm/xl/16.1.1

export KOKKOS_PATH=$HOME/kokkos

export XLC_USR_CONFIG=/opt/ibm/xlC/16.1.1/etc/xlc.cfg.rhel.7.6.gcc.7.2.0.cuda.10.1

cmake -DCMAKE_CXX_COMPILER=xlc++ -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -qxflag=disable__cplusplusOverride" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_PASCAL60=ON -DKokkos_ARCH_POWER8=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RELEASE -DCUDAToolkit_ROOT="/ascldap/users/projects/ppc64le-pwr8-nvidia/cuda/10.1.105" $KOKKOS_PATH
```

**Comment by masterleinad** [comment]
@ndellingwood Oh, yes sorry, we of course also need the other pull request that has now been merged to the release-candidate branch. Can you try if cherry-picking this commit onto that branch lets you compile the release branch?

**Comment by ndellingwood** [comment]
@masterleinad Cuda_Serial build of rc-3.4.0 with this fix successfully builds :)
Separate from this PR (but showing up when building), there are many warnings from cuda that we cannot control and I am not able to suppress with the `-Wno-unused-function` flag of the form:
```
/ascldap/users/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/include/cuda_fp16.hpp:394:22: warning: unused function '__float2half_rz' [-Wunused-function]
static inline __half __float2half_rz(const float a)
```

Any suggestions on a way to silence this warning? I also tried adding `-Xcudafe --diag_suppress=boolean_controlling_expr_is_constant` to the cxx flags but it did not help

**Comment by ndellingwood** [comment]
Hopefully this is encouraging, all unit tests passed for the Cuda_Serial build:

```
Test project /ascldap/users/ndellin/kokkos-bk/testing/White-XlCuda-Cmake
      Start  1: KokkosCore_UnitTest_Serial1
 1/49 Test  #1: KokkosCore_UnitTest_Serial1 ..................   Passed   15.43 sec
      Start  2: KokkosCore_UnitTest_Serial2
 2/49 Test  #2: KokkosCore_UnitTest_Serial2 ..................   Passed   12.73 sec
      Start  3: KokkosCore_UnitTest_SerialGraph
 3/49 Test  #3: KokkosCore_UnitTest_SerialGraph ..............   Passed    0.10 sec
      Start  4: KokkosCore_UnitTest_Cuda1
 4/49 Test  #4: KokkosCore_UnitTest_Cuda1 ....................   Passed   13.52 sec
      Start  5: KokkosCore_UnitTest_Cuda2
 5/49 Test  #5: KokkosCore_UnitTest_Cuda2 ....................   Passed   18.71 sec
      Start  6: KokkosCore_UnitTest_Cuda3
 6/49 Test  #6: KokkosCore_UnitTest_Cuda3 ....................   Passed   49.32 sec
      Start  7: KokkosCore_UnitTest_CudaTimingBased
 7/49 Test  #7: KokkosCore_UnitTest_CudaTimingBased ..........   Passed    0.55 sec
      Start  8: KokkosCore_UnitTest_CudaInterOpInit
 8/49 Test  #8: KokkosCore_UnitTest_CudaInterOpInit ..........   Passed    0.10 sec
      Start  9: KokkosCore_UnitTest_CudaInterOpStreams
 9/49 Test  #9: KokkosCore_UnitTest_CudaInterOpStreams .......   Passed    0.10 sec
      Start 10: KokkosCore_UnitTest_CudaGraph
10/49 Test #10: KokkosCore_UnitTest_CudaGraph ................   Passed    0.10 sec
      Start 11: KokkosCore_UnitTest_Default
11/49 Test #11: KokkosCore_UnitTest_Default ..................   Passed    0.21 sec
      Start 12: KokkosCore_UnitTest_PushFinalizeHook
12/49 Test #12: KokkosCore_UnitTest_PushFinalizeHook .........   Passed    0.09 sec
      Start 13: KokkosCore_UnitTest_Develop
13/49 Test #13: KokkosCore_UnitTest_Develop ..................   Passed    0.09 sec
      Start 14: KokkosCore_UnitTest_LogicalSpaces
14/49 Test #14: KokkosCore_UnitTest_LogicalSpaces ............   Passed    0.44 sec
      Start 15: KokkosCore_ProfilingTestLibraryLoadHelp
15/49 Test #15: KokkosCore_ProfilingTestLibraryLoadHelp ......   Passed    0.10 sec
      Start 16: KokkosCore_ProfilingTestLibraryCmdLineHelp
16/49 Test #16: KokkosCore_ProfilingTestLibraryCmdLineHelp ...   Passed    0.10 sec
      Start 17: KokkosCore_ProfilingTestLibraryLoad
17/49 Test #17: KokkosCore_ProfilingTestLibraryLoad ..........   Passed    0.10 sec
      Start 18: KokkosCore_ProfilingTestLibraryCmdLine
18/49 Test #18: KokkosCore_ProfilingTestLibraryCmdLine .......   Passed    0.09 sec
      Start 19: KokkosCore_UnitTest_StackTraceTest
19/49 Test #19: KokkosCore_UnitTest_StackTraceTest ...........   Passed    0.62 sec
      Start 20: KokkosCore_UnitTest_DefaultInit_1
20/49 Test #20: KokkosCore_UnitTest_DefaultInit_1 ............   Passed    0.10 sec
      Start 21: KokkosCore_UnitTest_DefaultInit_2
21/49 Test #21: KokkosCore_UnitTest_DefaultInit_2 ............   Passed    0.10 sec
      Start 22: KokkosCore_UnitTest_DefaultInit_3
22/49 Test #22: KokkosCore_UnitTest_DefaultInit_3 ............   Passed    0.10 sec
      Start 23: KokkosCore_UnitTest_DefaultInit_4
23/49 Test #23: KokkosCore_UnitTest_DefaultInit_4 ............   Passed    0.09 sec
      Start 24: KokkosCore_UnitTest_DefaultInit_5
24/49 Test #24: KokkosCore_UnitTest_DefaultInit_5 ............   Passed    0.09 sec
      Start 25: KokkosCore_UnitTest_DefaultInit_6
25/49 Test #25: KokkosCore_UnitTest_DefaultInit_6 ............   Passed    0.09 sec
      Start 26: KokkosCore_UnitTest_DefaultInit_7
26/49 Test #26: KokkosCore_UnitTest_DefaultInit_7 ............   Passed    0.10 sec
      Start 27: KokkosCore_UnitTest_DefaultInit_8
27/49 Test #27: KokkosCore_UnitTest_DefaultInit_8 ............   Passed    0.09 sec
      Start 28: KokkosCore_UnitTest_DefaultInit_9
28/49 Test #28: KokkosCore_UnitTest_DefaultInit_9 ............   Passed    0.10 sec
      Start 29: KokkosCore_UnitTest_DefaultInit_10
29/49 Test #29: KokkosCore_UnitTest_DefaultInit_10 ...........   Passed    0.10 sec
      Start 30: KokkosCore_UnitTest_DefaultInit_11
30/49 Test #30: KokkosCore_UnitTest_DefaultInit_11 ...........   Passed    0.10 sec
      Start 31: KokkosCore_UnitTest_DefaultInit_12
31/49 Test #31: KokkosCore_UnitTest_DefaultInit_12 ...........   Passed    0.09 sec
      Start 32: KokkosCore_UnitTest_DefaultInit_13
32/49 Test #32: KokkosCore_UnitTest_DefaultInit_13 ...........   Passed    0.10 sec
      Start 33: KokkosCore_UnitTest_DefaultInit_14
33/49 Test #33: KokkosCore_UnitTest_DefaultInit_14 ...........   Passed    0.10 sec
      Start 34: KokkosCore_UnitTest_DefaultInit_15
34/49 Test #34: KokkosCore_UnitTest_DefaultInit_15 ...........   Passed    0.10 sec
      Start 35: KokkosCore_UnitTest_DefaultInit_16
35/49 Test #35: KokkosCore_UnitTest_DefaultInit_16 ...........   Passed    0.10 sec
      Start 36: KokkosCore_UnitTest_DefaultInit_17
36/49 Test #36: KokkosCore_UnitTest_DefaultInit_17 ...........   Passed    0.10 sec
      Start 37: KokkosCore_UnitTest_DefaultInit_18
37/49 Test #37: KokkosCore_UnitTest_DefaultInit_18 ...........   Passed    0.10 sec
      Start 38: KokkosCore_IncrementalTest_CUDA
38/49 Test #38: KokkosCore_IncrementalTest_CUDA ..............   Passed    0.10 sec
      Start 39: KokkosCore_IncrementalTest_SERIAL
39/49 Test #39: KokkosCore_IncrementalTest_SERIAL ............   Passed    0.10 sec
      Start 40: KokkosCore_UnitTest_CTestDevice
40/49 Test #40: KokkosCore_UnitTest_CTestDevice ..............   Passed    0.01 sec
      Start 41: KokkosCore_UnitTest_CMakePassCmdLineArgs0
41/49 Test #41: KokkosCore_UnitTest_CMakePassCmdLineArgs0 ....   Passed    0.01 sec
      Start 42: KokkosCore_PerfTestExec
42/49 Test #42: KokkosCore_PerfTestExec ......................   Passed    4.98 sec
      Start 43: KokkosCore_PerformanceTest_Atomic
43/49 Test #43: KokkosCore_PerformanceTest_Atomic ............   Passed   19.81 sec
      Start 44: KokkosCore_PerformanceTest_Mempool
44/49 Test #44: KokkosCore_PerformanceTest_Mempool ...........   Passed    0.10 sec
      Start 45: KokkosCore_PerformanceTest_TaskDag
45/49 Test #45: KokkosCore_PerformanceTest_TaskDag ...........   Passed    0.01 sec
      Start 46: KokkosContainers_UnitTest_Serial
46/49 Test #46: KokkosContainers_UnitTest_Serial .............   Passed   42.83 sec
      Start 47: KokkosContainers_UnitTest_Cuda
47/49 Test #47: KokkosContainers_UnitTest_Cuda ...............   Passed   17.03 sec
      Start 48: KokkosContainers_PerformanceTest_Cuda
48/49 Test #48: KokkosContainers_PerformanceTest_Cuda ........   Passed    0.75 sec
      Start 49: KokkosAlgorithms_UnitTest
49/49 Test #49: KokkosAlgorithms_UnitTest ....................   Passed  333.88 sec

100% tests passed, 0 tests failed out of 49

Total Test time (real) = 533.89 sec
```

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
Plz cherry pick this in release candidate
