### ISSUE TITLE
Kokkos updates breaking Trilinos builds 8/12/2021

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4237]
A recent update to Kokkos on 8/12/2021 is breaking builds with Trilinos, in particular the Sacado package. Looking at the error message and recent changes, most likely PR #4226 triggered the issue

This is for a build with cuda/10.1 on Volta70 arch:

```
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/kokkos/core/src/impl/Kokkos_ViewMapping.hpp(2895): error: no instance of constructor "Kokkos::View<DataType, Properties...>::View [with DataType=InnerFadType *, Properties=<Kokkos::Serial::memory_space, Kokkos::MemoryTraits<1U>>]" matches the argument list
18:56:43             argument types are: (InnerFadType *, size_t)
18:56:43           detected during:
18:56:43             instantiation of "void Kokkos::Impl::ViewValueFunctor<DeviceType, ValueType, false>::execute(__nv_bool) [with DeviceType=Kokkos::HostSpace::execution_space, ValueType=InnerFadType]" 
18:56:43 (2931): here
18:56:43             instantiation of "void Kokkos::Impl::ViewValueFunctor<DeviceType, ValueType, false>::construct_shared_allocation() [with DeviceType=Kokkos::HostSpace::execution_space, ValueType=InnerFadType]" 
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/sacado/src/KokkosExp_View_Fad.hpp(1426): here
18:56:43             instantiation of "Kokkos::Impl::SharedAllocationRecord<void, void> *Kokkos::Impl::ViewMapping<Traits, std::enable_if<<expression>, Traits::specialize>::type>::allocate_shared(const Kokkos::Impl::ViewCtorProp<P...> &, const Traits::array_layout &) [with Traits=Kokkos::ViewTraits<SFadType **, Kokkos::LayoutLeft, Kokkos::Serial>, P=<std::__cxx11::string, std::integral_constant<unsigned int, 0U>, Kokkos::HostSpace::memory_space, Kokkos::HostSpace::execution_space>]" 
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/kokkos/core/src/Kokkos_View.hpp(1552): here
18:56:43             instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::Impl::ViewCtorProp<P...> &, const std::enable_if<<expression>, Kokkos::ViewTraits<DataType, Properties...>::array_layout>::type &) [with DataType=SFadType **, Properties=<Kokkos::LayoutLeft, Kokkos::Serial>, P=<std::__cxx11::string>]" 
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/kokkos/core/src/Kokkos_View.hpp(1697): here
18:56:43             instantiation of "Kokkos::View<DataType, Properties...>::View(const Label &, std::enable_if<Kokkos::Impl::is_view_label<Label>::value, const size_t>::type, size_t, size_t, size_t, size_t, size_t, size_t, size_t) [with DataType=SFadType **, Properties=<Kokkos::LayoutLeft, Kokkos::Serial>, Label=char [6]]" 
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/sacado/test/UnitTests/Fad_Fad_KokkosTests.hpp(124): here
18:56:43             instantiation of "void Kokkos_View_FadFad_DeepCopy_UnitTest<FadFadType, Layout, Device>::runUnitTestImpl(Teuchos::FancyOStream &, __nv_bool &) const [with FadFadType=SFadType, Layout=Kokkos::LayoutLeft, Device=Kokkos::Serial]" 
18:56:43 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/sacado/test/UnitTests/Fad_Fad_KokkosTests_Serial.cpp(40): here
18:56:43 
18:56:43 1 error detected in the compilation of "/tmp/tmpxft_00003298_00000000-6_Fad_Fad_KokkosTests_Serial.cpp1.ii".
```

Nightly Build Reproducer (weaver testbed):
```
# Create symbolic links to kokkos and kokkos-kernels in Trilinos for source override
export TRILINOS_DIR=<somepath-to-trilinos-source>
export KOKKOS_DIR=<somepath>
export KOKKOSKERNELS_DIR=<somepath>

cd $TRILINOS_DIR
  # the n and f flags were needed for Jenkins, probably not needed in a local interactive build
ln -snf ${KOKKOS_DIR} kokkos
ln -snf ${KOKKOSKERNELS_DIR} kokkos-kernels


# Modules and environment
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/weaver
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt

module list
export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper
export TRILINOS_INSTALL_DIR=${PWD}/install

cd <your-build-dir>

# Configuration
cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
 -DCMAKE_CXX_STANDARD="14" \
 -DTrilinos_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
 -DSEACASIoss_structured_cgns_assembly_copy_DISABLE=ON \
 -DSEACASIoss_structured_cgns_assembly_copy_fpp_DISABLE=ON \
 -DIntrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1_DISABLE=ON \
 -DKokkosCore_UnitTest_CudaTimingBased_MPI_1_DISABLE=ON \
$TRILINOS_DIR
```

Since this occurs in Sacado (and mayalso occur with tests from Stokhos), a potentially more simplified general test configuration (I haven't verified):

```
# load modules, newer cmake, cuda/10.1

export TRILINOS_DIR=<somepath-to-trilinos-source>
export KOKKOS_DIR=<somepath>
export KOKKOSKERNELS_DIR=<somepath>

cd $TRILINOS_DIR
  # the n and f flags were needed for Jenkins, probably not needed in a local interactive build
ln -n ${KOKKOS_DIR} kokkos
ln -n ${KOKKOSKERNELS_DIR} kokkos-kernels

export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper
export TRILINOS_INSTALL_DIR=${PWD}/install

cd <your-build-dir>

# Configuration
cmake \
 -GNinja \
 -DCMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
 -DCMAKE_CXX_STANDARD="14" \
 -DTrilinos_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
 -DTrilinos_ENABLE_Sacado=ON \
 -DTrilinos_ENABLE_Kokkos=ON \
 -DKokkos_ENABLE_CUDA=ON \
 -DKokkos_ARCH_VOLTA70=ON \
 -DKokkos_ENABLE_CUDA_UVM=ON \
 -DKokkosCore_UnitTest_CudaTimingBased_MPI_1_DISABLE=ON \
$TRILINOS_DIR
```

**Comment by ndellingwood** [comment]
I manually tested a Trilinos build that missed the merge of PR #4240 last night and compilation passes the Trilinos builds, thanks @masterleinad
