### ISSUE TITLE
Nightly build failure with gcc on Power9+Volta70 in Kokkos_NumericTraits with constexpr T Kokkos::Experimental::Impl::safe_minimum: error: is not a constant expression

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4485]
Various nightly builds with cuda/9.2 and cuda/10.{0,1} and/or gcc/6 or gcc/7.2 on Power9 + Volta are failing in Kokkos_NumericTraits with apparent issues handling `long double` in constexpr usage:

**Sample output snip**
```
04:14:38 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_cuda_9288_gcc_720_volta-dbg/kokkos/core/src/Kokkos_NumericTraits.hpp: In instantiation of ‘constexpr T Kokkos::Experimental::Impl::safe_minimum(T) [with T = long double]’:
04:14:38 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_cuda_9288_gcc_720_volta-dbg/kokkos/core/src/Kokkos_NumericTraits.hpp:151:122:   required from here
04:14:38 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_cuda_9288_gcc_720_volta-dbg/kokkos/core/src/Kokkos_NumericTraits.hpp:145:29: error: ‘(1.0e+0l / 1.79769313486231570800000000000001e+308l)’ is not a constant expression
04:14:38    constexpr auto small = one / huge;
```

**Sample reproducer** (cuda/9.2+gcc/7.2 Cuda_Serial debug build):
```
module load cmake/3.19.3 cuda/9.2.88 gcc/7.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=Power9,Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --with-cuda-options=enable_lambda  --no-examples --with-options=enable_large_mem_tests --debug
```

This is following merge of #4473 @dalg24 are you able to take a look?

Edit: This seems to be more specifically an issue with gcc, not just with the cuda builds
