### ISSUE TITLE
Nightly build errors with cuda/9.2+Kepler arch: error calling device function from host device function

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4784]
Nightly cuda/9.2 builds, Kepler arch began failing to compile with error messages:

```
04:43:31 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_cuda_92-dbg-boundscheck/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp(115): error: calling a __device__ function("__activemask") from a __host__ __device__ function("impl_acquire") is not allowed
04:43:31 
04:43:31 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_cuda_92-dbg-boundscheck/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp(116): error: calling a __device__ function("__ballot_sync") from a __host__ __device__ function("impl_acquire") is not allowed
04:43:31 
04:43:31 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_cuda_92-dbg-boundscheck/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp(128): error: calling a __device__ function("__ballot_sync") from a __host__ __device__ function("impl_acquire") is not allowed
04:43:31 
04:43:31 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_cuda_92-dbg-boundscheck/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp(115): error: calling a __device__ function("__activemask") from a __host__ __device__ function("impl_acquire") is not allowed
04:43:31 
04:43:31 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_cuda_92-dbg-boundscheck/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp(116): error: calling a __device__ function("__ballot_sync") from a __host__ __device__ function("impl_acquire") is not allowed
04:43:31 
04:43:31 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_cuda_92-dbg-boundscheck/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp(128): error: calling a __device__ function("__ballot_sync") from a __host__ __device__ function("impl_acquire") is not allowed
```

Failures coincide with merge of #4741, @crtrott can you investigate?

**Reproducer** (kokkos-dev):
```
module load sems-archive-env sems-archive-cmake/3.17.1 sems-archive-gcc/6.1.0 sems-archive-cuda/9.2

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=Kepler35 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --boundscheck --no-examples --with-options=enable_large_mem_tests --debug
```

**Comment by ndellingwood** [comment]
Looks like #4783 was already submitted

**Comment by ndellingwood** [comment]
Reran failing nightly build and confirmed #4783 fixed the compilation error

**Comment by ajpowelsnl** [comment]
Good morning @ndellingwood -- can we close this issue now?  We can re-open, if necessary.

**Comment by ndellingwood** [comment]
@ajpowelsnl yes, this is resolved and confirmed to fix the nightly builds
