### PR TITLE
Fix Intel19 issue with const variable requiring an initializer

### LINKED ISSUE #7404: Nightly build failures, intel/19.0.5 icpc, Kokkos_BasicView.hpp(43): error #854...
**Describe the bug**

Nightly builds with intel/19.0.5 fail to compile with the following type of error:
```
11:45:16 In file included from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Kokkos_View.hpp(26),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Kokkos_Parallel.hpp(31),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Kokkos_MemoryPool.hpp(26),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Kokkos_TaskScheduler.hpp(34),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Serial/Kokkos_Serial.hpp(37),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/decl/Kokkos_Declare_SERIAL.hpp(21),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/TestAll_2024-10-04_11.44.36/intel/19.0.5/Serial-debug/KokkosCore_Config_DeclareBackend.hpp(22),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/Kokkos_Core.hpp(45),
11:45:16                  from /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/impl/Kokkos_Core.cpp(21):
11:45:16 /data/jenkins/workspace/kokkos_osrhel8_intel_1905-dbg/kokkos/core/src/View/Kokkos_BasicView.hpp(43): error #854: const variable "Kokkos::Impl::subview_ctor_tag" requires an initializer -- class "Kokkos::Impl::SubViewCtorTag" has no user-provided default constructor
11:45:16   } subview_ctor_tag;
11:45:16     ^
```

This follows merge of #7385 , @crtrott 

**Please include the following for a minimal reproducer**

**Reproducer**:
```bash
module load sems-cmake sems-intel/19.0.5

cmake -DCMAKE_CXX_COMPILER=icpc -DCMAKE_CXX_FLAGS="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -diag-disable=1011 -diag-disable=869" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=DEBUG -DKokkos_ENABLE_DEBUG=ON -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF $KOKKOS_PATH
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #7404 (not tested)

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
See https://github.com/kokkos/kokkos/pull/7385#issuecomment-2394272713.

**Comment by masterleinad** [comment]
```
AppVeyor was unable to build non-mergeable pull request 
```
not sure why it's complaining here. I don't see conflicts.

**Review by ldh4 — APPROVED** [review]

**Comment by dalg24** [comment]
Retest this please

**Comment by ndellingwood** [comment]
ICE is present in Serial icpc builds in a couple unit tests when specifying an arch (e.g. SKX), but unrelated to changes in this PR
