### ISSUE TITLE
Nightly build failures, intel/19.0.5 icpc: Kokkos_View.hpp(973): error #1011: missing return statement at end of non-void function...

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7071]
**Describe the bug**
Nightly builds with intel/19.0.5 icpc are failing to compile with output:
```
14:30:11 /home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Kokkos_View.hpp(973): error #1011: missing return statement at end of non-void function "Kokkos::View<DataType, Properties...>::operator()(I0, I1) const [with DataType=uint64_t={unsigned long} **, Properties=<std::conditional_t<true, Kokkos::Serial::array_layout, Kokkos::Serial::array_layout>, Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>, std::conditional_t<false,
14:30:11           void, Kokkos::Experimental::DefaultViewHooks>>, I0=int, I1=int]"
14:30:11     }
14:30:11     ^
14:30:11           detected during:
14:30:11             instantiation of "std::enable_if_t<<expression>, Kokkos::View<DataType, Properties...>::reference_type> Kokkos::View<DataType, Properties...>::operator()(I0, I1) const [with DataType=uint64_t={unsigned long} **, Properties=<std::conditional_t<true, Kokkos::Serial::array_layout, Kokkos::Serial::array_layout>, Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>, std::conditional_t<false, void, Kokkos::Experimental::DefaultViewHooks>>, I0=int, I1=int]" at
14:30:11                       line 933 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/algorithms/unit_tests/../src/Kokkos_Random.hpp"
14:30:11             instantiation of "void Kokkos::Random_XorShift64_Pool<DeviceType>::init(uint64_t={unsigned long}, int) [with DeviceType=Kokkos::Serial]" at line 903 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/algorithms/unit_tests/../src/Kokkos_Random.hpp"
14:30:11             instantiation of "Kokkos::Random_XorShift64_Pool<DeviceType>::Random_XorShift64_Pool(uint64_t={unsigned long}) [with DeviceType=Kokkos::Serial]" at line 394 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/algorithms/unit_tests/TestRandom.hpp"
14:30:11             instantiation of "void Test::AlgoRandomImpl::test_random<RandomGenerator>(unsigned int) [with RandomGenerator=Kokkos::Random_XorShift64_Pool<Kokkos::Serial>]" at line 553 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/algorithms/unit_tests/TestRandom.hpp"
...
```

This follows merge of these commits:

    Fix mdspan test ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/1064/changes#1d7ccd8df67681ac1e3e85623f5dd02a726cd4de) / [githubweb](https://github.com/kokkos/kokkos/commit/1d7ccd8df67681ac1e3e85623f5dd02a726cd4de))
    Update to CUDA 12.4.1 in MSVC CI ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/1064/changes#363b464f5ac02924e0c06a4d78e2d47f42fe4cc9) / [githubweb](https://github.com/kokkos/kokkos/commit/363b464f5ac02924e0c06a4d78e2d47f42fe4cc9))
    Workaround MSVC compiler issues in Views ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/1064/changes#d50a878324681fdaed9255566bdcb4bd9d64ed36) / [githubweb](https://github.com/kokkos/kokkos/commit/d50a878324681fdaed9255566bdcb4bd9d64ed36))
    Avoid lambda in sort_by_key_via_sort ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/1064/changes#90d8770367399242424f574b206afe955aa2840a) / [githubweb](https://github.com/kokkos/kokkos/commit/90d8770367399242424f574b206afe955aa2840a))

It looks like older icpc versions don't handle well some of the nice refactor clean up of the operator() of the View from #7068

**Please include the following for a minimal reproducer**
Reproducer:
```bash
module load sems-cmake sems-intel/19.0.5

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH

```

**Comment by masterleinad** [comment]
> It looks like older icpc versions don't handle well some of the nice refactor clean up of the operator() of the View from #7068

Yeah, we can probably just use  `__builtin_unreachable` again (or return a default constructed value if the type is default-constructible).

**Comment by ndellingwood** [comment]
@masterleinad yeah, I added the workaround in a couple spots until the job passed for me, PR #7072 up if you can give a quick review+approval, thanks!
