### ISSUE TITLE
Nightly failures with in builds with gcc/9.1, 9.2 in toolchain: TestBitManipulationBuiltins.hpp: error: no matching function for call to ‘TestBitCastFunction<Space>::check...

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6107]
**Describe the bug**
Nightly builds with gcc/9.1 or gcc/9.2 in the toolchain failed to compile the `TestBitManipulationBuiltins.hpp` unit test following merge of #6101  with error output:

cuda/11.7 and cuda/11.2 with gcc/9.2
```
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:812:27: error: no matching function for call to ‘TestBitCastFunction<Space>::check<int>(float) const’
09:12:03   812 |       if (!check<int>(12.34f)) {
09:12:03       |                           ^
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:792:1: note: candidate: ‘template<class Space> template<class To, class From> static bool TestBitCastFunction<Space>::check(const From&)’
09:12:03   792 |   static KOKKOS_FUNCTION bool check(const From& from) {
09:12:03       | ^ ~~~
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:792:1: note:   template argument deduction/substitution failed:
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:812:27: note:   mismatched types ‘const From’ and ‘float’
09:12:03   812 |       if (!check<int>(12.34f)) {
09:12:03       |                           ^
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:818:43: error: no matching function for call to ‘TestBitCastFunction<Space>::check<long long unsigned int>(double) const’
09:12:03   818 |       if (!check<unsigned long long>(123.456)) {
09:12:03       |                                           ^
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:792:1: note: candidate: ‘template<class Space> template<class To, class From> static bool TestBitCastFunction<Space>::check(const From&)’
09:12:03   792 |   static KOKKOS_FUNCTION bool check(const From& from) {
09:12:03       | ^ ~~~
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:792:1: note:   template argument deduction/substitution failed:
09:12:03 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkosdev2_cuda117_gcc920_cpp17/kokkos/core/unit_test/TestBitManipulationBuiltins.hpp:818:43: note:   mismatched types ‘const From’ and ‘double’
09:12:03   818 |       if (!check<unsigned long long>(123.456)) {

```

@dalg24 can you investigate?

Reproducer:
```bash
module load sems-archive-env sems-archive-cmake/3.17.1 sems-archive-gcc/9.2.0 cuda/11.7

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --with-cuda-options=enable_lambda  --no-examples   --with-options=enable_large_mem_tests
```

**Comment by dalg24** [comment]
We have a CUDA-11.7 GCC-9.3.0 (instead of 9.2.0) build in CI which is passing.
I tried a couple things on godbolt and could not reproduce.  Pasting it [here](https://godbolt.org/z/31nxxGWEK) in case someone wants to try harder than me.

I don't have access to your machine so you will have to investigate yourself.  Compiler bugs are always fun.

**Comment by ndellingwood** [comment]
More nightly builds failed with gcc/9.1 and gcc/9.2, updated the title to better reflect that

Reproducer notes for gcc/9.2 build on x86_64 (happens with all host backends):
```bash
module load cmake/3.19.3 gcc/9.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial --arch=SKX --compiler=g++ --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""  --kokkos-path=$KOKKOS_PATH --no-examples   --with-options=enable_large_mem_tests --debug
```
