### ISSUE TITLE
OpenMP target 

### ISSUE THREAD

**Issue by hamidrezanorouzi** [kokkos/kokkos#6193]
I am adding OpenMP Target backend to my code (https://github.com/phasicFlow). When I enable OpenMPTarget as the device, and Serial as the host, and compile the code, I get an error:
```
/home/cem3/Kokkos/kokkos/core/src/Kokkos_Macros.hpp:482:23: error: redefinition of ‘constexpr bool kokkos_omp_on_host()’
  482 | static constexpr bool kokkos_omp_on_host() { return true; }
      |                       ^~~~~~~~~~~~~~~~~~
/home/cem3/Kokkos/kokkos/core/src/Kokkos_Macros.hpp:479:23: note: ‘constexpr bool kokkos_omp_on_host()’ previously defined here
  479 | static constexpr bool kokkos_omp_on_host() { return true; }
      |                       ^~~~~~~~~~~~~~~~~~
/home/cem3/Kokkos/kokkos/core/src/Kokkos_Macros.hpp:483:25: error: expected ‘target’ before ‘variant’
  483 | #pragma omp end declare variant
      |                         ^~~~~~~
/home/cem3/Kokkos/kokkos/core/src/Kokkos_Macros.hpp:486:23: error: redefinition of ‘constexpr bool kokkos_omp_on_host()’
  486 | static constexpr bool kokkos_omp_on_host() { return false; }
      |                       ^~~~~~~~~~~~~~~~~~
/home/cem3/Kokkos/kokkos/core/src/Kokkos_Macros.hpp:479:23: note: ‘constexpr bool kokkos_omp_on_host()’ previously defined here
  479 | static constexpr bool kokkos_omp_on_host() { return true; }
      |                       ^~~~~~~~~~~~~~~~~~
/home/cem3/Kokkos/kokkos/core/src/Kokkos_Macros.hpp:487:25: error: expected ‘target’ before ‘variant’
  487 | #pragma omp end declare variant

```

I am compiling on ubuntu 20.04 and using g++-v9.4 compiler, and Kokkos version is the latest version (develop branch).

I get the following output from cmake configuration:
```
Kokkos source directory is /home/cem3/Kokkos/kokkos
Setting default Kokkos CXX standard to 17
Kokkos version: 4.0.99
The project name is: Kokkos
Using internal gtest for testing
Using -std=gnu++17 for C++17 extensions as feature
Built-in Execution Spaces:
    Device Parallel: Kokkos::Experimental::OpenMPTarget
    Host Parallel: NoTypeDefined
      Host Serial: SERIAL

Architectures:
Using internal desul_atomics copy
Kokkos Devices: OPENMPTARGET;SERIAL, Kokkos Backends: OPENMPTARGET;SERIAL
Configuring done
```

**Comment by dalg24** [comment]
@rgayatri23 please see if you can error out at configuration time when the CXX compiler is GCC.

**Comment by rgayatri23** [comment]
Yeah I am installing the latest gcc/13.1 to see if we can get the OpenMPTarget backend to work with gcc compiler. 
I am quite confident that we cannot make it work with gcc/9.4 or anything that is less than gcc/12.x

**Comment by masterleinad** [comment]
This also reminds me that you wanted to update the minimum compiler versions for `OpenMPTarget`.

**Comment by hamidrezanorouzi** [comment]
Thanks for the replies. I installed clang-16 (v-16.0.5) on Ubuntu-20.04 and changed the cmake system (attached file) and compiled it for SERIAL execution only. I got the following error: 

In file included from /home/cem3/PhasicFlow/other/main.cpp:2:
In file included from /home/cem3/Kokkos/kokkos/core/src/Kokkos_Core.hpp:43:
In file included from /home/cem3/Kokkos/kokkos/core/src/Kokkos_Core_fwd.hpp:29:
/home/cem3/Kokkos/kokkos/core/src/impl/Kokkos_Error.hpp:20:10: fatal error: 'string' file not found

[CMakeLists.txt](https://github.com/kokkos/kokkos/files/11687630/CMakeLists.txt)

**Comment by rgayatri23** [comment]
Is this the string file in the compiler toolchain? Can you try adding the following option to your CMake command
```shell
-DCMAKE_CXX_FLAGS="--gcc-toolchain=/path-to-gcc"
```

**Comment by hamidrezanorouzi** [comment]
Still get the same error.

kokkossimd
kokkoscore
kokkoscontainers

are build. When compiling the executable (here main.cpp), it issues an error. Not only the string header file, other standard C++ headers like iostream. 
Further, I installed libc++-dev-16 on my computer, to fix the issue. The problem with header files was solved, but I got tons of linkage error when the compiler wanted to make the executable. I removed all the include files from Kokkos, and only kept iostream header in the executable. I built it and get the following error 
```
/usr/bin/ld: CMakeFiles/test.dir/main.cpp.o: in function `__cxx_global_var_init':
main.cpp:(.text.startup+0xc): undefined reference to `std::ios_base::Init::Init()'
/usr/bin/ld: main.cpp:(.text.startup+0x13): undefined reference to `std::ios_base::Init::~Init()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/test.dir/build.make:100: test] Error 1
make[1]: *** [CMakeFiles/Makefile2:280: CMakeFiles/test.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
I am sure there is something wrong with my settings in CMakefileList, but I don't know where.

**Comment by masterleinad** [comment]
What does the failing compile line/link line look like? To me, it seems more like your toolchain is broken than that there is something wrong with your `CMakeLists.txt` file.

**Comment by hamidrezanorouzi** [comment]
I cloned Kokkos onto the following address on my computer:
~/Kokkos/kokkos
and I created a project in a sub-folder on home directory. See the CMakeLists of the project. It is attached. 

[CMakeLists.txt](https://github.com/kokkos/kokkos/files/11720060/CMakeLists.txt)

My computer: Intel Core-i5, GPU: GeForce-1050
command line for cmake: 
`cmake ./.. `

**Comment by rgayatri23** [comment]
Your C and C++ compilers seem to be wrong.
```
set(CMAKE_C_COMPILER "/usr/bin/clang-16" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "/usr/bin/clang-16" CACHE STRING "" FORCE)
```

They should be `clang` and `clang++` 

Also is the problem in building Kokkos or during building an app to use Kokkos?

**Comment by hamidrezanorouzi** [comment]
Thanks for the help. I made a mistake at setting C and C++ the compilers. The problem with standard C++ headers now resolved. 
The CMakeLists.txt now looks like this:

[CMakeLists.txt](https://github.com/kokkos/kokkos/files/11737189/CMakeLists.txt)

Now I run the cmake with the following command line


cmake ./.. -**DKokkos_ENABLE_OPENMP=ON** -DKokkos_ENABLE_OPENMPTARGET=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DKokkos_ARCH_PASCAL61=ON


and I get the following error.
```
Kokkos source directory is /home/cem3/Kokkos/kokkos
-- Setting default Kokkos CXX standard to 17
-- Kokkos version: 4.0.99
-- The project name is: Kokkos
-- Using internal gtest for testing
-- Using -std=gnu++17 for C++17 extensions as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Experimental::OpenMPTarget
--     Host Parallel: Kokkos::OpenMP
--       Host Serial: SERIAL
-- 
-- Architectures:
--  PASCAL61
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindOpenMP.cmake:511 (find_package_handle_standard_args)
  /home/cem3/Kokkos/kokkos/cmake/kokkos_tpls.cmake:102 (find_package)
  /home/cem3/Kokkos/kokkos/cmake/kokkos_tribits.cmake:207 (INCLUDE)
  /home/cem3/Kokkos/kokkos/CMakeLists.txt:226 (KOKKOS_SETUP_BUILD_ENVIRONMENT)
```

and when I run it with the following CL: 

cmake ./.. -**DKokkos_ENABLE_OPENMP=OFF** -DKokkos_ENABLE_OPENMPTARGET=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ 

it works fine and create the build system. But in compiling the code, it gives the following error:
```
[  3%] Building CXX object kokkos/simd/src/CMakeFiles/kokkossimd.dir/Kokkos_SIMD_dummy.cpp.o
[  6%] Linking CXX static library libkokkossimd.a
[  6%] Built target kokkossimd
Scanning dependencies of target kokkoscore
[  9%] Building CXX object kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o
[ 12%] Building CXX object kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Command_Line_Parsing.cpp.o
[ 16%] Building CXX object kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o
In file included from /home/cem3/Kokkos/kokkos/core/src/impl/Kokkos_Core.cpp:21:
In file included from /home/cem3/Kokkos/kokkos/core/src/Kokkos_Core.hpp:45:
In file included from /home/cem3/PhasicFlow/other/build/kokkos/KokkosCore_Config_DeclareBackend.hpp:22:
In file included from /home/cem3/Kokkos/kokkos/core/src/decl/Kokkos_Declare_OPENMPTARGET.hpp:21:
/home/cem3/Kokkos/kokkos/core/src/OpenMPTarget/Kokkos_OpenMPTarget.hpp:29:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make[2]: *** [kokkos/core/src/CMakeFiles/kokkoscore.dir/build.make:89: kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1140: kokkos/core/src/CMakeFiles/kokkoscore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by rgayatri23** [comment]
In both cases, it looks like CMake cannot find OpenMP. Just to be sure, the clang build has been enabled with OpenMP right?

**Comment by hamidrezanorouzi** [comment]
How can I check this?

**Comment by rgayatri23** [comment]
You can probably write a small code yourself, something like
```c++
#include<iostream>
#include<omp.h>

int main()
{
   #pragma omp target 
   {
       printf("Hello from inside the target region\n");
    }
}
```

And compile it as 
`clang++ foo.cpp -fopenmp -foffload -fopenmp-targets=nvptx64 -o foo.ex`

**Comment by hamidrezanorouzi** [comment]
I did so. I compiled with the above CL and I got:
```
clang: error: unknown argument: '-foffload'
clang: error: cannot determine nvptx64 architecture: nvptx-arch: Executable "nvptx-arch" doesn't exist!; consider passing it via '-march'
clang: error: no library 'libomptarget-nvptx-sm_35.bc' found in the default clang lib directory or in LIBRARY_PATH; use '--libomptarget-nvptx-bc-path' to specify nvptx bitcode library
```

And, I removed the flag related to offloading, I recompiled and I got: 
```
clang++ foo.cpp -fopenmp -o foo.ex

foo.cpp:4:10: fatal error: 'omp.h' file not found
#include <omp.h>
```

**Comment by ajpowelsnl** [comment]
@hamidrezanorouzi - have you been able to move forward with this help?  If so, may we close the issue?

**Comment by hamidrezanorouzi** [comment]
Yes. thanks
